import{GuideService}from'./guide.service';import{GUIDE_KNOWLEDGE}from'./guide-knowledge';
describe('public Concierge Guide Copilot',()=>{
 const golden:[string,string][]=[['ChatGPT하고 뭐가 다른가요?','CHATGPT_DIFFERENCE'],['구글이 있는데 왜 필요해요?','MAP_DIFFERENCE'],['네이버 지도면 되지 않나요?','MAP_DIFFERENCE'],['그냥 검색하면 되잖아요.','SEARCH_CONTINUITY'],['AI 정보가 틀리면요?','DATA_ACCURACY'],['누가 지역정보를 관리하나요?','DATA_STEWARDSHIP'],['돈 내는 업체를 먼저 추천하나요?','PAID_RANKING'],['업체가 참여하면 뭐가 좋아요?','BUSINESS_VALUE'],['지자체가 꼭 해야 하나요?','MUNICIPALITY_VALUE'],['합천에서만 되나요?','REGIONAL_SCALE'],['내 위치는 어떻게 사용하나요?','PRIVACY_LOCATION'],['여행을 닫았다 다시 열면 어떻게 되나요?','PRIVACY_LOCATION'],['구글도 요즘 AI 추천하는데요?','MAP_OBJECTION'],['ChatGPT한테 위치 알려주면 똑같지 않나요?','MAP_OBJECTION']];
 it.each(golden)('%s resolves to approved %s knowledge',(question,intent)=>expect(new GuideService().answer({question},question)).toMatchObject({status:'ANSWERED',intent,readOnly:true}));
 it('adapts perspective without requiring role selection',()=>{expect(new GuideService().answer({question:'업체가 참여하면 뭐가 좋아요?'},'b')).toMatchObject({audience:'BUSINESS',answer:expect.stringContaining('업체 입장에서')});expect(new GuideService().answer({question:'지자체가 꼭 해야 하나요?'},'p')).toMatchObject({audience:'PUBLIC_SECTOR',answer:expect.stringContaining('공공 관점')})});
 it('handles a Google follow-up without repeating or denying Google recommendation',()=>{const service=new GuideService(),first:any=service.answer({question:'구글이 있잖아요.'},'f'),next:any=service.answer({question:'그래도 구글도 추천해주잖아요.',previousIntent:first.intent},'f');expect(next).toMatchObject({intent:'MAP_OBJECTION'});expect(next.answer).toMatch(/맞습니다.*추천/);expect(next.answer).not.toBe(first.answer)});
 it('keeps every approved answer free of prohibited marketing claims',()=>{const answers=GUIDE_KNOWLEDGE.map(x=>x.shortAnswer).join(' ');for(const claim of ['세계 최초','100% 정확','매출 보장','ChatGPT는 여행 추천을 못한다','Google은 추천을 못한다'])expect(answers).not.toContain(claim)});
 it('returns a non-persisted human-review candidate for unknown field questions',()=>expect(new GuideService().answer({question:'우리 동네만의 새 질문입니다'},'u')).toMatchObject({status:'REVIEW_CANDIDATE',candidate:{type:'NEW_GUIDE_QUESTION',questionStored:false,requiresHumanApproval:true}}));
 it('rate limits the public endpoint per client without authentication',()=>{const service=new GuideService();for(let i=0;i<20;i++)service.answer({question:'무슨 서비스인가요?'},'same');expect(()=>service.answer({question:'무슨 서비스인가요?'},'same')).toThrow('Guide request limit exceeded')});
});
