export type GuideAudience='VISITOR'|'BUSINESS'|'PUBLIC_SECTOR'|'GENERAL';
export type GuideKnowledge={intent:string;audiences:GuideAudience[];patterns:RegExp[];shortAnswer:string;supportingConcepts:string[];example?:string;allowedClaims:string[];prohibitedClaims:string[];relatedQuestions:string[]};

const prohibited=['ChatGPT는 여행 추천을 못한다','Google은 추천을 못한다','네이버는 부정확하다','세계 최초','100% 정확','매출 보장','유료 업체 우선 노출'];
const item=(value:Omit<GuideKnowledge,'prohibitedClaims'>):GuideKnowledge=>({...value,prohibitedClaims:prohibited});

export const GUIDE_KNOWLEDGE:GuideKnowledge[]=[
 item({intent:'CHATGPT_DIFFERENCE',audiences:['GENERAL','VISITOR'],patterns:[/chatgpt|챗gpt|챗지피티|범용\s*ai/i],shortAnswer:'ChatGPT는 아주 폭넓은 질문에 답할 수 있는 범용 AI입니다. 지역 AI 컨시어지는 그런 AI를 지역의 검증된 정보와 현재 여행 상황에 연결해 실제 현장에서 일하도록 만든 서비스입니다. 단순히 답을 주는 데서 끝나지 않고 현재 여행을 이어서 다음 행동까지 연결하는 데 초점을 둡니다.',supportingConcepts:['RDM','runtime context','TripSession','actions'],allowedClaims:['범용 AI와 지역 운영 시스템의 역할 차이'],relatedQuestions:['ChatGPT한테 위치를 알려주면 똑같지 않나요?','실제 여행에서는 어떻게 이어지나요?']}),
 item({intent:'MAP_DIFFERENCE',audiences:['GENERAL','VISITOR'],patterns:[/구글|google|네이버\s*지도|지도.*(?:왜|필요)|다\s*해주/i],shortAnswer:'맞습니다. 지도 서비스는 장소를 찾고 길을 안내하는 데 매우 뛰어납니다. 지역 AI 컨시어지가 집중하는 것은 그 많은 장소 중 현재 위치, 남은 시간, 동행자, 날씨와 기존 여행을 함께 보고 지금 무엇이 맞는지 판단하는 일입니다. Maps find places. The Concierge helps decide what fits now.',supportingConcepts:['current location','runtime context','journey continuity'],allowedClaims:['서로 다른 초점','지도 서비스의 강점 인정'],relatedQuestions:['구글도 요즘 AI 추천하는데요?','그냥 검색하면 되지 않나요?']}),
 item({intent:'MAP_OBJECTION',audiences:['GENERAL','VISITOR'],patterns:[/구글도.*(?:추천|ai)|지도도.*추천|위치.*알려.*똑같/i],shortAnswer:'맞습니다. 범용 AI와 지도 서비스도 위치 기반 추천을 제공할 수 있습니다. 이 플랫폼이 좁게 집중하는 차이는 지역 관리자가 검토한 운영 데이터, 여러 질문 사이의 여행 연속성, 현재 일정 상태와 안전한 행동 연결을 한 구조에서 다루는 점입니다. 모든 면에서 더 낫다는 뜻이 아니라 지역 현장 운영에 맞춘 역할입니다.',supportingConcepts:['RDM','Regional Copilot','current-turn','action safety'],allowedClaims:['기능 중첩 인정','지역 운영 초점'],relatedQuestions:['정보는 누가 검토하나요?','여행을 닫았다 열면 어떻게 되나요?']}),
 item({intent:'SEARCH_CONTINUITY',audiences:['GENERAL','VISITOR'],patterns:[/그냥.*검색|검색하면|키워드\s*검색/],shortAnswer:'검색은 보통 한 번의 질문에서 장소를 찾는 데 강합니다. 지역 AI 컨시어지는 “펜션 근처 카페?” 다음의 “그 주변 볼 곳?”, “거긴 멀어?”, “비가 오는데?”를 같은 여행 맥락으로 이어갑니다. 각 질문을 고립된 검색어로 보지 않고 현재 장소와 일정 상태를 구조화해 유지하는 데 초점을 둡니다.',supportingConcepts:['conversational anchor','current-turn','TripSession'],allowedClaims:['구조화된 연속성'],relatedQuestions:['닫았다 다시 열어도 이어지나요?']}),
 item({intent:'DATA_ACCURACY',audiences:['GENERAL','VISITOR','BUSINESS','PUBLIC_SECTOR'],patterns:[/틀린\s*정보|정보.*틀리|오류|정확|책임/],shortAnswer:'오류가 전혀 없다고 약속하지는 않습니다. 외부 검색에서 발견한 정보는 곧바로 운영 사실로 쓰지 않고 미검증 후보로 구분합니다. Regional Copilot이 검토 과제를 만들고 지역 관리자가 중요한 사실을 확인한 뒤 VERIFIED/ACTIVE 지역 운영 데이터로 반영하는 구조입니다.',supportingConcepts:['search evidence','UNVERIFIED','Regional Copilot','RDM'],allowedClaims:['검토 절차','제로 오류 비보장'],relatedQuestions:['지역정보는 누가 관리하나요?']}),
 item({intent:'DATA_STEWARDSHIP',audiences:['GENERAL','BUSINESS','PUBLIC_SECTOR'],patterns:[/누가.*(?:관리|고치|검토)|지역정보.*관리|틀린.*누가/],shortAnswer:'Regional Copilot은 누락 장소, 오래된 정보, 좌표 부족과 미검증 후보를 찾아 검토 과제로 제안합니다. 중요한 운영 사실은 지역 관리자가 확인하고 승인합니다. Copilot proposes. Human decides.',supportingConcepts:['Regional Copilot','Regional Manager','Core Destination'],allowedClaims:['사람의 승인'],relatedQuestions:['업체가 직접 고칠 수 있나요?','지자체는 어떤 역할을 하나요?']}),
 item({intent:'PAID_RANKING',audiences:['GENERAL','BUSINESS','PUBLIC_SECTOR'],patterns:[/돈.*(?:업체|먼저|추천)|유료|광고|가입.*먼저|순위/],shortAnswer:'아니요. 현재 제품 원칙에서 결제 여부는 추천 순위를 정하는 기준이 아닙니다. Core Destination, 유료 참여 업체, 추천 순위는 서로 다른 개념이며 추천은 방문자 상황, 장소 유형 적합성, 검증된 운영 정보와 현재 조건을 기준으로 합니다. 미래의 미확정 상업 정책까지 약속하지는 않습니다.',supportingConcepts:['ranking principle','Core Destination','RDM'],allowedClaims:['현재 원칙만 설명'],relatedQuestions:['업체는 왜 참여해야 하나요?']}),
 item({intent:'BUSINESS_VALUE',audiences:['BUSINESS','GENERAL'],patterns:[/업체.*(?:도움|좋|참여|왜)|상인|사업자|가게.*참여/],shortAnswer:'업체는 상호·업종 같은 대표 정보와 운영 정보를 더 정확하게 표현하고, 방문자 상황에 실제로 맞을 때 발견될 기회를 얻을 수 있습니다. 지원되는 경우 전화·길찾기·예약 같은 행동 연결도 가능합니다. 참여나 결제가 매출 또는 노출 순위를 보장한다는 뜻은 아닙니다.',supportingConcepts:['canonical business identity','verified facts','actions'],allowedClaims:['잠재적 가치','보장 없음'],relatedQuestions:['정보 수정은 어떻게 하나요?','돈을 내면 먼저 나오나요?']}),
 item({intent:'MUNICIPALITY_VALUE',audiences:['PUBLIC_SECTOR','GENERAL'],patterns:[/지자체|공공|군청|시청|꼭.*해야|왜.*필요/],shortAnswer:'지자체 참여는 기술적으로 필수는 아니며 민간 또는 지역 운영으로도 시작할 수 있습니다. 다만 공공 관광·문화 데이터, 지역 범위 확장, 데이터 관리의 지속성과 공공 인프라 연계에 도움을 줄 수 있습니다. 역할은 지역 여건과 협력 방식에 따라 달라집니다.',supportingConcepts:['public data','regional stewardship','sustainability'],allowedClaims:['선택적 참여'],relatedQuestions:['민간 운영으로 시작할 수 있나요?']}),
 item({intent:'REGIONAL_SCALE',audiences:['GENERAL','PUBLIC_SECTOR'],patterns:[/합천.*(?:만|밖)|다른\s*지역|전국|확장|가조/],shortAnswer:'합천은 현장 검증 지역이고 가조는 같은 구조를 다른 지역에 재사용할 수 있는지 확인하는 지역입니다. 플랫폼은 공통 Regional Engine에 지역별 데이터, 의미 맥락과 관리 책임을 결합합니다. 아직 전국에서 운영 중이라고 말할 단계는 아니지만 별도 앱을 복제하지 않고 지역을 추가하는 구조를 검증하고 있습니다.',supportingConcepts:['Shared Regional Engine','isolated regions'],allowedClaims:['검증 단계','전국 운영 미주장'],relatedQuestions:['지역별 정보가 섞이지 않나요?']}),
 item({intent:'PRIVACY_LOCATION',audiences:['VISITOR','GENERAL'],patterns:[/내\s*위치|위치.*(?:사용|저장|권한)|개인정보|여행정보|닫았다.*열|다시\s*열/],shortAnswer:'위치는 브라우저에서 허용한 경우에만 가져오며, 거부하거나 사용할 수 없으면 그 상태로 동작합니다. 여행은 지역별 익명 TripSession으로 브라우저 localStorage에 저장되고, 저장 실패 시 같은 브라우저의 sessionStorage를 보조로 사용합니다. 여행 연속성을 위해 익명 ID와 개인정보를 줄인 여행 상태가 서버에 동기화될 수 있으며, 지역별 키로 분리됩니다. 자유 입력 원문은 TripSession 저장 과정에서 제거되지만 컨시어지 요청 처리용 서버 Runtime Context에는 입력 메시지가 저장되는 현재 구현이 있으므로 원문이 서버에 전혀 남지 않는다고 약속하지 않습니다.',supportingConcepts:['permissioned geolocation','TripSession','anonymous sync','regional isolation','Runtime Context'],allowedClaims:['실제 저장 경계 공개'],relatedQuestions:['새 여행을 시작하면 기존 여행은 어떻게 되나요?']}),
 item({intent:'PLATFORM_OVERVIEW',audiences:['GENERAL'],patterns:[/무슨\s*서비스|무엇.*서비스|왜.*필요|어떤.*서비스|소개/],shortAnswer:'지역 AI 컨시어지는 범용 AI를 지역의 검증된 운영 정보와 방문자의 현재 여행 상황에 연결하는 플랫폼입니다. Local Concierge는 방문자의 다음 행동을 돕고, Regional Copilot은 지역 관리자의 데이터 검토를 돕습니다. 이 Guide Copilot은 그 구조와 필요성을 일반 방문자·업체·공공 관계자에게 설명합니다.',supportingConcepts:['three surfaces','RDM','runtime context'],allowedClaims:['현재 구현 역할'],relatedQuestions:['ChatGPT와 무엇이 다른가요?','업체에는 어떤 도움이 되나요?']})
];
