import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{appendItineraryItem,currentAndNext,executionState,verifiedNavigation}from'./journeyExecution.ts';import{createTripSession,loadTripSession,saveTripSession}from'./tripSession.ts';
const mountain={entityId:'https://hapcheon.example/ontology#hwangmaesanCountyPark',regionId:'hapcheon',label:'황매산 군립공원',actions:{navigate:{latitude:35.495,longitude:127.974}}};
const memory=()=>{const data=new Map<string,string>();return{getItem:(key:string)=>data.get(key)||null,setItem:(key:string,value:string)=>void data.set(key,value)}};
test('adding an itinerary entity produces a planned next action without duplicates',()=>{const first=appendItineraryItem(createTripSession('hapcheon'),mountain);assert.equal(first.added,true);assert.equal((first.session.itinerary as any).steps[0].status,'PLANNED');const repeated=appendItineraryItem(first.session,mountain);assert.equal(repeated.added,false);assert.equal((repeated.session.itinerary as any).steps.length,1)});
test('verified actions enable navigation and missing coordinates never fabricate it',()=>{assert.deepEqual(verifiedNavigation(mountain),{name:'황매산 군립공원',latitude:35.495,longitude:127.974});assert.equal(verifiedNavigation({...mountain,actions:{}}),null);assert.equal(verifiedNavigation({...mountain,actions:{navigate:{}}}),null)});
test('composer order and the next itinerary item remain unchanged',()=>{const steps=['합천호','북어마을','로우풀','합천호 스마일펜션'].map((label,index)=>({entityId:`https://hapcheon.example/ontology#${index}`,label,status:'PLANNED',order:index+1}));assert.equal(currentAndNext(steps,steps[1].entityId).current.label,'북어마을');assert.equal(currentAndNext(steps,steps[1].entityId).next.label,'로우풀');assert.deepEqual(steps.map(x=>x.label),['합천호','북어마을','로우풀','합천호 스마일펜션'])});
test('regional persisted itinerary reopens safely without cross-region leakage',()=>{const storage=memory(),hapcheon=appendItineraryItem(createTripSession('hapcheon'),mountain).session;saveTripSession(executionState(hapcheon,mountain.entityId,'EN_ROUTE'),storage as any);saveTripSession(createTripSession('gajo'),storage as any);assert.equal((loadTripSession(storage as any,'hapcheon')!.itinerary as any).steps[0].regionId,'hapcheon');assert.equal(loadTripSession(storage as any,'gajo')!.itinerary,undefined)});
test('persistent continuity strips raw visitor language',()=>{let serialized='';saveTripSession({...createTripSession('hapcheon'),runtimeContext:{regionId:'hapcheon',rawMessage:'비밀 문장',weatherState:'RAIN'}},{setItem:(_key:string,value:string)=>{serialized=value}}as any);assert.doesNotMatch(serialized,/비밀 문장|rawMessage/);assert.match(serialized,/weatherState/)});
test('visitor execution UI keeps add, itinerary, nearby anchor and replan continuations reachable',()=>{const nearby=readFileSync(new URL('./pages/NearbyRestaurantsPage.tsx',import.meta.url),'utf8'),item=readFileSync(new URL('./components/RecommendationItineraryItem.tsx',import.meta.url),'utf8'),css=readFileSync(new URL('./index.css',import.meta.url),'utf8');for(const copy of ['다음으로 무엇을 할까요?','내 일정 보기','다른 곳 더 찾기'])assert.match(nearby,new RegExp(copy));assert.match(item,/anchor:\{entityId,label:name,latitude:destination\.latitude,longitude:destination\.longitude\}/);assert.match(item,/일정 변경/);assert.match(css,/@media\(max-width:430px\).*post-add-secondary/)});
