import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { installDismissalKey, installExperienceMode, installPlatform, isIosSafari, isStandalone, manifestHref } from './pwaInstall.ts';
const androidChrome='Mozilla/5.0 (Linux; Android 14; SM-S921N) AppleWebKit/537.36 Chrome/125.0 Mobile Safari/537.36';
const samsung='Mozilla/5.0 (Linux; Android 14; SAMSUNG SM-S921N) AppleWebKit/537.36 SamsungBrowser/25.0 Chrome/121.0 Mobile Safari/537.36';
const iosSafari='Mozilla/5.0 (iPhone) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1';
const mode=(platform:ReturnType<typeof installPlatform>,promptAvailable=false,overrides:Partial<{usefulResult:boolean;dismissed:boolean;standalone:boolean}>={})=>installExperienceMode({usefulResult:true,dismissed:false,standalone:false,platform,promptAvailable,...overrides});
test('each regional manifest preserves id, start URL, scope, icons and standalone display',()=>{for(const id of ['gajo','okcheon','muan','gyeryong','hapcheon','daejeon-junggu'] as const){assert.equal(manifestHref(id),`/manifest-${id}.webmanifest`);const manifest=JSON.parse(readFileSync(new URL(`../public/manifest-${id}.webmanifest`,import.meta.url),'utf8'));assert.equal(manifest.id,`/${id}`);assert.equal(manifest.start_url,`/${id}`);assert.equal(manifest.scope,`/${id}`);assert.equal(manifest.display,'standalone');assert.deepEqual(manifest.icons.map((icon:{sizes:string})=>icon.sizes),['192x192','512x512'])}});
test('Android uses native install when beforeinstallprompt is available',()=>assert.equal(mode(installPlatform(androidChrome),true),'native'));
test('Android retains a manual install experience without beforeinstallprompt',()=>assert.equal(mode(installPlatform(androidChrome)),'android-guide'));
test('Samsung Internet receives the Android manual fallback',()=>{assert.equal(installPlatform(samsung),'samsung-internet');assert.equal(mode(installPlatform(samsung)),'android-guide')});
test('iOS Safari behavior remains manual and excludes iOS Chromium',()=>{assert.equal(isIosSafari(iosSafari,'Apple Computer, Inc.'),true);assert.equal(mode(installPlatform(iosSafari,'Apple Computer, Inc.')),'ios-guide');assert.equal(isIosSafari('Mozilla/5.0 (iPhone) AppleWebKit/605.1.15 CriOS/120 Mobile/15E148 Safari/604.1','Apple Computer, Inc.'),false)});
test('standalone supports display mode and iOS flag',()=>{assert.equal(isStandalone({matchMedia:()=>({matches:true}) as MediaQueryList} as Window,{} as Navigator),true);assert.equal(isStandalone({matchMedia:()=>({matches:false}) as MediaQueryList} as Window,{standalone:true} as Navigator),true)});
test('standalone and dismissed states remain hidden',()=>{assert.equal(mode('android-browser',true,{standalone:true}),'hidden');assert.equal(mode('android-browser',true,{dismissed:true}),'hidden')});
test('dismissal is region scoped',()=>assert.notEqual(installDismissalKey('hapcheon'),installDismissalKey('gajo')));
test('install experience is hidden before a useful result and uses return-visit public copy',()=>{assert.equal(mode('android-browser',true,{usefulResult:false}),'hidden');const component=readFileSync(new URL('./components/InstallExperience.tsx',import.meta.url),'utf8');assert.match(component,/다음에도 쉽게 이용하기/);assert.match(component,/QR을 다시 찾지 않고/);assert.match(component,/sessionStorage\.setItem\(key,'1'\)/)});
