import type { CreateContextInput } from './api/client';
export type QuickIntentId='place-now'|'food-now'|'two-hour-course'|'senior-comfort'|'rainy-day'|'events-today'|'nearby'|'free-talk';
export interface QuickIntent{id:QuickIntentId;title:string;description:string;destination:'/concierge'|'/nearby-discovery';preset?:'senior'|'family-healing'|'indoor'|'nearby';context:CreateContextInput}
export const REGION_INTEREST_OPTIONS=[{id:'REST_AND_RECOVERY',label:'편안한 휴식'},{id:'HOT_SPRING',label:'온천'},{id:'FOOD',label:'맛집'},{id:'CAFE',label:'카페'},{id:'NATURE',label:'자연·산책'},{id:'INDOOR',label:'실내 활동'},{id:'ACTIVITY',label:'체험'}];
export const REGION_PLACE_SUGGESTIONS=[{id:'https://gajo-wellness.kr/ontology#antiAgingHealingLand',label:'거창 항노화힐링랜드',aliases:['항노화힐링랜드']},{id:'https://gajo-wellness.kr/ontology#gajoHotSpringComplex',label:'백두산천지온천',aliases:['가조온천']},{id:'https://gajo-wellness.kr/ontology#localFoodRestaurant',label:'미가추어탕',aliases:[]},{id:'https://gajo-wellness.kr/ontology#wellnessLounge',label:'다온 카페',aliases:[]}];
export interface RegionConfig{id:string;regionName:string;serviceName:string;heroCopy:string;accent:string;center:{latitude:number;longitude:number};bounds:{north:number;south:number;east:number;west:number};quickIntents:QuickIntent[];supportedCategories:string[];serviceAreaMessage:string;ontologyNamespace:string;dataSources:Record<string,string>}
export const GAJO_CONFIG:RegionConfig={id:'gajo',regionName:'가조',serviceName:'가조 여행 동행',heroCopy:'계획할 때부터 여행 중인 지금까지, 필요한 다음 일정을 이어드려요.',accent:'#0b675f',center:{latitude:35.714,longitude:127.918},bounds:{north:35.84,south:35.58,east:128.05,west:127.78},quickIntents:[
{id:'place-now',title:'지금 어디 갈까요?',description:'현재 시간에 갈 수 있는 곳',destination:'/concierge',context:{inputMode:'STRUCTURED'}},{id:'food-now',title:'오늘 뭐 먹을까요?',description:'주변에서 지금 이용하기 좋은 곳',destination:'/nearby-discovery',context:{inputMode:'STRUCTURED'}},{id:'two-hour-course',title:'2~3시간 코스',description:'남은 시간에 맞춰 일정 만들기',destination:'/concierge',context:{inputMode:'STRUCTURED'}},{id:'senior-comfort',title:'부모님과 편하게',description:'걷기 부담이 적은 일정',destination:'/concierge',preset:'senior',context:{inputMode:'STRUCTURED'}},{id:'rainy-day',title:'비 오는 날',description:'날씨에 맞는 실내·대안 일정',destination:'/concierge',preset:'indoor',context:{inputMode:'STRUCTURED',activityPreferences:['INDOOR']}},{id:'events-today',title:'오늘 행사',description:'지금 참여할 수 있는 행사',destination:'/concierge',context:{inputMode:'STRUCTURED',activityPreferences:['EVENTS']}},{id:'nearby',title:'내 주변',description:'현재 위치에서 가까운 곳',destination:'/nearby-discovery',preset:'nearby',context:{inputMode:'STRUCTURED'}},{id:'free-talk',title:'그냥 말할게요',description:'상황을 편하게 이야기하기',destination:'/concierge',context:{inputMode:'STRUCTURED'}}],supportedCategories:['FOOD','CAFE','LODGING','HOT_SPRING_WELLNESS','ACTIVITY','TOURISM_NATURE','EVENTS'],serviceAreaMessage:'현재는 가조 지역을 중심으로 안내하고 있어요. 가조에서 즐길 수 있는 장소를 찾아드릴까요?',ontologyNamespace:'https://gajo.example/ontology#',dataSources:{masterData:'regional-master-data',nearby:'KAKAO_LOCAL',weather:'OPEN_METEO'}};
export const REGION_CONFIG=GAJO_CONFIG;
const campaigns:Record<string,QuickIntentId>={'next-place':'place-now','food-now':'food-now','rainy-day':'rainy-day','two-hour-course':'two-hour-course','events-today':'events-today'};
export function resolveEntry(search:string){const p=new URLSearchParams(search);const id=campaigns[p.get('intent')||''];return{entrySource:p.get('entry')||'direct',intent:id?REGION_CONFIG.quickIntents.find(i=>i.id===id):undefined}}
export const entryCopy:Record<string,string>={restaurant:'식사 후 어디 갈까요?',pension:'내일 오전 일정 만들기',parking:'주차 후 가까운 곳부터 보기',festival:'오늘 행사와 주변 즐길거리',attraction:'관람 후 다음 일정 찾기'};
