import test from'node:test';import assert from'node:assert/strict';import{appSurface,isExkoviaHost,isPlatformPreview,regionFromLocation,regionalPath,shouldRegisterVisitorPwa}from'./regionRouting.ts';test('canonical Okcheon routes retain region',()=>{assert.equal(regionalPath('/concierge?mode=plan','okcheon'),'/okcheon/concierge?mode=plan');assert.equal(regionalPath('/concierge?mode=now','okcheon'),'/okcheon/concierge?mode=now');assert.equal(regionFromLocation('/okcheon/concierge','?mode=plan'),'okcheon')});test('legacy direct concierge remains compatible',()=>{assert.equal(regionFromLocation('/concierge',''),'gajo');assert.equal(regionFromLocation('/concierge','?region=okcheon'),'okcheon');assert.equal(regionalPath('/concierge','gajo'),'/concierge')});
test('canonical Muan routes preserve the active region',()=>{for(const path of ['/concierge?mode=plan','/concierge?mode=now','/itinerary','/nearby-discovery','/map','/admin'])assert.equal(regionalPath(path,'muan'),`/muan${path}`);assert.equal(regionFromLocation('/muan/concierge','?mode=plan'),'muan')});
test('canonical Gyeryong routes preserve the active region',()=>{for(const path of ['/concierge?mode=plan','/concierge?mode=now','/itinerary','/nearby-discovery','/map','/admin'])assert.equal(regionalPath(path,'gyeryong'),`/gyeryong${path}`);assert.equal(regionFromLocation('/gyeryong/concierge','?mode=plan'),'gyeryong')});
test('canonical Hapcheon routes preserve the active region',()=>{for(const path of ['/concierge?mode=plan','/concierge?mode=now','/itinerary','/nearby-discovery','/map','/admin'])assert.equal(regionalPath(path,'hapcheon'),`/hapcheon${path}`);assert.equal(regionFromLocation('/hapcheon/concierge','?mode=plan'),'hapcheon')});
test('production gajo.odex.kr/hapcheon resolves Hapcheon from the path',()=>assert.equal(regionFromLocation('/hapcheon','','gajo.odex.kr'),'hapcheon'));
test('legacy Hapcheon PWA root resolves explicitly from its production hostname',()=>{assert.equal(regionFromLocation('/','','hapcheon.odex.kr'),'hapcheon');assert.equal(regionFromLocation('/','', 'gajo.odex.kr'),'gajo');assert.equal(regionFromLocation('/','', 'okcheon.odex.kr'),'okcheon');assert.equal(regionFromLocation('/okcheon','', 'hapcheon.odex.kr'),'okcheon');assert.equal(regionFromLocation('/','?region=gajo','hapcheon.odex.kr'),'gajo')});
test('canonical Daejeon Jung-gu routes preserve the district region',()=>{for(const path of ['/concierge?mode=plan','/concierge?mode=now','/itinerary','/nearby-discovery','/map','/admin'])assert.equal(regionalPath(path,'daejeon-junggu'),`/daejeon-junggu${path}`);assert.equal(regionFromLocation('/daejeon-junggu/concierge','?mode=plan'),'daejeon-junggu')});
test('hostname classification is explicit and case normalized',()=>{for(const host of['exkovia.com','www.exkovia.com','EXKOVIA.COM','WWW.ExKoViA.CoM']){assert.equal(isExkoviaHost(host),true);assert.equal(appSurface('/','',host),'PLATFORM')}assert.equal(isPlatformPreview('localhost','?platform=exkovia'),true);assert.equal(appSurface('/','','localhost'),'REGION');assert.equal(regionFromLocation('/','','gajo.odex.kr'),'gajo');for(const host of['copilot.odex.kr','guide.odex.kr','unknown.example']){assert.equal(regionFromLocation('/','',host),undefined);assert.equal(appSurface('/','',host),'UNSUPPORTED')}});
test('PWA registration is regional only',()=>{assert.equal(shouldRegisterVisitorPwa('/hapcheon','','exkovia.com'),true);assert.equal(shouldRegisterVisitorPwa('/','','exkovia.com'),false);assert.equal(shouldRegisterVisitorPwa('/go/smile','','exkovia.com'),false);assert.equal(shouldRegisterVisitorPwa('/','','unknown.example'),false)});
