import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {appSurface,shouldRegisterVisitorPwa} from './regionRouting.ts';

const root=new URL('../',import.meta.url),read=(name:string)=>readFileSync(new URL(name,root),'utf8');
const exkovia=read('exkovia.html'),gajo=read('index.html'),nginx=read('nginx.conf'),css=read('src/platform.css');
const main=read('src/main.tsx');
const meta=(html:string,key:string)=>html.match(new RegExp(`<meta[^>]+(?:name|property)=["']${key}["'][^>]+content=["']([^"']+)`))?.[1];
test('EXKOVIA root emits its exact social title, description and versioned portal image',()=>{const title='찾아오는 여행도우미 | 필요한 순간, 먼저 찾아갑니다',description='여행자의 상황을 이해하고, 필요한 순간 먼저 찾아오는 AI 여행도우미입니다.',image='https://exkovia.com/branding/travel-helper-social-1200x630-v2.png';assert.match(exkovia,new RegExp(`<title>${title.replace('|','\\|')}<\\/title>`));for(const key of['og:title','twitter:title'])assert.equal(meta(exkovia,key),title);for(const key of['description','og:description','twitter:description'])assert.equal(meta(exkovia,key),description);for(const key of['og:type','og:site_name','og:locale','og:url','og:image','og:image:width','og:image:height','og:image:type','twitter:card','twitter:image'])assert.ok(meta(exkovia,key),key);assert.equal(meta(exkovia,'og:site_name'),'찾아오는 여행도우미');assert.equal(meta(exkovia,'og:image'),image);assert.equal(meta(exkovia,'twitter:image'),image);assert.equal(meta(exkovia,'og:image:alt'),'찾아오는 여행도우미 — 필요한 순간, 먼저 찾아갑니다');assert.match(exkovia,/rel="canonical" href="https:\/\/exkovia\.com\/"/);assert.doesNotMatch(exkovia,/exkovia-social-1200x630\.png|가조 AI 컨시어지|manifest-gajo|gajo-ai/)});
test('Gajo initial HTML uses public travel language while retaining favicon and runtime manifest policy',()=>{assert.match(gajo,/<title>가조 AI 여행안내<\/title>/);assert.match(gajo,/지역 AI 여행안내/);assert.match(gajo,/href="\/favicon\.svg"/);assert.match(gajo,/manifest-\$\{active\}\.webmanifest/)});
test('EXKOVIA platform HTML starts without a regional manifest while Hapcheon runtime can add its own',()=>{assert.doesNotMatch(exkovia,/rel="manifest"/);assert.match(main,/regionalManifest\.rel=['"]manifest['"]/);assert.match(main,/regionalManifest\.href=manifestHref\(bootRegion\.id\)/)});
test('Nginx serves the EXKOVIA root and existing service paths from their original entries',()=>{for(const host of['exkovia.com','www.exkovia.com'])assert.match(nginx,new RegExp(`${host.replaceAll('.','\\.')} /exkovia\\.html`));assert.doesNotMatch(nginx,/hapcheon\.html/);assert.match(nginx,/default \/unsupported\.html/);assert.match(nginx,/gajo\.odex\.kr \/index\.html/);assert.match(nginx,/hapcheon\.odex\.kr \/index\.html/);assert.match(nginx,/copilot\.odex\.kr \/copilot\.html/);assert.match(nginx,/guide\.odex\.kr \/guide\.html/);assert.match(nginx,/location = \/ \{\s*rewrite \^ \$spa_entry last/);assert.match(nginx,/try_files \$uri \$uri\/ \$spa_entry/);for(const entry of['exkovia','unsupported','copilot','guide'])assert.match(nginx,new RegExp(`location = /${entry}\\.html \\{\\s*internal`));assert.match(nginx,/if \(\$spa_entry != \/index\.html\) \{ return 404; \}/);assert.match(nginx,/location \^~ \/api\/[^]*proxy_pass \$api_upstream\$request_uri/)});
test('Nginx never converts missing static assets or branding files into SPA HTML',()=>{for(const prefix of['assets','branding'])assert.match(nginx,new RegExp(`location \\^~ /${prefix}/ \\{\\s*try_files \\$uri =404;`));assert.match(nginx,/location = \/favicon\.svg \{\s*try_files \$uri =404;/)});
test('unknown hosts cannot reach platform region or QR surfaces',()=>{for(const path of['/','/partner/apply','/region/apply','/hapcheon','/hapcheon/concierge','/go/example','/visit/example'])assert.equal(appSurface(path,'?platform=exkovia','unknown.example'),'UNSUPPORTED')});
test('Korean platform headings use keep-all without removing responsive overflow guards',()=>{assert.match(css,/platform-hero h1[^]*word-break:\s*keep-all/);assert.match(css,/platform-entrances h2[^]*word-break:\s*keep-all/);assert.match(css,/platform-cta[^]*word-break:\s*keep-all/);assert.match(css,/overflow-x:\s*hidden/);assert.match(css,/@media \(max-width: 430px\)/)});
test('social image is a real versioned 1200 by 630 PNG and icons exist',()=>{const image=new URL('public/branding/travel-helper-social-1200x630-v2.png',root),data=readFileSync(image);assert.equal(data.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(data.readUInt32BE(16),1200);assert.equal(data.readUInt32BE(20),630);for(const name of['public/branding/exkovia-favicon.svg','public/branding/exkovia-mark.svg','public/branding/exkovia-icon-192.png','public/branding/exkovia-icon-512.png'])assert.equal(existsSync(new URL(name,root)),true,name)});
test('regional report keeps noindex on common and canonical SPA responses without leaking it to other locations',()=>{const locations=[...nginx.matchAll(/location\s+([^{]+){([^}]*)}/g)].map(([,selector,body])=>({selector:selector.trim(),body})),report=locations.find(x=>x.selector.includes('regional-report|(?!(?:api|assets|branding)'));assert.ok(report);assert.match(report.selector,/\^\/\(\?:regional-report\|\(\?!\(\?:api\|assets\|branding\)\(\?:\/\|\$\)\)\[a-z0-9-\]\+\/regional-report\)\/\?\$/);const reportPattern=new RegExp(report.selector.replace(/^~\s+/,''));for(const path of['/regional-report','/regional-report/','/hapcheon/regional-report','/hapcheon/regional-report/','/okcheon/regional-report','/gajo/regional-report','/unsupported-region/regional-report'])assert.equal(reportPattern.test(path),true,path);for(const path of['/api/regional-report','/api/regional-report/summary','/api/regional-report?period=7d','/api/analytics/summary','/api/partners/example','/assets/regional-report','/hapcheon','/okcheon','/gajo','/assets/example.js'])assert.equal(reportPattern.test(path.split('?')[0]),false,path);assert.match(report.body,/add_header Cache-Control "no-cache"/);assert.match(report.body,/add_header X-Robots-Tag "noindex, nofollow" always/);assert.match(report.body,/rewrite \^ \$spa_entry break/);assert.doesNotMatch(report.body,/try_files|\blast\s*;/);assert.equal((nginx.match(/X-Robots-Tag/g)||[]).length,1);for(const location of locations.filter(x=>x!==report))assert.doesNotMatch(location.body,/X-Robots-Tag/);assert.match(gajo,/platformPaths = \[[^\]]*'\/regional-report'/);assert.match(gajo,/\[\^\/\]\+\\\/regional-report/);for(const host of['exkovia.com','gajo.odex.kr','localhost'])for(const path of['/regional-report','/regional-report/','/hapcheon/regional-report','/hapcheon/regional-report/','/okcheon/regional-report','/gajo/regional-report'])assert.equal(shouldRegisterVisitorPwa(path,'',host),false)});
