import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {appSurface} from './regionRouting.ts';

const root=new URL('../',import.meta.url),read=(name:string)=>readFileSync(new URL(name,root),'utf8');
const exkovia=read('exkovia.html'),gajo=read('index.html'),nginx=read('nginx.conf'),css=read('src/platform.css');
const main=read('src/main.tsx');
const meta=(html:string,key:string)=>html.match(new RegExp(`<meta[^>]+(?:name|property)=["']${key}["'][^>]+content=["']([^"']+)`))?.[1];
test('EXKOVIA initial HTML owns complete crawler metadata without Gajo branding',()=>{assert.match(exkovia,/<title>EXKOVIA \| 지역과 여행자를 잇는 AI 관광 플랫폼<\/title>/);assert.equal(meta(exkovia,'description'),'여행자, 지역 업소, 지자체를 연결하는 지역형 AI 관광 플랫폼입니다.');for(const key of['og:type','og:site_name','og:locale','og:title','og:description','og:url','og:image','og:image:width','og:image:height','og:image:type','twitter:card','twitter:title','twitter:description','twitter:image'])assert.ok(meta(exkovia,key),key);assert.match(exkovia,/rel="canonical" href="https:\/\/exkovia\.com\/"/);assert.doesNotMatch(exkovia,/가조 AI 컨시어지|manifest-gajo|gajo-ai/)});
test('Gajo initial HTML retains its existing title description favicon and runtime manifest policy',()=>{assert.match(gajo,/<title>가조 AI 컨시어지<\/title>/);assert.match(gajo,/거창 가조 온천단지/);assert.match(gajo,/href="\/favicon\.svg"/);assert.match(gajo,/manifest-\$\{active\}\.webmanifest/)});
test('EXKOVIA platform HTML starts without a regional manifest while Hapcheon runtime can add its own',()=>{assert.doesNotMatch(exkovia,/rel="manifest"/);assert.match(main,/regionalManifest\.rel=['"]manifest['"]/);assert.match(main,/regionalManifest\.href=manifestHref\(bootRegion\.id\)/)});
test('Nginx selects immutable hostname-specific SPA entries and preserves API proxy',()=>{for(const host of['exkovia.com','www.exkovia.com'])assert.match(nginx,new RegExp(`${host.replaceAll('.','\\.')} /exkovia\\.html`));assert.match(nginx,/default \/unsupported\.html/);assert.match(nginx,/gajo\.odex\.kr \/index\.html/);assert.match(nginx,/copilot\.odex\.kr \/copilot\.html/);assert.match(nginx,/guide\.odex\.kr \/guide\.html/);assert.match(nginx,/location = \/ \{\s*rewrite \^ \$spa_entry last/);assert.match(nginx,/try_files \$uri \$uri\/ \$spa_entry/);for(const entry of['exkovia','unsupported','copilot','guide'])assert.match(nginx,new RegExp(`location = /${entry}\\.html \\{\\s*internal`));assert.match(nginx,/if \(\$spa_entry != \/index\.html\) \{ return 404; \}/);assert.match(nginx,/location \/api\/[^]*proxy_pass \$api_upstream\$request_uri/)});
test('Nginx never converts missing static assets or branding files into SPA HTML',()=>{for(const prefix of['assets','branding'])assert.match(nginx,new RegExp(`location \\^~ /${prefix}/ \\{\\s*try_files \\$uri =404;`));assert.match(nginx,/location = \/favicon\.svg \{\s*try_files \$uri =404;/)});
test('unknown hosts cannot reach platform region or QR surfaces',()=>{for(const path of['/','/partner/apply','/region/apply','/hapcheon','/hapcheon/concierge','/go/example','/visit/example'])assert.equal(appSurface(path,'?platform=exkovia','unknown.example'),'UNSUPPORTED')});
test('Korean platform headings use keep-all without removing responsive overflow guards',()=>{assert.match(css,/platform-hero h1[^]*word-break:\s*keep-all/);assert.match(css,/platform-entrances h2[^]*word-break:\s*keep-all/);assert.match(css,/platform-cta[^]*word-break:\s*keep-all/);assert.match(css,/overflow-x:\s*hidden/);assert.match(css,/@media \(max-width: 430px\)/)});
test('social image is a real 1200 by 630 PNG and icons exist',()=>{const image=new URL('public/branding/exkovia-social-1200x630.png',root),data=readFileSync(image);assert.equal(data.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(data.readUInt32BE(16),1200);assert.equal(data.readUInt32BE(20),630);for(const name of['public/branding/exkovia-favicon.svg','public/branding/exkovia-mark.svg','public/branding/exkovia-icon-192.png','public/branding/exkovia-icon-512.png'])assert.equal(existsSync(new URL(name,root)),true,name)});
