import type{CreateContextInput}from'./api/client';
export interface PlannedPlace{label:string;entityId?:string;resolved:boolean}
export interface PlannedContext{duration?:'DAY'|'1N2D'|'2N3D'|'CUSTOM';startDate?:string;arrivalPeriod?:string;departurePeriod?:string;companions?:CreateContextInput['companions'];mobilityConstraints?:string[];walkingLevel?:CreateContextInput['walkingLevel'];transportMode?:CreateContextInput['transportMode'];interests?:string[];mustVisitPlaces?:PlannedPlace[]}
export interface TripSession{id:string;regionId:string;mode:'PLAN'|'NOW';plannedContext?:PlannedContext;runtimeContext?:any;itinerary?:unknown;createdAt:string;updatedAt:string}
const KEY='regional-concierge-trip-session-v1';
export function createTripSession(regionId='gajo',now=new Date()):TripSession{const iso=now.toISOString();return{id:crypto.randomUUID(),regionId,mode:'NOW',createdAt:iso,updatedAt:iso}}
export function loadTripSession(storage:Pick<Storage,'getItem'|'setItem'>=sessionStorage):TripSession|undefined{try{const value=storage.getItem(KEY);return value?JSON.parse(value):undefined}catch{return undefined}}
export function saveTripSession(session:TripSession,storage:Pick<Storage,'setItem'>=sessionStorage){const next={...session,updatedAt:new Date().toISOString()};storage.setItem(KEY,JSON.stringify(next));return next}
export function ensureTripSession(regionId='gajo',storage:Pick<Storage,'getItem'|'setItem'>=sessionStorage){return loadTripSession(storage)||saveTripSession(createTripSession(regionId),storage)}
export function sessionContext(s:TripSession):CreateContextInput{const p=s.plannedContext||{};return{companions:p.companions,companionConstraints:p.mobilityConstraints,walkingLevel:p.walkingLevel,transportMode:p.transportMode,activityPreferences:p.interests}}
export function mergeTravelContext(carried:CreateContextInput,explicit:CreateContextInput):CreateContextInput{return{...carried,...explicit,companions:explicit.companions??carried.companions,companionConstraints:explicit.companionConstraints??carried.companionConstraints,activityPreferences:explicit.activityPreferences??carried.activityPreferences}}
export function resolveMustVisit(value:string,suggestions:Array<{id:string;label:string;aliases?:string[]}>):PlannedPlace|undefined{const label=value.trim();if(!label)return undefined;const normalized=label.replace(/\s/g,'').toLowerCase();const match=suggestions.find(p=>[p.label,...(p.aliases||[])].some(v=>v.replace(/\s/g,'').toLowerCase()===normalized));return match?{label:match.label,entityId:match.id,resolved:true}:{label,resolved:false}}
export function currentTravelContext(planned:CreateContextInput,runtime:CreateContextInput,explicit:CreateContextInput):CreateContextInput{return mergeTravelContext(mergeTravelContext(planned,runtime),explicit)}
