export const VISITOR_FLOW_COPY = {
  preservedStops: {ko:'개 일정은 그대로 보존됩니다.',en:'stops will be preserved.'},
  graphEvidenceDescription: {ko:'아래는 온톨로지 그래프에서 실제로 추적된 RDF 트리플입니다. 이 서비스의 모든 추천은 프롬프트 규칙이 아닌 그래프 순회(graph traversal)를 통해 도출됩니다.',en:'These RDF triples show the graph evidence used to produce the recommendation.'},
  dayNumber: {ko:'{day}일차',en:'Day {day}'},
  savedTripOrder: {ko:'저장한 여행 일정을 순서대로 보여드려요.',en:'Your saved itinerary, in visit order.'},
  travelPlan: {ko:'이동 계획',en:'Travel Plan'},
  travelPlanUnavailable: {ko:'검증된 실제 장소 이동 계획을 현재 불러올 수 없습니다.',en:'A verified travel plan is currently unavailable.'},
  changeSchedule: {ko:'일정 변경',en:'Change Itinerary'},
  locationPurpose: {ko:'현재 위치를 사용하면 가까운 장소와 이동 부담을 고려한 일정을 추천할 수 있습니다. 위치는 브라우저 세션에서만 사용합니다.',en:'Use your location to find nearby places and plan manageable journeys. Your location is used only for this browser session.'},
  useCurrentPosition: {ko:'현재 위치 사용',en:'Use Current Location'},
  loadingVerifiedPlaces: {ko:'검증된 실제 장소를 불러오는 중입니다.',en:'Loading verified places…'},
  addedByReplan: {ko:'새 일정에 추가됨',en:'Added to Revised Itinerary'},
  recommendElsewhere: {ko:'다른 곳 추천받기',en:'Find Other Places'},
  seeOtherRestaurants: {ko:'다른 식당 보기',en:'See Other Restaurants'},
  demoRain: {ko:'데모: 13시 강한 비 발생',en:'Demo: Heavy Rain at 13:00'},
  planned: {ko:'예정',en:'Planned'},
  localPlace: {ko:'지역 장소',en:'Local Place'},
  markVisited: {ko:'방문 완료',en:'Mark as Visited'},
  travelInput: {ko:'여행 조건 입력',en:'Your Travel Request'},
  requestPlaceholder: {ko:'필요한 내용을 입력하세요',en:'Tell us what you need'},
  speakOrTypeStatus: {ko:'말하거나 글자로 입력할 수 있어요.',en:'You can speak or type your request.'},
  newAnswer: {ko:'새 AI 여행 답변',en:'New AI Travel Response'},
  understood: {ko:'이렇게 이해했어요',en:'What We Understood'},
  understoodTrip: {ko:'말씀하신 방문 상황을 바탕으로 일정을 구성했습니다.',en:'We planned this itinerary around your travel request.'},
  curatedCourse: {ko:'선별한 여행 코스',en:'Selected Stops'},
  answerActions: {ko:'이 답변에서 바로 하기',en:'Actions for This Response'},
  address: {ko:'주소',en:'Address'},
  nearbyNavigation:{ko:'주변 찾기',en:'Nearby'},
  tripCount: {ko:'내 여행 {count}건',en:'My Trip: {count} saved'},
  fromCurrent: {ko:'현재 위치에서',en:'From your current location'},
  externalKnowledge: {ko:'외부 지역지식 서비스',en:'External Regional Knowledge'},
  exploreDeep: {ko:'을 더 깊이 알아보기',en:' — Explore in Depth'},
  exploreKnowledge: {ko:'군의 관광지·역사·문화·자연과 주변 자원의 관계를 EXKO 지역지식에서 살펴보세요.',en:' — Explore local attractions, history, culture, nature and nearby places on EXKO.'},
  exkoPrefix: {ko:'EXKO에서',en:'Explore on EXKO:'},
  exkoSuffix: {ko:'군 살펴보기',en:' — Regional Guide'},
  exkoCompact: {ko:'군 지역지식 보기',en:' — Regional Knowledge'},
  parking: {ko:'주차',en:'Parking'},
  weatherPending: {ko:'날씨 정보 확인 전',en:'Weather not checked'},
  weatherUnknown: {ko:'날씨 정보 없음',en:'Weather unavailable'},
  weatherLive: {ko:'실시간 날씨 확인됨',en:'Current weather checked'},
  weatherRecent: {ko:'최근 확인한 날씨 정보',en:'Recently checked weather'},
  checking: {ko:'확인 중…',en:'Checking…'},
  clearWeather: {ko:'맑음',en:'Clear'}, cloudyWeather: {ko:'흐림',en:'Cloudy'},
  rainWeather: {ko:'비',en:'Rain'}, lightRain: {ko:'약한 비',en:'Light rain'}, heavyRain: {ko:'강한 비',en:'Heavy rain'},
  thunderstorm: {ko:'뇌우',en:'Thunderstorm'}, snow: {ko:'눈',en:'Snow'},
  alreadySavedStay: {ko:'이미 내 여행에 저장된 숙소입니다.',en:'This accommodation is already saved in My Trip.'},
  alreadyAdded: {ko:'이미 내 여행에 담겨 있습니다.',en:'Already saved in My Trip.'},
  viewFullTrip: {ko:'내 여행 전체 보기',en:'View My Trip'},
  depart: {ko:'출발하기',en:'Start Directions'},
  continueSearching: {ko:'계속 장소 찾기',en:'Find More Places'},
  invalidStay: {ko:'이 숙소의 정보를 확인할 수 없어 저장하지 못했습니다. 다른 숙소를 선택해 주세요.',en:'This accommodation could not be verified. Please choose another place.'},
  saveStayFailed: {ko:'숙소를 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.',en:'Could not save accommodation. Please try again shortly.'},
  saveTripFailed: {ko:'내 여행에 담지 못했습니다. 다시 시도해 주세요.',en:'Could not save to My Trip. Please try again.'},
  tourismDescription: {ko:'볼거리와 현장 경험',en:'Sights and local experiences'},
  foodDescription: {ko:'식사와 카페',en:'Restaurants and cafés'},
  stayDescription: {ko:'머물 곳 찾기',en:'Places to stay'},
  essentialDescription: {ko:'여행 중 필요한 곳',en:'Useful places on your trip'},
  categoryTabs: {ko:'주변 찾기 대분류',en:'Nearby categories'},
  locationHelp: {ko:'현재 위치를 확인하면 주변 장소와 이동 정보를 더 정확하게 안내해드릴 수 있습니다.',en:'Confirm your location for more accurate nearby places and travel information.'},
  staleLocation: {ko:'마지막으로 확인한 위치가 오래됐어요. 현재 위치를 다시 확인할까요?',en:'Your saved location is out of date. Would you like to check it again?'},
  previousLocation: {ko:'이전 확인 위치:',en:'Previous location:'},
  locationDenied: {ko:'위치 권한이 거부되었습니다. 다른 장소를 기준으로 계속할 수 있어요.',en:'Location access was denied. You can continue by choosing another place.'},
  locationTimeout: {ko:'위치 확인 시간이 초과되었습니다. 다른 장소를 기준으로 계속할 수 있어요.',en:'Location lookup timed out. You can continue by choosing another place.'},
  locationUnavailable: {ko:'현재 위치를 사용할 수 없습니다. 다른 장소를 기준으로 계속할 수 있어요.',en:'Your location is unavailable. You can continue by choosing another place.'},
  locationImprecise: {ko:'위치 정확도가 부족합니다. 다른 장소를 기준으로 찾아보세요.',en:'Your location is not accurate enough. Please choose another starting place.'},
  anchorsFailed: {ko:'대표 장소를 불러오지 못했습니다. 장소명을 검색해 주세요.',en:'Landmarks could not be loaded. Please search by place name.'},
  searchEmpty: {ko:'확인된 장소가 없습니다. 더 구체적인 주소나 장소명을 입력해 주세요.',en:'No places were found. Enter a more specific address or place name.'},
  searchFailed: {ko:'장소 검색이 원활하지 않습니다. 잠시 후 다시 시도해 주세요.',en:'Place search is unavailable. Please try again shortly.'},
  currentFound: {ko:'현재 위치 주변에서 찾았습니다.',en:'Showing places near your current location.'},
  locationRefreshed: {ko:'현재 위치 기준으로 다시 찾았습니다.',en:'Results refreshed for your current location.'},
  locationChanged: {ko:'현재 위치가 달라졌어요. 이곳을 기준으로 다시 찾아볼까요?',en:'Your location has changed. Search from here?'},
  recheckLocation: {ko:'현재 위치 다시 확인',en:'Check Current Location Again'},
  startCurrent: {ko:'현재 위치에서 시작',en:'Start from Current Location'},
  tripStart: {ko:'여행 시작 위치',en:'Trip Starting Point'},
  tripStartQuestion: {ko:'어디에서 여행을 시작할까요?',en:'Where would you like to start your trip?'},
  outsideRegion: {ko:'현재 위치는 지원 지역 밖으로 확인됩니다.',en:'Your current location is outside the supported area.'},
  searchCoordinates: {ko:'좌표를 기준으로 주변 장소를 찾아드립니다.',en:'We will use your coordinates to find nearby places.'},
  nearBoundary: {ko:'지역 경계와 가까울 수 있어요.',en:'You may be near the regional boundary.'},
  addressAndCoordinates: {ko:'주소와 현재 좌표를 함께 기준으로 주변 장소를 찾습니다.',en:'We use your address and coordinates to find nearby places.'},
  replanQuestion: {ko:'다음 장소와 이동 방향이 달라 남은 일정을 확인해 볼까요?',en:'Your next stop is in a different direction. Review the rest of your trip?'},
  replanNotice: {ko:'위치 변경은 주변검색 기준에 바로 반영했습니다. 기존 일정은 아직 변경하지 않았습니다.',en:'Nearby search now uses your new location. Your itinerary has not changed.'},
  accuracyHigh: {ko:'위치 정확도 좋음',en:'High location accuracy'},
  accuracyMedium: {ko:'위치 정확도 보통',en:'Moderate location accuracy'},
  accuracyLow: {ko:'위치 정확도 낮음',en:'Low location accuracy'},
  accuracyUnknown: {ko:'위치 정확도 확인 필요',en:'Location accuracy unavailable'},
  lastChecked: {ko:'마지막 확인',en:'Last checked'},
  checkedAt: {ko:'확인 시각',en:'Checked at'},
  lodgingFind: {ko:'숙소 찾기',en:'Find Accommodation'},
  lodgingHelp: {ko:'주변 숙소 후보를 찾습니다. 예약 가능 여부는 숙소에 직접 확인해 주세요.',en:'Find nearby accommodation. Contact the property directly to check availability.'},
  savedLodging: {ko:'저장된 숙소',en:'Saved Accommodation'},
  registeredLink: {ko:'등록 장소와 연결됨',en:'Linked to a verified place'},
  nearbyLoadFailed: {ko:'주변 장소를 불러오지 못했습니다.',en:'Could not load nearby places.'},
  partialResults: {ko:'일부 범위까지 확인했습니다. 확인된 장소만 보여드립니다.',en:'Only part of the area was checked. Showing confirmed results.'},
  tourismResults: {ko:'지역에서 확인된 관광자원과 가까운 장소를 함께 찾았습니다.',en:'Showing verified local attractions and nearby places.'},
  retainFood: {ko:'다른 음식 종류로 바꾸지 않았습니다. 범위를 넓히거나 ‘전체 음식점’을 선택해 보세요.',en:'Your food category is unchanged. Expand the radius or choose All Food.'},
  partialBand: {ko:'외부 검색이 일부 완료되지 않아 이 거리 구간을 모두 확인하지 못했습니다.',en:'The external search was incomplete for this distance band.'},
  emptyBand: {ko:'이 거리 구간에서는 확인된 장소가 없습니다.',en:'No confirmed places in this distance band.'},
  verifiedFirst: {ko:'승인·검증된 지역 관광 데이터를 먼저 보여드립니다.',en:'Approved and verified local attractions appear first.'},
  nearestCurrent: {ko:'현재 위치에서 가까운 곳',en:'Near Your Current Location'},
  confirmedTourism: {ko:'관광 분류와 지역·좌표가 확인된 주변 검색 결과입니다.',en:'Nearby results with verified tourism categories, areas and coordinates.'},
  nearest: {ko:'가까운 곳',en:'Nearby'},
  confirmedPlaces: {ko:'확인된 장소',en:'Confirmed Places'},
  moreOptions: {ko:'함께 살펴볼 만한 곳',en:'More Places to Explore'},
  navigationClose: {ko:'내비 선택 닫기',en:'Close Navigation Options'},
  navigationQuestion: {ko:'어떤 내비로 이동할까요?',en:'Which navigation app would you like to use?'},
  naver: {ko:'네이버지도',en:'Naver Map'},
  kakao: {ko:'카카오맵',en:'Kakao Map'},
  hoursUnknown: {ko:'현재 운영 여부 확인 필요',en:'Check current opening hours before visiting.'},
  signatureMenu: {ko:'대표 메뉴',en:'Signature Menu'},
  priceRange: {ko:'가격대',en:'Price Range'},
  payment: {ko:'결제',en:'Payment'},
  reservation: {ko:'예약',en:'Reservation'},
  openingHours: {ko:'운영시간',en:'Opening Hours'},
} as const satisfies Record<string, {ko:string; en:string}>;
