import {PlaceDiscoveryService} from '../concierge/place-discovery.service';
import {HAPCHEON_MASTER_DATA} from '../regions/hapcheon/master-data';
import {selectPlaceGuidance} from './place-guidance.selector';
import {PlaceWeatherContextProvider} from '../context/place-weather-context.provider';

const regional={effectiveDataset:jest.fn(async(regionId:string)=>({regionId,records:regionId==='hapcheon'?HAPCHEON_MASTER_DATA:[]}))};
const service=new PlaceDiscoveryService(regional as any);
const entity=(suffix:string)=>HAPCHEON_MASTER_DATA.find(item=>item.entityUri.endsWith(suffix))!;
const connected=(observation:any)=>{const weather={getCurrent:jest.fn(async()=>observation)},hydration={hydrate:jest.fn((base:any,current:any)=>({context:{...base,temperature:current.temperature,windSpeed:current.windSpeed,weather:current.weather,weatherState:current.weather,weatherObservation:{observedAt:current.observedAt,source:current.source,status:current.status,stale:current.stale}}}))},provider=new PlaceWeatherContextProvider(weather as any,hydration as any,{get:jest.fn()}as any);return{service:new PlaceDiscoveryService(regional as any,undefined,undefined,undefined,undefined,provider),weather,provider}};

describe('receipt 35 canonical guidance fixtures',()=>{
 it('keeps guidance in canonical data for three distinct places',()=>{for(const suffix of ['#hwangmaesanCountyPark','#haeinsa','#hapcheonVideoThemePark']){const place=entity(suffix);expect(place.description).toBeTruthy();expect(place.operationalTips?.length).toBeGreaterThan(2);expect(new Set(place.operationalTips?.map(tip=>tip.id)).size).toBe(place.operationalTips?.length)}});
 it('selects fresh rain guidance without changing exact-place ordering',async()=>{const now=new Date().toISOString(),result:any=await service.discover('hapcheon','TOURISM_NATURE','황매산 찾아줘',{weather:'RAIN',weatherState:'RAIN',weatherObservation:{source:'OPEN_METEO',observedAt:now}});expect(result.entities[0]).toMatchObject({entityId:entity('#hwangmaesanCountyPark').entityUri,placeGuidance:{tipId:'mountain-rain',realtime:true}});expect(result.entities[0].reasons).toContain('요청한 장소명과 정확히 일치')});
 it('selects closing-soon guidance only for the matching canonical runtime state',()=>{const video=entity('#hapcheonVideoThemePark'),garden=entity('#hapcheonGardenThemePark'),now=new Date('2026-09-01T08:30:00Z'),context={currentTime:'17:30',runtimeStates:[{entityUri:video.entityUri,operatingState:'CLOSING_SOON',closingTime:'18:00',observedAt:'2026-09-01T08:25:00Z'}]};expect(selectPlaceGuidance(video,context,now).tipId).toBe('theme-park-closing-soon');expect(selectPlaceGuidance(garden,context,now).tipId).toBeUndefined()});
 it('keeps another region with a similar alias free of Hapcheon tips',async()=>{const other={...entity('#hapcheonVideoThemePark'),entityUri:'urn:other:video',canonicalLabelKo:'영상테마파크',alternateLabels:['영상테마파크'],operationalTips:[]},isolated=new PlaceDiscoveryService({effectiveDataset:jest.fn(async(regionId:string)=>({regionId,records:[other]}))}as any),result:any=await isolated.discover('other','TOURISM_NATURE','영상테마파크 찾아줘',{});expect(result.entities[0].placeGuidance).toMatchObject({shortDescription:other.description,realtime:false});expect(result.entities[0].placeGuidance.tipId).toBeUndefined()});
 it('new regions gain the same behavior from data registration alone',()=>{const record={entityUri:'urn:new:place',description:'새 지역의 검증 설명',operationalTips:[{id:'new-general',trigger:{},priority:1,message:'일반 안내',provenance:{sourceType:'OFFICIAL_LOCAL_GOV',sourceName:'새 지역 공식 자료',sourceUrl:'https://new.example',verifiedAt:'2026-09-01'}}]};expect(selectPlaceGuidance(record,{})).toMatchObject({shortDescription:'새 지역의 검증 설명',tipId:'new-general',situationalMessage:'일반 안내'})});
 it('hydrates exact-place weather from the canonical coordinates and selects the fresh strongest tip',async()=>{const observation={observedAt:new Date().toISOString(),weather:'CLEAR',temperature:4,windSpeed:12,source:'OPEN_METEO',status:'LIVE',stale:false},{service:liveService,weather}=connected(observation),result:any=await liveService.discover('hapcheon','TOURISM_NATURE','황매산 찾아줘',{}),mountain=entity('#hwangmaesanCountyPark');expect(weather.getCurrent).toHaveBeenCalledWith(expect.objectContaining({latitude:mountain.latitude,longitude:mountain.longitude,gpsAllowed:true,timeoutMs:1200}));expect(result.entities[0]).toMatchObject({entityId:mountain.entityUri,placeGuidance:{tipId:'mountain-strong-wind',realtime:true,evidenceLabel:'OPEN_METEO'}})});
 it('falls back to the general mountain possibility for stale weather',async()=>{const{service:liveService}=connected({observedAt:new Date().toISOString(),weather:'RAIN',temperature:4,windSpeed:12,source:'OPEN_METEO',status:'STALE',stale:true}),result:any=await liveService.discover('hapcheon','TOURISM_NATURE','황매산 찾아줘',{});expect(result.entities[0].placeGuidance).toMatchObject({tipId:'mountain-general-preparation',realtime:false})});
 it('keeps exact search successful when Open-Meteo fails',async()=>{const{service:liveService,weather}=connected(undefined);weather.getCurrent.mockRejectedValue(new Error('timeout'));const result:any=await liveService.discover('hapcheon','TOURISM_NATURE','황매산 찾아줘',{});expect(result.entities[0]).toMatchObject({entityId:entity('#hwangmaesanCountyPark').entityUri,placeGuidance:{tipId:'mountain-general-preparation',realtime:false}})});
 it('does not call Open-Meteo for a coordinate-less exact place and keeps its verified description',async()=>{const noPoint={...entity('#hwangmaesanCountyPark'),entityUri:'urn:test:no-point',canonicalLabelKo:'좌표 없는 산',alternateLabels:['좌표없는산'],latitude:undefined,longitude:undefined},{weather,provider}=connected({}),isolated=new PlaceDiscoveryService({effectiveDataset:jest.fn(async()=>({regionId:'test',records:[noPoint]}))}as any,undefined,undefined,undefined,undefined,provider),result:any=await isolated.discover('test','TOURISM_NATURE','좌표 없는 산 찾아줘',{});expect(weather.getCurrent).not.toHaveBeenCalled();expect(result.entities[0].placeGuidance).toMatchObject({shortDescription:noPoint.description,tipId:'mountain-general-preparation',realtime:false})});
 it('does not leak mountain weather tips to Haeinsa or Video Theme Park',async()=>{const observation={observedAt:new Date().toISOString(),weather:'CLEAR',temperature:4,windSpeed:12,source:'OPEN_METEO',status:'LIVE',stale:false},{service:liveService}=connected(observation),temple:any=await liveService.discover('hapcheon','TOURISM_NATURE','해인사 찾아줘',{}),video:any=await liveService.discover('hapcheon','TOURISM_NATURE','합천 영상테마파크 찾아줘',{});expect(temple.entities[0].placeGuidance.tipId).toBe('temple-general');expect(video.entities[0].placeGuidance.tipId).toBe('theme-park-general')});
 it('preserves nearby anchor and entity order after bounded weather hydration',async()=>{const observation={observedAt:new Date().toISOString(),weather:'RAIN',temperature:15,windSpeed:2,source:'OPEN_METEO',status:'LIVE',stale:false},{service:liveService}=connected(observation),before:any=await service.discover('hapcheon','TOURISM_NATURE','황매산 주변 관광지',{}),after:any=await liveService.discover('hapcheon','TOURISM_NATURE','황매산 주변 관광지',{});expect(after.anchorEntityId).toBe(before.anchorEntityId);expect(after.entities.map((item:any)=>item.entityId)).toEqual(before.entities.map((item:any)=>item.entityId))});
});
