import { GYERYONG_PUBLIC_TOILETS } from './public-toilets';

export const GYERYONG_MASTER_DATA=[
 {entityUri:'https://gyeryong.example/ontology#militaryCultureFestival',canonicalLabelKo:'계룡 군문화축제',alternateLabels:['군문화축제','계룡군문화축제'],category:'FESTIVAL_EVENT',tags:['MILITARY_CULTURE_HISTORY','FESTIVAL_EVENT','FAMILY_EXPERIENCE'],entityType:'EVENT',runtimeDataStatus:'UNKNOWN',eventAvailability:'UNKNOWN',accessStatus:'PUBLIC_EVENT_UNVERIFIED',accessNotice:'행사 일정과 공개구역 관람 가능 여부는 추가 확인이 필요합니다.'},
 {entityUri:'https://gyeryong.example/ontology#sagyeHistoricHouse',canonicalLabelKo:'사계고택(은농재)',alternateLabels:['사계고택','은농재'],category:'MILITARY_CULTURE_HISTORY',tags:['MILITARY_CULTURE_HISTORY','FAMILY_EXPERIENCE'],entityType:'ATTRACTION',runtimeDataStatus:'PARTIAL',accessStatus:'PUBLIC_INFORMATION_CONFIRMED',accessNotice:'관람 가능 시간은 방문 전에 계룡시 문화관광 안내에서 확인해 주세요.',publicInformationUrl:'https://gyeryong.go.kr/tour/',source:{sourceType:'OFFICIAL_LOCAL_GOV',sourceName:'계룡시 문화관광',sourceUrl:'https://gyeryong.go.kr/tour/'}},
 {entityUri:'https://gyeryong.example/ontology#hyangjeoksanHealingForest',canonicalLabelKo:'향적산치유의숲',alternateLabels:['향적산 치유의 숲','향적산'],category:'TOURISM_NATURE',tags:['TOURISM_NATURE','REST','FAMILY_EXPERIENCE'],entityType:'ATTRACTION',runtimeDataStatus:'PARTIAL',accessStatus:'PUBLIC_INFORMATION_CONFIRMED',accessNotice:'프로그램과 이용 가능 시간은 방문 전에 확인해 주세요.',publicInformationUrl:'https://gyeryong.go.kr/tour/',source:{sourceType:'OFFICIAL_LOCAL_GOV',sourceName:'계룡시 문화관광',sourceUrl:'https://gyeryong.go.kr/tour/'}},
 {entityUri:'https://gyeryong.example/ontology#ipamReservoir',canonicalLabelKo:'입암저수지',alternateLabels:['입암 저수지'],category:'TOURISM_NATURE',tags:['TOURISM_NATURE','REST'],entityType:'ATTRACTION',runtimeDataStatus:'PARTIAL',accessStatus:'PUBLIC_INFORMATION_CONFIRMED',accessNotice:'현장 통행 안내와 안전 표지를 따라 주세요.',publicInformationUrl:'https://gyeryong.go.kr/tour/',source:{sourceType:'OFFICIAL_LOCAL_GOV',sourceName:'계룡시 문화관광',sourceUrl:'https://gyeryong.go.kr/tour/'}},
 {entityUri:'https://gyeryong.example/ontology#goemokjeongPark',canonicalLabelKo:'괴목정',alternateLabels:['괴목정 공원'],category:'TOURISM_NATURE',tags:['TOURISM_NATURE','REST','FAMILY_EXPERIENCE'],entityType:'ATTRACTION',runtimeDataStatus:'PARTIAL',accessStatus:'PUBLIC_INFORMATION_CONFIRMED',accessNotice:'주변 군사시설 출입구역과 혼동하지 않도록 현장 안내를 따라 주세요.',address:'충청남도 계룡시 신도안면 용동리 11',publicInformationUrl:'https://life.gyeryong.go.kr/tour/html/sub02/0203.html',source:{sourceType:'OFFICIAL_LOCAL_GOV',sourceName:'계룡시 문화관광',sourceUrl:'https://life.gyeryong.go.kr/tour/html/sub02/0203.html'}},
 {entityUri:'https://gyeryong.example/ontology#militaryExperienceCenter',canonicalLabelKo:'계룡시병영체험관',alternateLabels:['병영체험관','계룡 병영체험관'],category:'FAMILY_EXPERIENCE',tags:['MILITARY_CULTURE_HISTORY','FAMILY_EXPERIENCE','INDOOR'],entityType:'ATTRACTION',runtimeDataStatus:'PARTIAL',accessStatus:'PUBLIC_INFORMATION_CONFIRMED',accessNotice:'체험 프로그램과 관람 가능 여부는 방문 전에 확인해 주세요.',address:'충청남도 계룡시 신도안면 신도안2길 185',telephone:'042-840-2630',publicInformationUrl:'https://www.gcfct.org/directions',source:{sourceType:'OFFICIAL_LOCAL_GOV',sourceName:'계룡시문화관광재단',sourceUrl:'https://www.gcfct.org/directions'}},
  ...GYERYONG_PUBLIC_TOILETS,
]as const;
