export type VerificationStatus = 'VERIFIED' | 'PARTIAL' | 'UNVERIFIED';
export type ProgramNature = 'OFFICIAL' | 'AI_COMPOSED';
export type WalkingBurden = 'LOW' | 'MODERATE' | 'HIGH' | 'UNKNOWN';
export interface Provenance { sourceName:string; sourceUrl:string; retrievedAt:string; verifiedAt?:string; verificationStatus:VerificationStatus }
export interface OperatingPeriod { days:string[]; validMonths?:number[]; openTime:string; closeTime:string; lastEntryTime?:string; note?:string; provenance:Provenance }
export interface HistoricalOperatingPeriod extends OperatingPeriod { confidence:'HISTORICAL'; currentVerificationRequired:true }
export interface SourceConflict { field:string; values:Array<{value:string; provenance:Provenance}>; reviewed:boolean }
export interface RealPlaceRecord { canonicalId:string; entityUri:string; canonicalLabelKo:string; alternateLabels?:string[]; description?:string; category:string; verificationStatus:VerificationStatus; address?:string; addressProvenance?:Provenance; lotAddress?:string; lotAddressProvenance?:Provenance; telephone?:string; telephoneProvenance?:Provenance; website?:string; managementOrganization?:string; latitude?:number; longitude?:number; coordinateProvenance?:Provenance; detailsProvenance:Provenance; operatingHours?:OperatingPeriod[]; historicalOperatingHours?:HistoricalOperatingPeriod[]; walkingBurden?:WalkingBurden; parking?:'AVAILABLE'|'UNKNOWN'; accessibilityNotes?:string[]; sourceConflicts?:SourceConflict[]; externalAliases?:string[]; demoOnly?:boolean }
export interface MasterProgramRecord { entityUri:string; nature:ProgramNature; heldAtFacility:string; provenance:Provenance }

const GAJO='https://gajo-wellness.kr/ontology#';
const retrievedAt='2026-08-09T00:00:00.000Z';
const publicForest:Provenance={sourceName:'공공데이터포털 전국휴양림표준데이터',sourceUrl:'https://www.data.go.kr/data/15013111/standard.do',retrievedAt,verifiedAt:'2024-05-07',verificationStatus:'VERIFIED'};
const ktoHealing:Provenance={sourceName:'한국관광공사 대한민국 구석구석',sourceUrl:'https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=fc1d8100-2371-4b07-841b-8b416f9135a8',retrievedAt,verifiedAt:'2024-09-01',verificationStatus:'PARTIAL'};
const countyHealing:Provenance={sourceName:'거창군 문화관광',sourceUrl:'https://www.geochang.go.kr/02534/00502.web?amode=view&id=TL0001860',retrievedAt,verifiedAt:'2024-12-10',verificationStatus:'VERIFIED'};
const countyFood:Provenance={sourceName:'거창군 문화관광 거창韓맛집',sourceUrl:'https://www.geochang.go.kr/00492/03370.web',retrievedAt,verifiedAt:'2025-11-13',verificationStatus:'PARTIAL'};
const ktoHotSpring:Provenance={sourceName:'한국관광공사 대한민국 구석구석',sourceUrl:'https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=9575d17c-ccd0-4b9d-87f2-6b184fde395b',retrievedAt,verifiedAt:'2019-12-01',verificationStatus:'PARTIAL'};
const publicBath:Provenance={sourceName:'경상남도 거창군 목욕장업현황',sourceUrl:'https://www.data.go.kr/data/15113010/fileData.do',retrievedAt,verifiedAt:'2026-03-05',verificationStatus:'VERIFIED'};
const openDays=['TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'];

export const REAL_PLACE_RECORDS:RealPlaceRecord[]=[
 {canonicalId:'geochang-anti-aging-healing-land',entityUri:`${GAJO}antiAgingHealingLand`,canonicalLabelKo:'거창 항노화힐링랜드',alternateLabels:['항노화자연휴양림'],description:'우두산의 산림 휴양·치유 시설로 Y자형 출렁다리와 무장애 데크로드가 있습니다.',category:'산림휴양시설',verificationStatus:'VERIFIED',address:'경상남도 거창군 가조면 의상봉길 834',telephone:'055-940-7933',website:'https://www.foresttrip.go.kr/indvz/main.do?hmpgId=ID02030109',managementOrganization:'거창군청',latitude:35.73662049,longitude:128.0408983,coordinateProvenance:publicForest,detailsProvenance:publicForest,walkingBurden:'UNKNOWN',parking:'AVAILABLE',accessibilityNotes:['경사도 8% 미만 무장애 데크로드'],operatingHours:[{days:openDays,validMonths:[3,4,5,6,7,8,9,10],openTime:'09:00',closeTime:'18:00',lastEntryTime:'17:00',note:'3월~10월, 월요일 휴무',provenance:ktoHealing},{days:openDays,validMonths:[11,12,1,2],openTime:'09:00',closeTime:'17:00',lastEntryTime:'16:00',note:'11월~2월, 월요일 휴무',provenance:ktoHealing}],sourceConflicts:[{field:'telephone',reviewed:false,values:[{value:'055-940-7933',provenance:publicForest},{value:'055-940-7930',provenance:ktoHealing}]}]},
 {canonicalId:'gajo-baekdusan-cheonji-hot-spring',entityUri:`${GAJO}gajoHotSpringComplex`,canonicalLabelKo:'백두산천지온천',alternateLabels:['가조 백두산천지온천'],description:'가조온천 관광지의 온천 목욕 시설입니다.',category:'온천시설',verificationStatus:'PARTIAL',address:'경상남도 거창군 가조면 온천길 161',addressProvenance:publicBath,lotAddress:'경상남도 거창군 가조면 일부리 1301',lotAddressProvenance:publicBath,telephone:'055-941-0721',telephoneProvenance:publicBath,latitude:35.698758,longitude:128.023103,coordinateProvenance:publicBath,walkingBurden:'UNKNOWN',parking:'UNKNOWN',detailsProvenance:publicBath,historicalOperatingHours:[{days:['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY'],openTime:'05:30',closeTime:'20:30',note:'과거 관광정보 기준이며 현재 운영시간 확인 필요',provenance:ktoHotSpring,confidence:'HISTORICAL',currentVerificationRequired:true},{days:['SATURDAY','SUNDAY'],openTime:'05:30',closeTime:'21:30',note:'과거 주말·공휴일 관광정보 기준이며 현재 운영시간 확인 필요',provenance:ktoHotSpring,confidence:'HISTORICAL',currentVerificationRequired:true}]},
 {canonicalId:'gajo-miga-chueotang',entityUri:`${GAJO}localFoodRestaurant`,canonicalLabelKo:'미가추어탕',description:'거창군이 안내하는 가조면 음식점입니다.',category:'음식점',verificationStatus:'PARTIAL',address:'경상남도 거창군 가조면 지산로 1477',telephone:'0507-1408-1006',walkingBurden:'UNKNOWN',parking:'UNKNOWN',detailsProvenance:countyFood},
 {canonicalId:'gajo-daon-cafe',entityUri:`${GAJO}wellnessLounge`,canonicalLabelKo:'다온 카페',description:'거창군이 안내하는 가조면 카페입니다.',category:'카페·휴식',verificationStatus:'PARTIAL',address:'경상남도 거창군 가조면 의상봉길 45-21',telephone:'055-942-7578',walkingBurden:'UNKNOWN',parking:'UNKNOWN',detailsProvenance:countyFood}
];

const ai=(entityUri:string,heldAtFacility:string):MasterProgramRecord=>({entityUri,nature:'AI_COMPOSED',heldAtFacility,provenance:{sourceName:'Gajo concierge ontology',sourceUrl:'repository:server/src/ontology-data/gajo_ai_concierge_domain_v1_0.ttl',retrievedAt,verificationStatus:'UNVERIFIED'}});
export const MASTER_PROGRAM_RECORDS=[ai(`${GAJO}lowIntensityHotSpringCourse`,`${GAJO}indoorHotSpringBath`),ai(`${GAJO}meditationLoungeProgram`,`${GAJO}wellnessLounge`),ai(`${GAJO}localFoodHealingMeal`,`${GAJO}localFoodRestaurant`),ai(`${GAJO}shortIndoorSeniorCourse`,`${GAJO}wellnessLounge`)];
