import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { OntologyGraphService } from '../ontology/ontology-graph.service';
import { CLASS } from '../ontology/ontology.constants';
import { MASTER_PROGRAM_RECORDS, REAL_PLACE_RECORDS, RealPlaceRecord } from './master-data.records';

export const DEFAULT_CLOSING_SOON_MINUTES=60;

@Injectable()
export class MasterDataService {
 constructor(private readonly graph:OntologyGraphService,private readonly config?:ConfigService){this.assertValid()}
 places(){return REAL_PLACE_RECORDS}
 programs(){return MASTER_PROGRAM_RECORDS}
 place(uri?:string){return uri?REAL_PLACE_RECORDS.find(r=>r.entityUri===uri):undefined}
 resolveCanonical(value:string){const normalized=this.normalize(value);return REAL_PLACE_RECORDS.find(r=>r.canonicalId===value||r.entityUri===value||r.externalAliases?.includes(value)||[r.canonicalLabelKo,...(r.alternateLabels||[])].some(label=>this.normalize(label)===normalized))}
 verifiedCoordinates(uri?:string){const r=this.place(uri);return r?.coordinateProvenance?.verificationStatus==='VERIFIED'&&Number.isFinite(r.latitude)&&Number.isFinite(r.longitude)?{latitude:r.latitude!,longitude:r.longitude!,sourceUri:r.entityUri}:undefined}
 mapEligiblePlaces(){return REAL_PLACE_RECORDS.filter(r=>Boolean(this.verifiedCoordinates(r.entityUri)))}
 closingSoonMinutes(){const value=Number(this.config?.get('CLOSING_SOON_MINUTES')||DEFAULT_CLOSING_SOON_MINUTES);return Number.isFinite(value)&&value>=15&&value<=180?value:DEFAULT_CLOSING_SOON_MINUTES}
 deriveOperatingState(uri:string,dayOfWeek?:string,currentTime?:string,currentDate?:string){const record=this.place(uri);if(!record?.operatingHours?.length||!dayOfWeek||!/^\d{2}:\d{2}/.test(currentTime||''))return {operatingState:'UNKNOWN' as const};const month=currentDate&&/^\d{4}-\d{2}-/.test(currentDate)?Number(currentDate.slice(5,7)):undefined;const dayPeriods=record.operatingHours.filter(p=>p.days.includes(dayOfWeek.toUpperCase()));const period=dayPeriods.find(p=>!p.validMonths||month===undefined||p.validMonths.includes(month));if(!period)return {operatingState:(dayPeriods.length?'UNKNOWN':'CLOSED') as 'UNKNOWN'|'CLOSED'};const now=this.minutes(currentTime!),open=this.minutes(period.openTime),close=this.minutes(period.closeTime);if(now<open||now>=close)return {operatingState:'CLOSED' as const,closingTime:period.closeTime};return {operatingState:(close-now<=this.closingSoonMinutes()?'CLOSING_SOON':'OPEN') as 'OPEN'|'CLOSING_SOON',closingTime:period.closeTime};}
 quality(){const facilities=this.graph.individualsOfIncludingSubclasses(CLASS.Facility);const programUris=new Set(this.graph.individualsOfIncludingSubclasses(CLASS.Program));const entities=facilities.map(uri=>{const r=this.place(uri);const flags:string[]=[];if(!r?.latitude||r.coordinateProvenance?.verificationStatus!=='VERIFIED')flags.push('MISSING_COORDINATES');if(!r?.address)flags.push('MISSING_ADDRESS');if(!r?.operatingHours?.length)flags.push('MISSING_HOURS');if(!r?.telephone)flags.push('MISSING_PHONE');if(!r||r.verificationStatus==='UNVERIFIED')flags.push('UNVERIFIED');if(r?.verificationStatus==='PARTIAL')flags.push('PARTIAL');if(r?.sourceConflicts?.some(c=>!c.reviewed))flags.push('SOURCE_CONFLICT');const fieldVerification={coordinates:r?.coordinateProvenance?.verificationStatus||'UNVERIFIED',address:r?.addressProvenance?.verificationStatus||'UNVERIFIED',lotAddress:r?.lotAddressProvenance?.verificationStatus||'UNVERIFIED',telephone:r?.telephoneProvenance?.verificationStatus||'UNVERIFIED',operatingHours:r?.operatingHours?.length&&r.operatingHours.every(h=>h.provenance.verificationStatus==='VERIFIED')?'VERIFIED':'UNVERIFIED'};return {entityUri:uri,label:this.graph.label(uri),record:r,fieldVerification,flags}});const programs=MASTER_PROGRAM_RECORDS.map(p=>({...p,flags:[...(programUris.has(p.entityUri)?[]:['UNKNOWN_PROGRAM']),...(facilities.includes(p.heldAtFacility)?[]:['BROKEN_PROGRAM_LINK'])]}));const summary={total:entities.length,verified:entities.filter(e=>e.record?.verificationStatus==='VERIFIED').length,partial:entities.filter(e=>e.record?.verificationStatus==='PARTIAL').length,unverified:entities.filter(e=>!e.record||e.record.verificationStatus==='UNVERIFIED').length,withCoordinates:entities.filter(e=>!e.flags.includes('MISSING_COORDINATES')).length};return {summary,entities,programs}}
 validate(records:RealPlaceRecord[]=REAL_PLACE_RECORDS){const errors:string[]=[];const ids=new Set<string>(),uris=new Set<string>(),labels=new Set<string>();for(const r of records){const label=this.normalize(r.canonicalLabelKo);if(!r.canonicalId?.trim())errors.push(`EMPTY_CANONICAL_ID:${r.entityUri}`);if(!label)errors.push(`EMPTY_LABEL:${r.entityUri}`);if(ids.has(r.canonicalId))errors.push(`DUPLICATE_CANONICAL_ID:${r.canonicalId}`);if(uris.has(r.entityUri))errors.push(`DUPLICATE_ENTITY:${r.entityUri}`);if(labels.has(label))errors.push(`DUPLICATE_NORMALIZED_LABEL:${label}`);ids.add(r.canonicalId);uris.add(r.entityUri);labels.add(label);if(r.latitude!==undefined&&(r.latitude<33||r.latitude>39))errors.push(`SUSPICIOUS_LATITUDE:${r.entityUri}`);if(r.longitude!==undefined&&(r.longitude<124||r.longitude>132))errors.push(`SUSPICIOUS_LONGITUDE:${r.entityUri}`);if(r.verificationStatus==='VERIFIED'&&(!r.detailsProvenance||r.detailsProvenance.verificationStatus!=='VERIFIED'))errors.push(`VERIFIED_WITHOUT_PROVENANCE:${r.entityUri}`);if((r.latitude!==undefined||r.longitude!==undefined)&&(!r.coordinateProvenance||r.coordinateProvenance.verificationStatus!=='VERIFIED'))errors.push(`COORDINATES_WITHOUT_VERIFIED_PROVENANCE:${r.entityUri}`);if(r.demoOnly)errors.push(`DEMO_LIVE_CONTAMINATION:${r.entityUri}`);for(const h of r.operatingHours||[]){if(!/^\d{2}:\d{2}$/.test(h.openTime)||!/^\d{2}:\d{2}$/.test(h.closeTime)||this.minutes(h.openTime)>=this.minutes(h.closeTime))errors.push(`INVALID_HOURS:${r.entityUri}`);if(!h.provenance)errors.push(`HOURS_WITHOUT_PROVENANCE:${r.entityUri}`)}for(let i=0;i<(r.operatingHours||[]).length;i++)for(let j=i+1;j<(r.operatingHours||[]).length;j++){const a=r.operatingHours![i],b=r.operatingHours![j],sameDay=a.days.some(d=>b.days.includes(d)),months=(a.validMonths||[]).some(m=>(b.validMonths||[]).includes(m));if(sameDay&&months&&a.openTime!==b.openTime)errors.push(`CONTRADICTORY_SEASONAL_HOURS:${r.entityUri}`)}}return errors}
 validateOntologyLinks(){const facilities=new Set(this.graph.individualsOfIncludingSubclasses(CLASS.Facility));const programs=new Set(this.graph.individualsOfIncludingSubclasses(CLASS.Program));return [...REAL_PLACE_RECORDS.filter(r=>!facilities.has(r.entityUri)).map(r=>`BROKEN_ONTOLOGY_URI:${r.entityUri}`),...MASTER_PROGRAM_RECORDS.flatMap(p=>[...(programs.has(p.entityUri)?[]:[`BROKEN_PROGRAM_URI:${p.entityUri}`]),...(facilities.has(p.heldAtFacility)?[]:[`BROKEN_HELD_AT:${p.entityUri}`])])]}
 private assertValid(){const errors=this.validate();if(errors.length)throw new Error(`Invalid master data: ${errors.join(', ')}`)}
 private normalize(value:string){return (value||'').normalize('NFKC').toLowerCase().replace(/[\s·ㆍ_\-()]/g,'')}
 private minutes(value:string){const [hour,minute]=value.split(':').map(Number);return hour*60+minute}
}
