import type {OperationalTip} from '../../place-guidance/place-guidance.types';

export type HapcheonSourceType='OFFICIAL_LOCAL_GOV'|'OFFICIAL_BUSINESS'|'KTO'|'OFFICIAL_MAP_LISTING';
export interface HapcheonSource{sourceType:HapcheonSourceType;sourceName:string;sourceUrl:string;verifiedAt:string}
export interface HapcheonCandidateRecord{entityUri:string;canonicalId:string;regionId:'hapcheon';themeId?:string;relatedEntityIds?:readonly string[];displayName:{ko:string;en?:string};canonicalLabelKo:string;alternateLabels:readonly string[];category:string;tags:readonly string[];runtimeDataStatus:'PARTIAL'|'VERIFIED';entityType:string;representativeAnchor?:boolean;season?:'AUTUMN';eventAvailability?:'UNKNOWN';accessNotice?:string;accommodationType?:string;areaLabel?:string;address?:string;telephone?:string;website?:string;reservationUrl?:string;reservationAction?:{kind:'DIRECT_BOOKING';verificationStatus:'VERIFIED';verifiedUrl:string;sourceUrl:string;verifiedAt:string};publicInformationUrl?:string;latitude?:number;longitude?:number;coordinateSource?:HapcheonSource;description:string;operationalTips?:readonly OperationalTip[];source:HapcheonSource;lastVerifiedAt:string;actions:{detail?:{url:string};reserve?:{url:string;evidenceMode:'VERIFIED_DIRECT'};call?:{phone:string};navigate?:{latitude:number;longitude:number};website?:{url:string}}}
const verifiedAt='2026-08-19';
const kto=(id:string):HapcheonSource=>({sourceType:'KTO',sourceName:'한국관광공사 관광정보',sourceUrl:`https://data.visitkorea.or.kr/resource/${id}`,verifiedAt});
const county=(url:string,name='합천군 공식 정보'):HapcheonSource=>({sourceType:'OFFICIAL_LOCAL_GOV',sourceName:name,sourceUrl:url,verifiedAt});
const business=(url:string):HapcheonSource=>({sourceType:'OFFICIAL_BUSINESS',sourceName:'합천호 스마일펜션 공식 홈페이지',sourceUrl:url,verifiedAt});
type Input=Omit<HapcheonCandidateRecord,'regionId'|'lastVerifiedAt'|'canonicalLabelKo'|'alternateLabels'|'actions'> & {aliases?:string[];recordVerifiedAt?:string};
const record=(v:Input):HapcheonCandidateRecord=>{const{aliases,recordVerifiedAt,...place}=v;const actions:HapcheonCandidateRecord['actions']={detail:{url:place.publicInformationUrl||place.website||place.source.sourceUrl}};if(place.reservationAction?.kind==='DIRECT_BOOKING'&&place.reservationAction.verificationStatus==='VERIFIED'&&place.reservationAction.verifiedUrl===place.reservationUrl&&place.reservationUrl!==place.website)actions.reserve={url:place.reservationUrl!,evidenceMode:'VERIFIED_DIRECT'};if(place.telephone)actions.call={phone:place.telephone};if(place.latitude!==undefined&&place.longitude!==undefined)actions.navigate={latitude:place.latitude,longitude:place.longitude};if(place.website)actions.website={url:place.website};return{...place,regionId:'hapcheon',lastVerifiedAt:recordVerifiedAt||verifiedAt,canonicalLabelKo:place.displayName.ko,alternateLabels:aliases||[],actions}};
const HAPCHEON_BASE_DATA:readonly HapcheonCandidateRecord[]=[
 record({entityUri:'https://hapcheon.example/ontology#meteorImpactCrater',canonicalId:'hapcheon-meteor-impact-crater',themeId:'hapcheon-meteor-crater',relatedEntityIds:['https://hapcheon.example/ontology#meteorVisitorCenter','https://hapcheon.example/ontology#daeamsanCraterObservatory','https://hapcheon.example/ontology#meteorCraterRoundTrail'],displayName:{ko:'합천운석충돌구 전체'},aliases:['합천운석충돌구','적중-초계분지'],category:'GEO_TOURISM',tags:['TOURISM_NATURE','GEOLOGY','FAMILY_TRIP'],runtimeDataStatus:'VERIFIED',entityType:'PLACE_CONCEPT',areaLabel:'초계면·적중면 일원',latitude:35.565,longitude:128.255,description:'약 5만 년 전 운석 충돌로 형성된 것으로 확인된 동서 약 7km, 남북 약 4km의 적중-초계분지입니다.',publicInformationUrl:'https://www.kigam.re.kr/board.es?act=view&bid=0025&list_no=47845&mid=a10703040000',source:county('https://www.kigam.re.kr/board.es?act=view&bid=0025&list_no=47845&mid=a10703040000','한국지질자원연구원')}),
 record({entityUri:'https://hapcheon.example/ontology#meteorVisitorCenter',canonicalId:'hapcheon-meteor-visitor-center',themeId:'hapcheon-meteor-crater',relatedEntityIds:['https://hapcheon.example/ontology#meteorImpactCrater'],displayName:{ko:'합천운석충돌구 관광안내소'},aliases:['운석충돌구 관광안내소'],category:'GEO_TOURISM',tags:['INDOOR','GEOLOGY','FAMILY_TRIP'],runtimeDataStatus:'VERIFIED',entityType:'VISITOR_CENTER',address:'경상남도 합천군 초계면 초계대공원 일원',latitude:35.561,longitude:128.266,description:'형성과정, 지질 배경과 시추 표본을 살펴보는 초계대공원 내 안내 공간입니다. 운영시간은 출발 전 공식 안내로 확인해야 합니다.',publicInformationUrl:'https://www.hc.go.kr/_res/portal/data/pdf/h09113/2024_10.pdf',source:county('https://www.hc.go.kr/_res/portal/data/pdf/h09113/2024_10.pdf')}),
 record({entityUri:'https://hapcheon.example/ontology#daeamsanCraterObservatory',canonicalId:'hapcheon-daeamsan-crater-observatory',themeId:'hapcheon-meteor-crater',relatedEntityIds:['https://hapcheon.example/ontology#meteorImpactCrater'],displayName:{ko:'대암산 전망대'},aliases:['합천운석충돌구 전망대'],category:'GEO_TOURISM',tags:['TOURISM_NATURE','GEOLOGY','VIEWPOINT'],runtimeDataStatus:'VERIFIED',entityType:'VIEWPOINT',address:'경상남도 합천군 초계면 대암산 일원',latitude:35.585,longitude:128.245,description:'대암산에서 적중-초계분지의 넓은 지형을 내려다보는 전망 지점입니다. 산길 현장 상태는 출발 전 확인해야 합니다.',publicInformationUrl:'https://www.kigam.re.kr/gallery.es?act=you_view&bid=0019&list_no=5336&mid=a10206020000',source:county('https://www.kigam.re.kr/gallery.es?act=you_view&bid=0019&list_no=5336&mid=a10206020000','한국지질자원연구원')}),
 record({entityUri:'https://hapcheon.example/ontology#meteorCraterRoundTrail',canonicalId:'hapcheon-meteor-crater-round-trail',themeId:'hapcheon-meteor-crater',relatedEntityIds:['https://hapcheon.example/ontology#meteorImpactCrater','https://hapcheon.example/ontology#daeamsanCraterObservatory'],displayName:{ko:'합천운석충돌구 환종주 탐방로'},aliases:['운석충돌구 환종주'],category:'GEO_TOURISM',tags:['ACTIVITY','GEOLOGY','HIKING'],runtimeDataStatus:'VERIFIED',entityType:'TRAIL',address:'경상남도 합천군 초계면·적중면 일원',latitude:35.58,longitude:128.25,description:'분지를 둘러싼 산지를 연결하는 탐방로입니다. 구간별 정비와 현장 통제가 있을 수 있으므로 출발 전 공식 안내를 확인해야 합니다.',publicInformationUrl:'https://www.hccl.go.kr/CLRecords/Files/FileAppendix/a9/A007384.pdf',source:county('https://www.hccl.go.kr/CLRecords/Files/FileAppendix/a9/A007384.pdf')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonLake',canonicalId:'hapcheon-lake',displayName:{ko:'합천호'},aliases:['합천 호수'],category:'HAPCHEON_LAKE',tags:['HAPCHEON_LAKE','TOURISM_NATURE','SCENIC_DRIVE','FAMILY_TRIP','REST'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 대병면 합천호수로 197',latitude:35.5305,longitude:128.0324,description:'합천댐으로 조성된 호수와 주변 경관을 만나는 합천의 대표 관광 권역입니다.',publicInformationUrl:'https://www.hc.go.kr/tour.web',source:county('https://www.hc.go.kr/tour.web','합천군 문화관광')}),
 record({entityUri:'https://hapcheon.example/ontology#haeinsa',canonicalId:'hapcheon-haeinsa',displayName:{ko:'해인사'},aliases:['합천 해인사'],category:'TOURISM_CULTURE',tags:['TOURISM_NATURE','FAMILY_TRIP'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 가야면 해인사길 122',telephone:'055-934-3000',latitude:35.8005687584,longitude:128.0971196597,description:'고려대장경판을 보관한 법보사찰입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/126175',source:kto('126175')}),
 record({entityUri:'https://hapcheon.example/ontology#hwangmaesanCountyPark',canonicalId:'hapcheon-hwangmaesan-county-park',displayName:{ko:'황매산 군립공원'},aliases:['황매산'],category:'TOURISM_NATURE',tags:['TOURISM_NATURE','SCENIC_DRIVE'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 가회면 황매산공원길 331',telephone:'055-930-4769',latitude:35.4822804994,longitude:127.9831021731,description:'철쭉과 억새 경관으로 알려진 합천의 군립공원입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/1622663',source:kto('1622663')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonVideoThemePark',canonicalId:'hapcheon-video-theme-park',displayName:{ko:'합천 영상테마파크'},aliases:['합천영상테마파크','영상테마파크'],category:'TOURISM_CULTURE',tags:['TOURISM_NATURE','FAMILY_TRIP','ACTIVITY'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 용주면 합천호수로 757',telephone:'055-930-8633',latitude:35.5484940723,longitude:128.0730785888,description:'시대물 영화와 드라마 촬영 세트를 둘러보는 합천의 영상문화 관광지입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/2469441',source:kto('2469441')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonGardenThemePark',canonicalId:'hapcheon-garden-theme-park',displayName:{ko:'합천 정원테마파크'},aliases:['정원테마파크'],category:'TOURISM_CULTURE',tags:['TOURISM_NATURE','FAMILY_TRIP','ACTIVITY'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',representativeAnchor:false,address:'경상남도 합천군 용주면 합천호수로 777',telephone:'055-930-8633',latitude:35.553365758,longitude:128.0738450568,description:'합천 영상테마파크와 연결된 정원·전시 관광시설입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/3060352',source:kto('3060352')}),
 record({entityUri:'https://hapcheon.example/ontology#hwangmaesanSilverGrassFestival',canonicalId:'hwangmaesan-silver-grass-festival',displayName:{ko:'황매산 억새축제'},aliases:['황매산억새축제'],category:'FESTIVAL_EXHIBITION',tags:['FESTIVAL_EXHIBITION','SEASONAL','AUTUMN'],runtimeDataStatus:'VERIFIED',entityType:'EVENT',season:'AUTUMN',eventAvailability:'UNKNOWN',accessNotice:'가을 축제이며 세부 개최일·시간·요금은 공식 일정 확인이 필요합니다.',address:'경상남도 합천군 가회면 황매산공원길 331',latitude:35.4822804994,longitude:127.9831021731,description:'황매산군립공원 일원에서 열리는 가을 억새축제입니다. 세부 일정은 공식 안내를 확인해야 합니다.',publicInformationUrl:'https://www.hc.go.kr/_res/portal/data/pdf/h09773/2026_18.pdf',source:county('https://www.hc.go.kr/_res/portal/data/pdf/h09773/2026_18.pdf','합천군 황매산 축제계획')}),
 record({entityUri:'https://hapcheon.example/ontology#cPark',canonicalId:'hapcheon-c-park',displayName:{ko:'씨파크'},aliases:['합천 씨파크'],category:'ACTIVITY',tags:['ACTIVITY','FAMILY_TRIP','CAFE'],runtimeDataStatus:'VERIFIED',entityType:'EXPERIENCE',address:'경상남도 합천군 합천호수로 525',latitude:35.5444275199,longitude:128.0537942855,description:'대병면에 위치한 체험·휴식 복합 공간입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/2992061',source:kto('2992061')}),
 record({entityUri:'https://hapcheon.example/ontology#yuseongGardenRestaurant',canonicalId:'hapcheon-yuseong-garden-restaurant',displayName:{ko:'유성가든식당'},aliases:['유성가든'],category:'FOOD',tags:['FOOD','HAPCHEON_LAKE'],runtimeDataStatus:'PARTIAL',entityType:'RESTAURANT',address:'경상남도 합천군 대병면 서부로 2081',telephone:'055-933-7055',accessNotice:'공식 정보의 영업시간 표기가 서로 맞지 않아 방문 전 전화로 확인해 주세요.',description:'합천군 공식 음식점 정보에 메기탕과 붕어찜 대표 메뉴로 등록된 대병면 식당입니다.',publicInformationUrl:'https://www.hc.go.kr/06543/08050/08052.web?amode=view&idx=20',source:{sourceType:'OFFICIAL_LOCAL_GOV',sourceName:'합천군 문화관광 음식점 정보',sourceUrl:'https://www.hc.go.kr/06543/08050/08052.web?amode=view&idx=20',verifiedAt:'2026-09-05'},recordVerifiedAt:'2026-09-05'}),
 record({entityUri:'https://hapcheon.example/ontology#cafeMotorrad',canonicalId:'hapcheon-cafe-motorrad',displayName:{ko:'카페 모토라드 합천'},aliases:['카페모토라드'],category:'CAFE',tags:['CAFE','SCENIC_DRIVE','REST'],runtimeDataStatus:'PARTIAL',entityType:'CAFE',address:'경상남도 합천군 대병면 합천호수로 525',telephone:'0507-1388-8883',latitude:35.5444275199,longitude:128.0537942855,website:'https://c-park.co.kr/cafe',description:'합천호 주요 차량 이동 경로의 카페입니다.',publicInformationUrl:'https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=186625',source:kto('2992061')}),
 record({entityUri:'https://hapcheon.example/ontology#cherryRoastery',canonicalId:'hapcheon-cherry-roastery',displayName:{ko:'커피볶는집체리'},aliases:['커피 볶는 집 체리'],category:'CAFE',tags:['CAFE','REST'],runtimeDataStatus:'PARTIAL',entityType:'CAFE',address:'경상남도 합천군 용주면 합천호수로 757',description:'합천 영상테마파크 이동 경로에 등록된 카페입니다.',publicInformationUrl:'https://www.hc.go.kr/05752/05908/07350.web',source:county('https://www.hc.go.kr/05752/05908/07350.web','합천군 사업체 정보')}),
 record({entityUri:'https://hapcheon.example/ontology#cafeMoida',canonicalId:'hapcheon-cafe-moida',displayName:{ko:'카페모이다'},aliases:['카페 모이다'],category:'CAFE',tags:['CAFE','HAPCHEON_LAKE','REST'],runtimeDataStatus:'PARTIAL',entityType:'CAFE',address:'경상남도 합천군 대병면 서부로 1979-1',description:'합천호 권역 대병면에 등록된 카페입니다.',publicInformationUrl:'https://www.hc.go.kr/05752/05908/07350.web',source:county('https://www.hc.go.kr/05752/05908/07350.web','합천군 사업체 정보')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonLakeSmilePension',canonicalId:'hapcheon-lake-smile-pension',displayName:{ko:'합천호 스마일펜션'},aliases:['스마일펜션','합천호수뷰 스마일펜션'],category:'ACCOMMODATION',tags:['ACCOMMODATION','FAMILY_TRIP','HAPCHEON_LAKE','REST'],runtimeDataStatus:'VERIFIED',entityType:'ACCOMMODATION',accommodationType:'PENSION',areaLabel:'합천호 권역',address:'경상남도 합천군 대병면 회양관광단지길 61',telephone:'055-931-1638',website:'https://www.lakesmile.com/',reservationUrl:'https://rev.yapen.co.kr/external?ypIdx=24507',latitude:35.524485899856,longitude:128.01578179029,coordinateSource:{sourceType:'OFFICIAL_MAP_LISTING',sourceName:'지방행정인허가 숙박업 데이터·카카오/VWorld 지도',sourceUrl:'https://flg.purpleo.co.kr/view/26602',verifiedAt},description:'회양관광단지에서 합천호를 바라보는 가족·커플형 펜션입니다.',publicInformationUrl:'https://www.lakesmile.com/',source:business('https://www.lakesmile.com/')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonLakeCharcoalGalbi',canonicalId:'hapcheon-lake-charcoal-galbi',displayName:{ko:'합천호 한우숯불갈비'},aliases:['합천호 숯불갈비'],category:'FOOD',tags:['FOOD','HAPCHEON_LAKE'],runtimeDataStatus:'PARTIAL',entityType:'RESTAURANT',telephone:'055-931-2995',description:'합천호 관광단지에서 펜션 공식 홈페이지가 안내하는 음식점입니다.',publicInformationUrl:'https://www.lakesmile.com/펜션서비스',source:business('https://www.lakesmile.com/펜션서비스')}),
 record({entityUri:'https://hapcheon.example/ontology#bukeoMaeul',canonicalId:'hapcheon-bukeo-maeul',displayName:{ko:'북어마을'},category:'FOOD',tags:['FOOD','HAPCHEON_LAKE'],runtimeDataStatus:'PARTIAL',entityType:'RESTAURANT',telephone:'055-934-0666',description:'합천호 관광단지에서 펜션 공식 홈페이지가 안내하는 음식점입니다.',publicInformationUrl:'https://www.lakesmile.com/펜션서비스',source:business('https://www.lakesmile.com/펜션서비스')}),
];
const guidanceSource=(id:string)=>kto(id);
const guidanceByEntity:Record<string,readonly OperationalTip[]>={
 'https://hapcheon.example/ontology#hwangmaesanCountyPark':[
  {id:'mountain-general-preparation',trigger:{},priority:10,message:'산 정상은 기온과 바람이 갑자기 달라질 수 있어요.',actionSuggestion:'겉옷과 물을 준비하세요.',provenance:guidanceSource('1622663')},
  {id:'mountain-low-temperature',trigger:{temperatureAtMost:8},priority:80,message:'오늘은 산 정상 기온이 낮아 쌀쌀해요.',actionSuggestion:'보온 겉옷을 챙기세요.',provenance:guidanceSource('1622663'),realtimeRequired:true,maxAgeMinutes:60},
  {id:'mountain-strong-wind',trigger:{windSpeedAtLeast:9},priority:90,message:'현재 바람이 강해 능선 체감온도가 낮을 수 있어요.',actionSuggestion:'노출된 능선에서는 안전에 유의하세요.',provenance:guidanceSource('1622663'),realtimeRequired:true,maxAgeMinutes:30},
  {id:'mountain-rain',trigger:{weather:['LIGHT_RAIN','RAIN','HEAVY_RAIN','THUNDERSTORM']},priority:95,message:'현재 비가 내려 산길이 미끄러울 수 있어요.',actionSuggestion:'미끄럼 방지 신발을 준비하고 무리한 산행은 피하세요.',provenance:guidanceSource('1622663'),realtimeRequired:true,maxAgeMinutes:30},
  {id:'mountain-walking-low',trigger:{walkingLevels:['LOW']},priority:40,message:'경사와 비포장 구간이 있어 보행 부담이 생길 수 있어요.',actionSuggestion:'짧은 전망 구간부터 살펴보세요.',provenance:guidanceSource('1622663')},
  {id:'mountain-elderly',trigger:{companionTags:['ELDERLY']},priority:50,message:'노약자와 함께라면 경사와 기온 변화를 고려해야 해요.',actionSuggestion:'휴식 지점을 정하고 무리하지 마세요.',provenance:guidanceSource('1622663')},
 ],
 'https://hapcheon.example/ontology#haeinsa':[
  {id:'temple-general',trigger:{},priority:10,message:'문화재와 사찰 공간을 천천히 둘러보는 방문지예요.',actionSuggestion:'조용한 관람 예절을 지켜 주세요.',provenance:guidanceSource('126175')},
  {id:'temple-closing-soon',trigger:{operatingStates:['CLOSING_SOON'],minutesToCloseAtMost:60},priority:90,message:'관람 종료가 가까워지고 있어요.',actionSuggestion:'핵심 관람 동선을 먼저 확인하세요.',provenance:guidanceSource('126175'),realtimeRequired:true,maxAgeMinutes:20},
  {id:'temple-walking-low',trigger:{walkingLevels:['LOW']},priority:45,message:'주차·진입 지점에서 주요 전각까지 걸을 수 있어요.',actionSuggestion:'중간에 쉬어 갈 시간을 포함하세요.',provenance:guidanceSource('126175')},
  {id:'temple-elderly',trigger:{companionTags:['ELDERLY']},priority:55,message:'노약자와 함께라면 돌계단과 보행 거리를 살펴야 해요.',actionSuggestion:'가까운 진입 동선과 휴식 장소를 먼저 확인하세요.',provenance:guidanceSource('126175')},
 ],
 'https://hapcheon.example/ontology#hapcheonVideoThemePark':[
  {id:'theme-park-general',trigger:{},priority:10,message:'야외 촬영 세트를 걸으며 둘러보는 관람 공간이에요.',actionSuggestion:'편한 신발과 물을 준비하세요.',provenance:guidanceSource('2469441')},
  {id:'theme-park-closing-soon',trigger:{operatingStates:['CLOSING_SOON'],minutesToCloseAtMost:60},priority:90,message:'관람 종료가 가까워지고 있어요.',actionSuggestion:'보고 싶은 촬영 세트를 먼저 둘러보세요.',provenance:guidanceSource('2469441'),realtimeRequired:true,maxAgeMinutes:20},
  {id:'theme-park-heat',trigger:{temperatureAtLeast:30},priority:85,message:'현재 기온이 높아 야외 관람 중 더울 수 있어요.',actionSuggestion:'물을 챙기고 그늘에서 자주 쉬세요.',provenance:guidanceSource('2469441'),realtimeRequired:true,maxAgeMinutes:30},
  {id:'theme-park-rain',trigger:{weather:['LIGHT_RAIN','RAIN','HEAVY_RAIN','THUNDERSTORM']},priority:95,message:'현재 비가 내려 야외 세트 관람이 불편할 수 있어요.',actionSuggestion:'우산과 미끄럼 방지 신발을 준비하세요.',provenance:guidanceSource('2469441'),realtimeRequired:true,maxAgeMinutes:30},
  {id:'theme-park-family',trigger:{companionTags:['CHILD','FAMILY']},priority:50,message:'아이와 함께 시대별 촬영 공간을 둘러보기 좋아요.',actionSuggestion:'걷는 거리와 쉬는 시간을 함께 계획하세요.',provenance:guidanceSource('2469441')},
 ],
};
export const HAPCHEON_MASTER_DATA:readonly HapcheonCandidateRecord[]=HAPCHEON_BASE_DATA.map(place=>({...place,operationalTips:guidanceByEntity[place.entityUri]||[]}));
export const HAPCHEON_MAP_PLACES=HAPCHEON_MASTER_DATA.filter(place=>place.actions.navigate);
