export type HapcheonSourceType='OFFICIAL_LOCAL_GOV'|'OFFICIAL_BUSINESS'|'KTO'|'OFFICIAL_MAP_LISTING';
export interface HapcheonSource{sourceType:HapcheonSourceType;sourceName:string;sourceUrl:string;verifiedAt:string}
export interface HapcheonCandidateRecord{entityUri:string;canonicalId:string;regionId:'hapcheon';displayName:{ko:string;en?:string};canonicalLabelKo:string;alternateLabels:readonly string[];category:string;tags:readonly string[];runtimeDataStatus:'PARTIAL'|'VERIFIED';entityType:string;accommodationType?:string;areaLabel?:string;address?:string;telephone?:string;website?:string;reservationUrl?:string;reservationAction?:{kind:'DIRECT_BOOKING';verificationStatus:'VERIFIED';verifiedUrl:string;sourceUrl:string;verifiedAt:string};publicInformationUrl?:string;latitude?:number;longitude?:number;coordinateSource?:HapcheonSource;description:string;source:HapcheonSource;lastVerifiedAt:string;actions:{detail?:{url:string};reserve?:{url:string;evidenceMode:'VERIFIED_DIRECT'};call?:{phone:string};navigate?:{latitude:number;longitude:number};website?:{url:string}}}
const verifiedAt='2026-08-19';
const kto=(id:string):HapcheonSource=>({sourceType:'KTO',sourceName:'한국관광공사 관광정보',sourceUrl:`https://data.visitkorea.or.kr/resource/${id}`,verifiedAt});
const county=(url:string,name='합천군 공식 정보'):HapcheonSource=>({sourceType:'OFFICIAL_LOCAL_GOV',sourceName:name,sourceUrl:url,verifiedAt});
const business=(url:string):HapcheonSource=>({sourceType:'OFFICIAL_BUSINESS',sourceName:'합천호 스마일펜션 공식 홈페이지',sourceUrl:url,verifiedAt});
type Input=Omit<HapcheonCandidateRecord,'regionId'|'lastVerifiedAt'|'canonicalLabelKo'|'alternateLabels'|'actions'> & {aliases?:string[]};
const record=(v:Input):HapcheonCandidateRecord=>{const actions:HapcheonCandidateRecord['actions']={detail:{url:v.publicInformationUrl||v.website||v.source.sourceUrl}};if(v.reservationAction?.kind==='DIRECT_BOOKING'&&v.reservationAction.verificationStatus==='VERIFIED'&&v.reservationAction.verifiedUrl===v.reservationUrl&&v.reservationUrl!==v.website)actions.reserve={url:v.reservationUrl!,evidenceMode:'VERIFIED_DIRECT'};if(v.telephone)actions.call={phone:v.telephone};if(v.latitude!==undefined&&v.longitude!==undefined)actions.navigate={latitude:v.latitude,longitude:v.longitude};if(v.website)actions.website={url:v.website};return{...v,regionId:'hapcheon',lastVerifiedAt:verifiedAt,canonicalLabelKo:v.displayName.ko,alternateLabels:v.aliases||[],actions}};
export const HAPCHEON_MASTER_DATA:readonly HapcheonCandidateRecord[]=[
 record({entityUri:'https://hapcheon.example/ontology#hapcheonLake',canonicalId:'hapcheon-lake',displayName:{ko:'합천호'},aliases:['합천 호수'],category:'HAPCHEON_LAKE',tags:['HAPCHEON_LAKE','TOURISM_NATURE','SCENIC_DRIVE','FAMILY_TRIP','REST'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 대병면 합천호수로 197',latitude:35.5305,longitude:128.0324,description:'합천댐으로 조성된 호수와 주변 경관을 만나는 합천의 대표 관광 권역입니다.',publicInformationUrl:'https://www.hc.go.kr/tour.web',source:county('https://www.hc.go.kr/tour.web','합천군 문화관광')}),
 record({entityUri:'https://hapcheon.example/ontology#haeinsa',canonicalId:'hapcheon-haeinsa',displayName:{ko:'해인사'},aliases:['합천 해인사'],category:'TOURISM_CULTURE',tags:['TOURISM_NATURE','FAMILY_TRIP'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 가야면 해인사길 122',telephone:'055-934-3000',latitude:35.8005687584,longitude:128.0971196597,description:'고려대장경판을 보관한 법보사찰입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/126175',source:kto('126175')}),
 record({entityUri:'https://hapcheon.example/ontology#hwangmaesanCountyPark',canonicalId:'hapcheon-hwangmaesan-county-park',displayName:{ko:'황매산 군립공원'},aliases:['황매산'],category:'TOURISM_NATURE',tags:['TOURISM_NATURE','SCENIC_DRIVE'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 가회면 황매산공원길 331',telephone:'055-930-4769',latitude:35.4822804994,longitude:127.9831021731,description:'철쭉과 억새 경관으로 알려진 합천의 군립공원입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/1622663',source:kto('1622663')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonGardenThemePark',canonicalId:'hapcheon-garden-theme-park',displayName:{ko:'합천 정원테마파크'},aliases:['합천영상테마파크','정원테마파크'],category:'TOURISM_CULTURE',tags:['TOURISM_NATURE','FAMILY_TRIP','ACTIVITY'],runtimeDataStatus:'VERIFIED',entityType:'ATTRACTION',address:'경상남도 합천군 용주면 합천호수로 777',telephone:'055-930-8633',latitude:35.553365758,longitude:128.0738450568,description:'합천영상테마파크와 연결된 정원·전시 관광시설입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/3060352',source:kto('3060352')}),
 record({entityUri:'https://hapcheon.example/ontology#cPark',canonicalId:'hapcheon-c-park',displayName:{ko:'씨파크'},aliases:['합천 씨파크'],category:'ACTIVITY',tags:['ACTIVITY','FAMILY_TRIP','CAFE'],runtimeDataStatus:'VERIFIED',entityType:'EXPERIENCE',address:'경상남도 합천군 합천호수로 525',latitude:35.5444275199,longitude:128.0537942855,description:'대병면에 위치한 체험·휴식 복합 공간입니다.',publicInformationUrl:'https://data.visitkorea.or.kr/resource/2992061',source:kto('2992061')}),
 record({entityUri:'https://hapcheon.example/ontology#cafeMotorrad',canonicalId:'hapcheon-cafe-motorrad',displayName:{ko:'카페 모토라드 합천'},aliases:['카페모토라드'],category:'CAFE',tags:['CAFE','SCENIC_DRIVE','REST'],runtimeDataStatus:'PARTIAL',entityType:'CAFE',address:'경상남도 합천군 대병면 합천호수로 525',telephone:'0507-1388-8883',latitude:35.5444275199,longitude:128.0537942855,website:'https://c-park.co.kr/cafe',description:'합천호 주요 차량 이동 경로의 카페입니다.',publicInformationUrl:'https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=186625',source:kto('2992061')}),
 record({entityUri:'https://hapcheon.example/ontology#cherryRoastery',canonicalId:'hapcheon-cherry-roastery',displayName:{ko:'커피볶는집체리'},aliases:['커피 볶는 집 체리'],category:'CAFE',tags:['CAFE','REST'],runtimeDataStatus:'PARTIAL',entityType:'CAFE',address:'경상남도 합천군 용주면 합천호수로 757',description:'합천영상테마파크 이동 경로에 등록된 카페입니다.',publicInformationUrl:'https://www.hc.go.kr/05752/05908/07350.web',source:county('https://www.hc.go.kr/05752/05908/07350.web','합천군 사업체 정보')}),
 record({entityUri:'https://hapcheon.example/ontology#cafeMoida',canonicalId:'hapcheon-cafe-moida',displayName:{ko:'카페모이다'},aliases:['카페 모이다'],category:'CAFE',tags:['CAFE','HAPCHEON_LAKE','REST'],runtimeDataStatus:'PARTIAL',entityType:'CAFE',address:'경상남도 합천군 대병면 서부로 1979-1',description:'합천호 권역 대병면에 등록된 카페입니다.',publicInformationUrl:'https://www.hc.go.kr/05752/05908/07350.web',source:county('https://www.hc.go.kr/05752/05908/07350.web','합천군 사업체 정보')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonLakeSmilePension',canonicalId:'hapcheon-lake-smile-pension',displayName:{ko:'합천호 스마일펜션'},aliases:['스마일펜션','합천호수뷰 스마일펜션'],category:'ACCOMMODATION',tags:['ACCOMMODATION','FAMILY_TRIP','HAPCHEON_LAKE','REST'],runtimeDataStatus:'VERIFIED',entityType:'ACCOMMODATION',accommodationType:'PENSION',areaLabel:'합천호 권역',address:'경상남도 합천군 대병면 회양관광단지길 61',telephone:'055-931-1638',website:'https://www.lakesmile.com/',reservationUrl:'https://rev.yapen.co.kr/',latitude:35.524485899856,longitude:128.01578179029,coordinateSource:{sourceType:'OFFICIAL_MAP_LISTING',sourceName:'지방행정인허가 숙박업 데이터·카카오/VWorld 지도',sourceUrl:'https://flg.purpleo.co.kr/view/26602',verifiedAt},description:'회양관광단지에서 합천호를 바라보는 가족·커플형 펜션입니다.',publicInformationUrl:'https://www.lakesmile.com/',source:business('https://www.lakesmile.com/')}),
 record({entityUri:'https://hapcheon.example/ontology#hapcheonLakeCharcoalGalbi',canonicalId:'hapcheon-lake-charcoal-galbi',displayName:{ko:'합천호 한우숯불갈비'},aliases:['합천호 숯불갈비'],category:'FOOD',tags:['FOOD','HAPCHEON_LAKE'],runtimeDataStatus:'PARTIAL',entityType:'RESTAURANT',telephone:'055-931-2995',description:'합천호 관광단지에서 펜션 공식 홈페이지가 안내하는 음식점입니다.',publicInformationUrl:'https://www.lakesmile.com/펜션서비스',source:business('https://www.lakesmile.com/펜션서비스')}),
 record({entityUri:'https://hapcheon.example/ontology#bukeoMaeul',canonicalId:'hapcheon-bukeo-maeul',displayName:{ko:'북어마을'},category:'FOOD',tags:['FOOD','HAPCHEON_LAKE'],runtimeDataStatus:'PARTIAL',entityType:'RESTAURANT',telephone:'055-934-0666',description:'합천호 관광단지에서 펜션 공식 홈페이지가 안내하는 음식점입니다.',publicInformationUrl:'https://www.lakesmile.com/펜션서비스',source:business('https://www.lakesmile.com/펜션서비스')}),
];
export const HAPCHEON_MAP_PLACES=HAPCHEON_MASTER_DATA.filter(place=>place.actions.navigate);
