import { ConciergeService, detectOutOfServiceDestination, isGuideExplanationQuestion } from './concierge.service';
import{GAJO_REGION_CONFIG}from'../region/region-config.service';
import { GuideService } from '../guide/guide.service';

describe('ConciergeService service-area handling', () => {
  it('answers approved Guide explanations without constructing or mutating travel context',async()=>{const context={createContext:jest.fn()},guide={approvedExplanation:jest.fn(()=>({status:'ANSWERED',intent:'REGIONAL_MANAGER',answer:'승인된 설명'}))},service=new ConciergeService(context as any,{}as any,{}as any,undefined,undefined,undefined,undefined,guide as any),answer:any=await service.chat({regionId:'okcheon',inputMode:'FREE_TEXT',rawMessage:'Regional Manager는 무슨 일을 하나요?'});expect(answer).toMatchObject({intentRoute:'GUIDE_EXPLANATION',recommendation:null,journeyContinuation:{preserveJourney:true}});expect(context.createContext).not.toHaveBeenCalled();expect(isGuideExplanationQuestion('지도에서 수승대 찾아줘')).toBe(false)});
  it.each(['T맵이랑 뭐가 달라?', '그냥 ChatGPT로 일정 짜면 안 돼?'])('answers active-trip objection %s as read-only Guide knowledge',async(rawMessage)=>{const context={createContext:jest.fn()},guideService=new GuideService(),service=new ConciergeService(context as any,{run:jest.fn()}as any,{label:jest.fn()}as any,undefined,undefined,undefined,undefined,guideService),answer:any=await service.chat({regionId:'okcheon',inputMode:'FREE_TEXT',rawMessage,mustVisitPlaces:[{entityId:'must-keep',requested:true}],explicitJourney:{multiDestination:true,requestedDestinations:[{entityId:'must-keep'}],sourceTurnId:'turn-7'}}as any);expect(answer).toMatchObject({intentRoute:'GUIDE_EXPLANATION',guideExplanation:{status:'ANSWERED',readOnly:true},recommendation:null,journeyContinuation:{preserveJourney:true}});expect(answer.intentRoute).not.toBe('PLACE_DISCOVERY');expect(context.createContext).not.toHaveBeenCalled();expect(answer.visitorMessage).toMatch(/여행을 계속할까요/)});
  it('recognizes the explicit Haeinsa destination without treating generic requests as external', () => {
    expect(detectOutOfServiceDestination('합천 해인사에 놀러 가고 싶어요.')).toEqual({ destination: '해인사', region: '합천' });
    expect(detectOutOfServiceDestination('엄마와 온천에 가고 싶어요.')).toBeUndefined();
    expect(detectOutOfServiceDestination('가조에서 해인사 이야기를 들었어요.')).toBeUndefined();
  });

  it('returns a normal visitor response and never runs Gajo recommendation for Haeinsa', async () => {
    const contextService = { createContext: jest.fn().mockResolvedValue({ context: { contextNo: 'RC-1', operationUri: 'gajo:operation', raw: { extractionDebug: { gatewayDecision: 'FALLBACK', status: 'PROVIDER_ERROR', errorCode: 'HTTP_429' } } }, evidence: [], firedRules: [] }) };
    const orchestrator = { run: jest.fn() };
    const service = new ConciergeService(contextService as any, orchestrator as any, { label: jest.fn() } as any);

    const result = await service.chat({ regionId:'gajo', inputMode: 'FREE_TEXT', rawMessage: '합천 해인사에 놀러 가고 싶어요.' });

    expect(result).toMatchObject({
      recommendation: null,
      domainResult: { status: 'OUT_OF_SERVICE_AREA', destination: '해인사', region: '합천' },
      visitorMessage: '현재는 가조 지역을 중심으로 안내하고 있어요. 가조에서 즐길 수 있는 장소를 찾아드릴까요?',
    });
    expect(orchestrator.run).not.toHaveBeenCalled();
  });
  it('returns direct discovery and does not enter the journey orchestrator',async()=>{const contextService={createContext:jest.fn().mockResolvedValue({context:{contextNo:'RC-D',operationUri:'gajo:operation',activityPreferences:['CAFE']},evidence:[],firedRules:[]})},orchestrator={run:jest.fn()},discovery={discover:jest.fn().mockResolvedValue({regionId:'hapcheon',category:'CAFE',entities:[{entityId:'lowful'}]})};const service=new ConciergeService(contextService as any,orchestrator as any,{label:jest.fn()}as any,{get:jest.fn(()=>GAJO_REGION_CONFIG),detectOutOfRegion:jest.fn()}as any,discovery as any);const result:any=await service.chat({regionId:'hapcheon',inputMode:'FREE_TEXT',rawMessage:'합천호 주변 전망 좋은 카페 알려줘'});expect(result).toMatchObject({intentRoute:'PLACE_DISCOVERY',recommendation:null,discovery:{category:'CAFE'}});expect(discovery.discover).toHaveBeenCalled();expect(orchestrator.run).not.toHaveBeenCalled()});
  it('invokes Journey Composer with the ambiguous Gajo concept and never category discovery',async()=>{const requested=[{entityId:'https://gajo-wellness.kr/semantic#gajoHotSpringArea',label:'가조온천',requestedLabel:'가조온천',resolved:false,requested:true,source:'SEMANTIC',entityType:'PLACE_CONCEPT'},{entityId:'https://gajo-wellness.kr/ontology#suseungdae',label:'수승대',requestedLabel:'수승대',resolved:false,requested:true,source:'SEMANTIC'}],contextService={createContext:jest.fn(async(input:any)=>({context:{contextNo:'RC-M',operationUri:'gajo:operation',regionId:'gajo',mustVisitPlaces:input.mustVisitPlaces},evidence:[],firedRules:[]}))},orchestrator={run:jest.fn(async(_id:string,_op:string,context:any)=>({tasks:[],executionLog:[],recommendation:{itinerary:{steps:context.mustVisitPlaces.map((x:any)=>({entityId:x.entityId,programLabel:x.label,requestedLabel:x.requestedLabel,actions:{}}))}}}))},discovery={resolveRequestedDestinations:jest.fn(async()=>requested),resolveReference:jest.fn(),discover:jest.fn()};const service=new ConciergeService(contextService as any,orchestrator as any,{label:jest.fn()}as any,{get:jest.fn(()=>GAJO_REGION_CONFIG),detectOutOfRegion:jest.fn()}as any,discovery as any);const result:any=await service.chat({regionId:'gajo',inputMode:'FREE_TEXT',rawMessage:'가조온천하고 수승대 가고 싶어요.'});expect(result).toMatchObject({intentRoute:'JOURNEY_PLAN',requestedDestinations:requested,visitorMessage:expect.stringContaining('가조온천과 수승대'),recommendation:{itinerary:{steps:[{programLabel:'가조온천',requestedLabel:'가조온천',actions:{}},{programLabel:'수승대',actions:{}}]}}});expect(contextService.createContext).toHaveBeenCalledWith(expect.objectContaining({mustVisitPlaces:requested}));expect(orchestrator.run).toHaveBeenCalled();expect(discovery.discover).not.toHaveBeenCalled();expect(JSON.stringify(result)).not.toMatch(/온천먹거리|다온 카페|항노화힐링랜드/)});

  it('keeps the exact structured journey for 어디부터 갈까 follow-up even without context reconstruction',async()=>{const requested=[{entityId:'https://gajo-wellness.kr/semantic#gajoHotSpringArea',label:'가조온천',requestedLabel:'가조온천',resolved:false,requested:true,source:'SEMANTIC'},{entityId:'https://gajo-wellness.kr/ontology#suseungdae',label:'수승대',requestedLabel:'수승대',resolved:false,requested:true,source:'SEMANTIC'}],contextService={createContext:jest.fn(async(input:any)=>({context:{contextNo:'RC-F',operationUri:'gajo:operation',regionId:'gajo',mustVisitPlaces:input.mustVisitPlaces},evidence:[],firedRules:[]}))},orchestrator={run:jest.fn(async(_id:string,_op:string,context:any)=>({tasks:[],executionLog:[],recommendation:{itinerary:{steps:context.mustVisitPlaces.map((x:any)=>({programLabel:x.label,requestedLabel:x.requestedLabel,actions:{}}))}}}))},discovery={resolveReference:jest.fn(),discover:jest.fn()};const service=new ConciergeService(contextService as any,orchestrator as any,{label:jest.fn()}as any,{get:jest.fn(()=>GAJO_REGION_CONFIG),detectOutOfRegion:jest.fn()}as any,discovery as any);const result:any=await service.chat({regionId:'gajo',inputMode:'FREE_TEXT',rawMessage:'어디부터 갈까?',isFollowup:true,explicitJourney:{requestedDestinations:requested as any,multiDestination:true,sourceTurnId:'turn-1'}});expect(contextService.createContext).toHaveBeenCalledWith(expect.objectContaining({mustVisitPlaces:requested}));expect(result).toMatchObject({intentRoute:'REPLAN',requestedDestinations:requested,recommendation:{itinerary:{steps:[{programLabel:'가조온천'},{programLabel:'수승대'}]}}});expect(result.visitorMessage).toContain('거리순 계산은 어렵습니다');expect(JSON.stringify(result)).not.toMatch(/다온 카페|항노화힐링랜드|백두산천지온천|관광과 체험을 둘러본 뒤/)});
});
