import { PlaceDiscoveryService } from './place-discovery.service';
import { routeNaturalLanguageIntent } from './intent-routing';
import { normalizeNearbyCategory } from '../nearby/nearby.service';

const place=(entityUri:string,canonicalLabelKo:string,entityType:string,category:string,latitude:number,longitude:number,extra:any={})=>({entityUri,canonicalLabelKo,alternateLabels:[],entityType,category,tags:[category],latitude,longitude,runtimeDataStatus:'VERIFIED',actions:{navigate:{latitude,longitude}},...extra});
const pension=place('pension','합천호 스마일펜션','ACCOMMODATION','ACCOMMODATION',35.52448,128.01578,{alternateLabels:['스마일펜션']});
const lowful=place('lowful','로우풀','CAFE','CAFE',35.526,128.018);
const lake=place('lake','합천호','ATTRACTION','TOURISM_NATURE',35.53,128.032);
const sauna=place('sauna','호수황토찜질방','WELLNESS','HOT_SPRING_WELLNESS',35.531,128.033);
const sauna2=place('sauna2','합천호청정사우나','WELLNESS','SAUNA',35.532,128.034);
const contamination=place('aj-pension','에이제펜션','ACCOMMODATION','ACCOMMODATION',35.5311,128.0331);
const food1=place('food1','북어마을','RESTAURANT','FOOD',35.533,128.035);
const food2=place('food2','호반식당','RESTAURANT','FOOD',35.535,128.037);
const records=[pension,lowful,lake,sauna,sauna2,contamination,food1,food2];
const regional={effectiveDataset:jest.fn(async(regionId:string)=>({regionId,records:regionId==='hapcheon'?records:[]}))};
const service=new PlaceDiscoveryService(regional as any);
const anchor=(row:any,sourceTurnId:string)=>({entityId:row.entityUri,regionId:'hapcheon',label:row.canonicalLabelKo,entityType:row.entityType,category:row.category,latitude:row.latitude,longitude:row.longitude,source:'RDM',sourceTurnId,role:'RESULT'});

describe('follow-up intent and discovery context',()=>{
  it('completes the six-turn cafe attraction sauna food distance alternative conversation',async()=>{const t1:any=await service.discover('hapcheon','CAFE','스마일펜션 근처 카페?',{turnId:'t1'});expect(t1.entities[0].entityId).toBe('lowful');const t2:any=await service.discover('hapcheon','TOURISM_NATURE','그 주변 볼 만한 곳?',{turnId:'t2',conversationalAnchor:anchor(lowful,'t1')});const attraction=records.find(x=>x.entityUri===t2.entities[0].entityId)!;const t3:any=await service.discover('hapcheon','HOT_SPRING_WELLNESS','그 근처 사우나는?',{turnId:'t3',conversationalAnchor:anchor(attraction,'t2')});expect(t3.entities.every((x:any)=>x.entityId!=='aj-pension')).toBe(true);const saunaResult=records.find(x=>x.entityUri===t3.entities[0].entityId)!;const t4:any=await service.discover('hapcheon','FOOD','그 근처 밥집은?',{turnId:'t4',conversationalAnchor:anchor(saunaResult,'t3')});const primary=t4.entities[0],context={regionId:'hapcheon',anchor:{entityId:saunaResult.entityUri,source:'RDM'},targetCategory:'FOOD',relation:'NEARBY',currentResult:{entityId:primary.entityId,source:'RDM'},shownEntityIds:[primary.entityId],sourceTurnId:'t4'};expect(routeNaturalLanguageIntent({rawMessage:'거긴 멀어?',inputMode:'FREE_TEXT',isFollowup:true}).intentRoute).toBe('DISTANCE_INFO');expect(await service.distanceInfo('hapcheon',{discoveryContext:context})).toMatchObject({status:'RESOLVED',toEntityId:primary.entityId});const t6:any=await service.discover('hapcheon','FOOD','다른 데는?',{turnId:'t6',discoveryAlternative:true,discoveryContext:context});expect(t6.anchorEntityId).toBe(saunaResult.entityUri);expect(t6.entities[0].entityId).not.toBe(primary.entityId)});
  it.each(['거긴 멀어?','얼마나 멀어?'])('%s routes to runtime distance information',rawMessage=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT',isFollowup:true}).intentRoute).toBe('DISTANCE_INFO'));
  it('calculates distance from verified discovery references rather than hardcoding it',async()=>{const result:any=await service.distanceInfo('hapcheon',{discoveryContext:{regionId:'hapcheon',anchor:{entityId:'sauna',source:'RDM'},currentResult:{entityId:'food1',source:'RDM'}}});expect(result).toMatchObject({status:'RESOLVED',fromEntityId:'sauna',toEntityId:'food1',calculation:'RUNTIME_HAVERSINE'});expect(result.distanceMeters).toBeGreaterThan(0);expect(result.distanceMeters).not.toBe(301)});
  it('asks for clarification when the relation origin is unavailable',async()=>expect(await service.distanceInfo('hapcheon',{})).toMatchObject({status:'NEEDS_CLARIFICATION'}));
  it('keeps anchor and FOOD category while excluding the current result',async()=>{const route:any=routeNaturalLanguageIntent({rawMessage:'다른 데는?',inputMode:'FREE_TEXT',isFollowup:true,discoveryCategoryHint:'FOOD'});expect(route).toMatchObject({intentRoute:'PLACE_DISCOVERY',category:'FOOD',alternative:true});const result:any=await service.discover('hapcheon','FOOD','다른 데는?',{turnId:'t6',discoveryAlternative:true,discoveryContext:{regionId:'hapcheon',anchor:{entityId:'sauna',label:'호수황토찜질방',source:'RDM'},targetCategory:'FOOD',relation:'NEARBY',currentResult:{entityId:'food1'},shownEntityIds:['food1'],sourceTurnId:'t4'}});expect(result).toMatchObject({anchorEntityId:'sauna',category:'FOOD',referenceResolution:{mode:'DISCOVERY_CONTEXT',sourceTurnId:'t4'}});expect(result.entities[0].entityId).toBe('food2');expect(result.entities.map((x:any)=>x.entityId)).not.toContain('food1')});
  it('lets an explicit category and explicit anchor override old context',async()=>{expect(routeNaturalLanguageIntent({rawMessage:'아니, 카페는?',inputMode:'FREE_TEXT',isFollowup:true,discoveryCategoryHint:'FOOD'})).toMatchObject({intentRoute:'PLACE_DISCOVERY',category:'CAFE'});const result:any=await service.discover('hapcheon','FOOD','스마일펜션 근처 식당은?',{discoveryAlternative:true,discoveryContext:{regionId:'hapcheon',anchor:{entityId:'sauna'},shownEntityIds:[],sourceTurnId:'old'}});expect(result.anchorEntityId).toBe('pension')});
  it('routes an explicit category override even when classified as a fresh category request',()=>expect(routeNaturalLanguageIntent({rawMessage:'아니, 카페는?',inputMode:'FREE_TEXT',isFollowup:false,discoveryCategoryHint:'FOOD'})).toMatchObject({intentRoute:'PLACE_DISCOVERY',category:'CAFE'}));
  it('rejects cross-region discovery context',async()=>{const result:any=await service.discover('hapcheon','FOOD','다른 데는?',{discoveryAlternative:true,discoveryContext:{regionId:'okcheon',anchor:{entityId:'sauna'},shownEntityIds:['food1']}});expect(result.anchorEntityId).toBeUndefined()});
});

describe('strict target type eligibility',()=>{
  it('returns exactly the eligible sauna/bath entities and excludes the observed pension contamination',async()=>{const result:any=await service.discover('hapcheon','HOT_SPRING_WELLNESS','스마일펜션 근처 사우나 있어?',{});expect(new Set(result.entities.map((x:any)=>x.programLabel))).toEqual(new Set(['호수황토찜질방','합천호청정사우나']));expect(result.entities.map((x:any)=>x.programLabel)).not.toContain('에이제펜션')});
  it('does not let an EXKO-related pension bypass sauna eligibility',async()=>{const exko={enabled:()=>true,semanticCandidates:()=>({resolved:true,alignmentStatus:'ALIGNED',neighborCount:1,regionalEntityIds:['aj-pension'],evidence:[{subject:'pension',predicate:'related',object:'aj-pension'}]})};const result:any=await new PlaceDiscoveryService(regional as any,exko as any).discover('hapcheon','HOT_SPRING_WELLNESS','스마일펜션 근처 사우나?',{});expect(result.entities.map((x:any)=>x.entityId)).not.toContain('aj-pension')});
  it.each([['목욕탕','HOT_SPRING_WELLNESS'],['사우나','HOT_SPRING_WELLNESS'],['찜질방','HOT_SPRING_WELLNESS'],['온천','HOT_SPRING_WELLNESS'],['SPA','HOT_SPRING_WELLNESS'],['에이제펜션','LODGING'],['호텔','LODGING'],['음식점','FOOD'],['카페','CAFE']] as const)('normalizes %s without category contamination',(name,expected)=>expect(normalizeNearbyCategory(name,'', '', 'HOT_SPRING_WELLNESS')).toBe(expected));
});
