import{discoveryCategory,routeNaturalLanguageIntent}from'./intent-routing';
describe('natural-language intent routing',()=>{it.each([['합천호 주변 전망 좋은 카페 알려줘','PLACE_DISCOVERY','CAFE'],['스마일펜션 근처 카페','PLACE_DISCOVERY','CAFE'],['부모님과 가기 좋은 카페','PLACE_DISCOVERY','CAFE'],['주차 편한 식당','PLACE_DISCOVERY','FOOD'],['아이와 갈 실내 체험','PLACE_DISCOVERY','ACTIVITY'],['지금 저녁 먹을 곳','IMMEDIATE_NOW','FOOD'],['현재 위치 근처 카페','IMMEDIATE_NOW','CAFE'],['1박2일 가족여행 짜줘','JOURNEY_PLAN',undefined],['해인사 보고 점심 먹고 카페 갔다가 펜션 들어가고 싶어요','JOURNEY_PLAN','LODGING'],['내일 하루 일정 만들어줘','JOURNEY_PLAN',undefined]])('%s routes to %s',(rawMessage,intentRoute,category)=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT'})).toEqual({intentRoute,category}));it.each(['부모님이 피곤해하세요','비가 와요','펜션으로 먼저 가고 싶어요'])('follow-up %s remains REPLAN',rawMessage=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT',isFollowup:true}).intentRoute).toBe('REPLAN'));it('does not reinterpret structured input as discovery',()=>expect(routeNaturalLanguageIntent({rawMessage:'근처 카페',inputMode:'STRUCTURED'}).intentRoute).toBe('JOURNEY_PLAN'));it('extracts restaurant intent without requiring a journey',()=>expect(discoveryCategory('합천호 주변 저녁 먹을 곳')).toBe('FOOD'))});

describe('explicit multi-destination routing',()=>{
  it.each([['가조온천하고 수승대 가고 싶어요.',['가조온천','수승대']],['해인사하고 황매산 가고 싶어요.',['해인사','황매산']],['A 갔다가 B 갈래.',['A','B']],['A랑 B 둘 다 보고 싶어요.',['A','B']]])('%s is entity-first journey intent',(rawMessage,explicitDestinations)=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT'})).toEqual({intentRoute:'JOURNEY_PLAN',category:undefined,multiDestination:true,explicitDestinations}));
  it.each([['가조온천 근처 밥집은?','PLACE_DISCOVERY','FOOD'],['가조온천 근처 카페?','PLACE_DISCOVERY','CAFE']])('keeps nearby regression %s',(rawMessage,intentRoute,category)=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT'})).toMatchObject({intentRoute,category}));
  it.each([['가조온천에서 숙박하고 싶어요.','LODGING'],['가조온천에서 목욕하고 싶어요.','HOT_SPRING_WELLNESS'],['호텔가조온천에서 자고 싶어요.','LODGING']])('contextually classifies %s',(rawMessage,category)=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT'})).toMatchObject({intentRoute:'PLACE_DISCOVERY',category}));
  it.each(['어디부터 갈까?','시간이 두 시간밖에 없어.','수승대는 빼줘.','순서 바꿔줘.'])('keeps journey follow-up %s in replan boundaries',rawMessage=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT',isFollowup:true}).intentRoute).toBe('REPLAN'));
});
describe('search fallback intent routing',()=>{it('routes a nearby sauna request to discovery even during a conversation',()=>expect(routeNaturalLanguageIntent({rawMessage:'스마일펜션 바로 근처에 사우나 있어?',inputMode:'FREE_TEXT',isFollowup:true})).toEqual({intentRoute:'PLACE_DISCOVERY',category:'HOT_SPRING_WELLNESS'}));it('continues from a search result to food discovery',()=>expect(routeNaturalLanguageIntent({rawMessage:'그 근처 밥집은?',inputMode:'FREE_TEXT',isFollowup:true})).toEqual({intentRoute:'PLACE_DISCOVERY',category:'FOOD'}))});
describe('first-time visitor routing',()=>{it.each(['처음 왔어요. 꼭 가볼 곳 알려주세요.','여기 처음인데 어디부터 볼까요?','대표 관광지를 알려줘','어디가 제일 유명해요?','필수 코스 추천해줘'])('%s uses the shared welcome intent',rawMessage=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT'})).toMatchObject({intentRoute:'FIRST_TIME_VISITOR',category:'TOURISM_NATURE'}))});
