import { PlaceDiscoveryService } from './place-discovery.service';
import { routeNaturalLanguageIntent } from './intent-routing';

const pension={entityUri:'pension',canonicalLabelKo:'합천호 스마일펜션',alternateLabels:['스마일펜션'],entityType:'ACCOMMODATION',category:'LODGING',latitude:35.524,longitude:128.015};
const lowful={entityUri:'lowful',canonicalLabelKo:'로우풀',alternateLabels:[],entityType:'CAFE',category:'CAFE',tags:['CAFE'],latitude:35.525,longitude:128.018,actions:{navigate:{latitude:35.525,longitude:128.018}}};
const haeinsa={entityUri:'haeinsa',canonicalLabelKo:'해인사',alternateLabels:[],entityType:'ATTRACTION',category:'TOURISM_NATURE',latitude:35.8,longitude:128.09};
const attraction={entityUri:'lake',canonicalLabelKo:'합천호',alternateLabels:[],entityType:'ATTRACTION',category:'TOURISM_NATURE',latitude:35.53,longitude:128.03};
const food={entityUri:'food',canonicalLabelKo:'북어마을',alternateLabels:[],entityType:'RESTAURANT',category:'FOOD',latitude:35.54,longitude:128.04};
const lodging={entityUri:'lodging',canonicalLabelKo:'검증 숙소',alternateLabels:[],entityType:'ACCOMMODATION',category:'LODGING',latitude:35.79,longitude:128.08};
const records=[pension,lowful,haeinsa,attraction,food,lodging],regional={effectiveDataset:jest.fn(async(region:string)=>({regionId:region,records:region==='hapcheon'?records:[]}))},service=new PlaceDiscoveryService(regional as any);
const anchor=(entity:any,sourceTurnId:string)=>({entityId:entity.entityUri,regionId:'hapcheon',label:entity.canonicalLabelKo,entityType:entity.entityType,category:entity.category,latitude:entity.latitude,longitude:entity.longitude,sourceTurnId,role:'RESULT'});

describe('multi-turn conversational anchor continuity',()=>{
  it('traverses Smile Pension to Lowful to a nearby attraction without Journey Composer',async()=>{const first:any=await service.discover('hapcheon','CAFE','스마일펜션에 묵는데 주변에서 차 마실 만한 곳 있어?',{turnId:'t1'});expect(first.entities[0].entityId).toBe('lowful');const text='그럼 거기 주변에 볼 만한 곳은?',route=routeNaturalLanguageIntent({rawMessage:text,inputMode:'FREE_TEXT',isFollowup:true});expect(route).toEqual({intentRoute:'PLACE_DISCOVERY',category:'TOURISM_NATURE'});const second:any=await service.discover('hapcheon','TOURISM_NATURE',text,{turnId:'t2',conversationalAnchor:anchor(lowful,'t1')});expect(second).toMatchObject({anchorEntityId:'lowful',referenceResolution:{mode:'CONVERSATIONAL_REFERENCE',sourceTurnId:'t1',currentTurnId:'t2'}});expect(second.entities[0].entityId).not.toBe('lowful')});
  it('uses the current primary result for conservative three-turn traversal',async()=>{const second:any=await service.discover('hapcheon','TOURISM_NATURE','거기 주변 볼 만한 곳',{conversationalAnchor:anchor(lowful,'t1')}),primary=second.entities[0],thirdText='그중 가까운 데서 밥 먹을 곳은?',third:any=await service.discover('hapcheon','FOOD',thirdText,{turnId:'t3',conversationalAnchor:anchor({entityUri:primary.entityId,canonicalLabelKo:primary.programLabel,entityType:primary.entityType,category:primary.category,latitude:primary.latitude,longitude:primary.longitude},'t2')});expect(routeNaturalLanguageIntent({rawMessage:thirdText,inputMode:'FREE_TEXT',isFollowup:true}).intentRoute).toBe('PLACE_DISCOVERY');expect(third.referenceResolution).toMatchObject({mode:'CONVERSATIONAL_REFERENCE',sourceTurnId:'t2'});expect(third.entities[0].entityId).toBe('food')});
  it('explicit named entities override the prior conversational reference',async()=>{const result:any=await service.discover('hapcheon','CAFE','그럼 해인사 주변 카페는?',{conversationalAnchor:anchor(lowful,'t1')});expect(result.referenceResolution.mode).toBe('EXPLICIT_ENTITY');expect(result.anchorEntityId).toBe('haeinsa')});
  it('knowledge subject becomes the next structured reference instead of stale Lowful',async()=>{const subject=await service.resolveReference('hapcheon','해인사는 왜 유명해?');expect(subject?.entityId).toBe('haeinsa');const next:any=await service.discover('hapcheon','CAFE','그럼 거기 주변 카페는?',{conversationalAnchor:{...subject,sourceTurnId:'knowledge',role:'SUBJECT'}});expect(next.anchorEntityId).toBe('haeinsa');expect(next.anchorEntityId).not.toBe('lowful')});
  it('supports typed relational forms for food and lodging',()=>{expect(routeNaturalLanguageIntent({rawMessage:'그 근처 밥집은?',inputMode:'FREE_TEXT',isFollowup:true})).toEqual({intentRoute:'PLACE_DISCOVERY',category:'FOOD'});expect(routeNaturalLanguageIntent({rawMessage:'거기서 숙소는 가까워?',inputMode:'FREE_TEXT',isFollowup:true})).toEqual({intentRoute:'PLACE_DISCOVERY',category:'LODGING'})});
  it('rejects a cross-region conversational anchor',async()=>{const result:any=await service.discover('okcheon','CAFE','거기 주변 카페',{conversationalAnchor:anchor(lowful,'t1')});expect(result.anchorEntityId).toBeUndefined();expect(result.entities).toEqual([])});
});
