import{Injectable,Optional}from'@nestjs/common';import{RegionalDataService}from'../regional-data/regional-data.service';import type{DiscoveryCategory}from'./intent-routing';
const CATEGORY_MATCH:Record<DiscoveryCategory,(record:any)=>boolean>={CAFE:r=>r.entityType==='CAFE'||r.category==='CAFE',FOOD:r=>r.entityType==='RESTAURANT'||r.category==='FOOD',LODGING:r=>r.entityType==='ACCOMMODATION'||/LODGING|ACCOMMODATION/.test(r.category),ACTIVITY:r=>/EXPERIENCE|ACTIVITY/.test(`${r.entityType} ${r.category}`),TOURISM_NATURE:r=>/ATTRACTION|TOURISM/.test(`${r.entityType} ${r.category}`),CONVENIENCE:r=>/CONVENIENCE/.test(`${r.entityType} ${r.category}`)};
@Injectable()export class PlaceDiscoveryService{constructor(@Optional()private readonly regionalData?:RegionalDataService){}
 async discover(regionId:string,category:DiscoveryCategory,message:string,context:any){const dataset=await this.regionalData?.effectiveDataset(regionId);if(!dataset)return{regionId,category,entities:[]};const requested=new Set<string>(context.activityPreferences||[]);if(/합천호|호수|전망|풍경/.test(message))requested.add('HAPCHEON_LAKE');if(/쉬|휴식|편안|부모님/.test(message))requested.add('REST');requested.add(category);
 const anchor=this.anchor(dataset.records,message),origin=this.origin(context)||this.coordinates(anchor);const ranked=dataset.records.filter(CATEGORY_MATCH[category]).map(record=>{const matched=(record.tags||[]).filter((tag:string)=>requested.has(tag));const distanceMeters=this.distance(origin,this.coordinates(record));const score=100+matched.length*20+(Number.isFinite(record.latitude)&&Number.isFinite(record.longitude)?1:0)+(distanceMeters===undefined?0:Math.max(0,10-distanceMeters/1000));return{record,matched,distanceMeters,score}}).sort((a,b)=>b.score-a.score||(a.distanceMeters??Infinity)-(b.distanceMeters??Infinity)||a.record.entityUri.localeCompare(b.record.entityUri));
 return{regionId,category,anchorEntityId:anchor?.entityUri,entities:ranked.map(({record,matched,distanceMeters,score},index)=>({entityId:record.entityUri,regionId,order:index+1,programUri:record.entityUri,programLabel:record.canonicalLabelKo,facilityUri:record.entityUri,facilityLabel:record.canonicalLabelKo,entityType:record.entityType,category:record.category,areaLabel:record.areaLabel,description:record.description,address:record.address,telephone:record.telephone,website:record.website,reservationUrl:record.reservationUrl,latitude:record.latitude,longitude:record.longitude,actions:record.actions,source:record.source,lastVerifiedAt:record.lastVerifiedAt,distanceMeters,reasons:[...matched.map((tag:string)=>tag==='HAPCHEON_LAKE'?'합천호 관련 맥락':tag==='REST'?'휴식 맥락':tag===category?'요청한 장소 유형':tag),...(distanceMeters!==undefined?[`검증 좌표 기준 ${distanceMeters}m`]:[])],score}))}}
 private anchor(records:readonly any[],message:string){const normalized=message.replace(/\s/g,'');return records.filter(record=>[record.canonicalLabelKo,...(record.alternateLabels||[])].some((label:string)=>{const value=label.replace(/\s/g,'');return normalized.includes(value)||normalized.includes(value.replace(/^합천호/,''))})).sort((a,b)=>b.canonicalLabelKo.length-a.canonicalLabelKo.length)[0]}
 private origin(context:any){return Number.isFinite(context.latitude)&&Number.isFinite(context.longitude)?{latitude:context.latitude,longitude:context.longitude}:undefined}
 private coordinates(record:any){return Number.isFinite(record?.latitude)&&Number.isFinite(record?.longitude)?{latitude:record.latitude,longitude:record.longitude}:undefined}
 private distance(a?:{latitude:number;longitude:number},b?:{latitude:number;longitude:number}){if(!a||!b)return undefined;const rad=(v:number)=>v*Math.PI/180,dLat=rad(b.latitude-a.latitude),dLng=rad(b.longitude-a.longitude),h=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLng/2)**2;return Math.round(6371000*2*Math.asin(Math.sqrt(h)))} }
