import { PlaceDiscoveryService } from './place-discovery.service';
import { routeNaturalLanguageIntent } from './intent-routing';

const pension={entityUri:'pension',canonicalLabelKo:'합천호 스마일펜션',alternateLabels:['스마일펜션'],entityType:'ACCOMMODATION',category:'ACCOMMODATION',tags:[],latitude:35.52448,longitude:128.01578,runtimeDataStatus:'VERIFIED',actions:{navigate:{latitude:35.52448,longitude:128.01578}}};
const food={entityUri:'food',canonicalLabelKo:'대병식당',alternateLabels:[],entityType:'RESTAURANT',category:'FOOD',tags:['FOOD'],latitude:35.526,longitude:128.017,runtimeDataStatus:'VERIFIED',actions:{navigate:{latitude:35.526,longitude:128.017}}};
const dataset={effectiveDataset:jest.fn(async(regionId:string)=>({regionId,records:regionId==='hapcheon'?[pension,food]:[]}))};
const searched={id:'sauna-1',name:'합천호 청정사우나',category:'HOT_SPRING_WELLNESS',providerCategoryName:'가정,생활 > 목욕탕,사우나',address:'경남 합천군 대병면 회양관광단지길 79-3',phone:'055-933-8877',lat:35.525,lng:128.016,distanceMeters:100,placeUrl:'https://place.map.kakao.com/sauna-1'};
const nearby={search:jest.fn(async()=>[searched])};

describe('search-to-action continuity',()=>{
  it('keeps an unmatched search discovery structured but operationally unverified',async()=>{const service=new PlaceDiscoveryService(dataset as any,undefined,nearby as any);const first:any=await service.discover('hapcheon','HOT_SPRING_WELLNESS','스마일펜션 바로 근처에 사우나 있어?',{turnId:'t1'});expect(first).toMatchObject({anchorEntityId:'pension',anchorLabel:'합천호 스마일펜션',searchFallback:{used:true,source:'KAKAO_LOCAL'},entities:[{entityId:'search:hapcheon:sauna-1',programLabel:'합천호 청정사우나',actions:{},operationalEvidence:{source:'SEARCH',verificationStatus:'UNVERIFIED',navigationAvailable:false,tripEligible:false},candidateEvidence:{sourceType:'KAKAO_LOCAL',observedPhone:'055-933-8877'}}]});expect(first.entities[0].telephone).toBeUndefined();expect(routeNaturalLanguageIntent({rawMessage:'스마일펜션 바로 근처에 사우나 있어?',inputMode:'FREE_TEXT'}).intentRoute).toBe('PLACE_DISCOVERY');
    const anchor={entityId:first.entities[0].entityId,regionId:'hapcheon',label:first.entities[0].programLabel,entityType:first.entities[0].entityType,category:first.entities[0].category,latitude:first.entities[0].latitude,longitude:first.entities[0].longitude,source:'SEARCH',sourceTurnId:'t1',role:'RESULT'};
    const second:any=await service.discover('hapcheon','FOOD','그 근처 밥집은?',{turnId:'t2',conversationalAnchor:anchor});expect(second).toMatchObject({anchorEntityId:'search:hapcheon:sauna-1',anchorLabel:'합천호 청정사우나',referenceResolution:{mode:'CONVERSATIONAL_REFERENCE',sourceTurnId:'t1',currentTurnId:'t2'},entities:[{entityId:'food'}]});expect(routeNaturalLanguageIntent({rawMessage:'그 근처 밥집은?',inputMode:'FREE_TEXT',isFollowup:true})).toEqual({intentRoute:'PLACE_DISCOVERY',category:'FOOD'});
  });
  it('rejects a search anchor from another region',async()=>{const service=new PlaceDiscoveryService(dataset as any,undefined,nearby as any);const result:any=await service.discover('hapcheon','FOOD','그 근처 밥집은?',{conversationalAnchor:{entityId:'search:okcheon:x',regionId:'okcheon',label:'다른 지역',latitude:36,longitude:127,source:'SEARCH',sourceTurnId:'old'}});expect(result.anchorEntityId).toBeUndefined()});
  it('prefers canonical RDM facts and actions without invoking search',async()=>{const sauna={...food,entityUri:'sauna',canonicalLabelKo:'합천호 청정사우나',entityType:'WELLNESS',category:'HOT_SPRING_WELLNESS',telephone:'055-000-0000',actions:{call:{phone:'055-000-0000'},navigate:{latitude:35.525,longitude:128.016}}};const regional={effectiveDataset:jest.fn(async()=>({regionId:'hapcheon',records:[pension,sauna]}))},localNearby={search:jest.fn()};const service=new PlaceDiscoveryService(regional as any,undefined,localNearby as any);const result:any=await service.discover('hapcheon','HOT_SPRING_WELLNESS','스마일펜션 근처 사우나',{turnId:'t1'});expect(result.entities[0]).toMatchObject({entityId:'sauna',telephone:'055-000-0000',actions:sauna.actions,operationalEvidence:{source:'RDM',tripEligible:true}});expect(localNearby.search).not.toHaveBeenCalled()});
});
