import { routeNaturalLanguageIntent } from './intent-routing';
import { PlaceDiscoveryService } from './place-discovery.service';
import { ExkoSemanticAdapter } from '../exko-semantic/exko-semantic.service';
import { ConciergeService } from './concierge.service';
import { GAJO_REGION_CONFIG } from '../region/region-config.service';

const golden='스마일펜션에 묵는데 주변에서 차 마실 만한 곳 있어?';
const pension={entityUri:'https://hapcheon.example/ontology#hapcheonLakeSmilePension',canonicalLabelKo:'합천호 스마일펜션',alternateLabels:['스마일펜션'],entityType:'ACCOMMODATION',category:'LODGING',runtimeDataStatus:'VERIFIED',latitude:35.524485899856,longitude:128.01578179029,actions:{navigate:{latitude:35.524485899856,longitude:128.01578179029}}};
const lowful={entityUri:'urn:regional:hapcheon:lowful',canonicalLabelKo:'로우풀',alternateLabels:['카페 로우풀'],entityType:'CAFE',category:'CAFE',tags:['CAFE','REST'],runtimeDataStatus:'VERIFIED',verificationStatus:'VERIFIED',latitude:35.525488,longitude:128.018877,telephone:'0507-1333-2434',source:{sourceType:'KTO'},actions:{call:{phone:'0507-1333-2434'},navigate:{latitude:35.525488,longitude:128.018877}}};
const restaurant={entityUri:'urn:regional:hapcheon:food',canonicalLabelKo:'북어마을',alternateLabels:[],entityType:'RESTAURANT',category:'FOOD',verificationStatus:'VERIFIED'};
const attraction={entityUri:'https://hapcheon.example/ontology#hapcheonLake',canonicalLabelKo:'합천호',alternateLabels:[],entityType:'ATTRACTION',category:'TOURISM_NATURE',verificationStatus:'VERIFIED'};
const regional={effectiveDataset:jest.fn(async(region:string)=>({regionId:region,records:region==='hapcheon'?[pension,lowful,restaurant,attraction]:[]}))};
const enabled=new ExkoSemanticAdapter({get:()=> 'true'}as any),disabled=new ExkoSemanticAdapter({get:(_k:string,f:string)=>f}as any);

describe('semantic anchor and target routing',()=>{
  it('routes the exact golden utterance to cafe discovery, not lodging or journey composition',()=>expect(routeNaturalLanguageIntent({rawMessage:golden,inputMode:'FREE_TEXT'})).toEqual({intentRoute:'PLACE_DISCOVERY',category:'CAFE'}));
  it('bypasses Journey Composer for the golden query',async()=>{const context={createContext:jest.fn().mockResolvedValue({context:{contextNo:'golden',operationUri:'operation'},evidence:[],firedRules:[]})},orchestrator={run:jest.fn()},discovery={discover:jest.fn().mockResolvedValue({regionId:'hapcheon',category:'CAFE',anchorEntityId:pension.entityUri,entities:[lowful]})},service=new ConciergeService(context as any,orchestrator as any,{}as any,{get:()=>GAJO_REGION_CONFIG,detectOutOfRegion:()=>undefined}as any,discovery as any),result:any=await service.chat({regionId:'hapcheon',inputMode:'FREE_TEXT',rawMessage:golden});expect(result).toMatchObject({intentRoute:'PLACE_DISCOVERY',recommendation:null,discovery:{category:'CAFE',anchorEntityId:pension.entityUri}});expect(discovery.discover).toHaveBeenCalledWith('hapcheon','CAFE',golden,expect.anything());expect(orchestrator.run).not.toHaveBeenCalled()});
  it.each([
    ['스마일펜션 근처 카페 알려줘.','PLACE_DISCOVERY','CAFE'],
    ['스마일펜션 근처에서 밥 먹을 곳 있어?','PLACE_DISCOVERY','FOOD'],
    ['로우풀 주변에 볼 만한 곳 있어?','PLACE_DISCOVERY','TOURISM_NATURE'],
  ])('%s resolves target semantics', (rawMessage,intentRoute,category)=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT'})).toEqual({intentRoute,category}));
  it.each(['스마일펜션은 어떤 곳이야?','스마일펜션 예약하고 싶어.'])('%s is about the pension itself, not nearby discovery',rawMessage=>expect(routeNaturalLanguageIntent({rawMessage,inputMode:'FREE_TEXT'}).intentRoute).not.toBe('PLACE_DISCOVERY'));
  it('separates the pension anchor from cafe candidates and computes distance at runtime',async()=>{const result:any=await new PlaceDiscoveryService(regional as any,enabled).discover('hapcheon','CAFE',golden,{});expect(result).toMatchObject({anchorEntityId:pension.entityUri,anchorLabel:'합천호 스마일펜션',relation:'NEARBY',targetCategory:'CAFE'});expect(result.entities.map((x:any)=>x.entityId)).toEqual([lowful.entityUri]);expect(result.entities[0].distanceMeters).toBeGreaterThan(0);expect(result.entities[0]).toMatchObject({telephone:lowful.telephone,actions:lowful.actions,operationalEvidence:{source:'RDM',verificationStatus:'VERIFIED',runtimeDistanceCalculated:true,navigationAvailable:true}});expect(result.entities.some((x:any)=>x.entityId===pension.entityUri)).toBe(false)});
  it('A/B keeps the safe RDM result while EXKO adds relational evidence only',async()=>{const off:any=await new PlaceDiscoveryService(regional as any,disabled).discover('hapcheon','CAFE',golden,{}),on:any=await new PlaceDiscoveryService(regional as any,enabled).discover('hapcheon','CAFE',golden,{});expect(on.entities.map((x:any)=>x.entityId)).toEqual(off.entities.map((x:any)=>x.entityId));expect(off.semanticEvidence).toEqual([]);expect(on.semanticEvidence).toEqual(expect.arrayContaining([expect.objectContaining({subject:'http://sight.eventpool.kr/resource/합천호_스마일펜션',object:'http://sight.eventpool.kr/resource/카페_로우풀',source:'EXKO'})]));expect(on.entities[0].distanceMeters).toBe(off.entities[0].distanceMeters);expect(on.semanticEvidence.every((x:any)=>x.distanceMeters===undefined&&x.actions===undefined)).toBe(true)});
  it('never turns EXKO-only neighbors into operational candidates or actions',async()=>{const noLowful={effectiveDataset:jest.fn(async()=>({regionId:'hapcheon',records:[pension]}))},result:any=await new PlaceDiscoveryService(noLowful as any,enabled).discover('hapcheon','CAFE',golden,{});expect(result.semanticDiagnostics.neighborCandidates).toBeGreaterThan(0);expect(result.entities).toEqual([])});
  it('keeps the pilot disabled and data isolated outside Hapcheon',async()=>expect((await new PlaceDiscoveryService(regional as any,enabled).discover('okcheon','CAFE',golden,{})).entities).toEqual([]));
});
