import { OKCHEON_MASTER_DATA } from './okcheon/master-data';
import { MUAN_MASTER_DATA } from './muan/master-data';
import { GYERYONG_MASTER_DATA } from './gyeryong/master-data';
import { HAPCHEON_MASTER_DATA } from './hapcheon/master-data';
import { DAEJEON_JUNGGU_MASTER_DATA } from './daejeon-junggu/master-data';
export interface RegionalCandidateRecord { entityUri:string;canonicalLabelKo:string;alternateLabels:readonly string[];category:string;tags:readonly string[];runtimeDataStatus:'UNKNOWN'|'PARTIAL'|'VERIFIED';entityType?:string;accommodationType?:string;areaLabel?:string;eventAvailability?:string;accessStatus?:string;accessNotice?:string }
export interface RegionalCandidateDataset { regionId:string;namespace:string;records:readonly RegionalCandidateRecord[];interestAliases:Record<string,string>;interestLabels:Record<string,string>;reasonSummary:string }
export const REGIONAL_CANDIDATE_DATASETS:Record<string,RegionalCandidateDataset>={
  okcheon:{regionId:'okcheon',namespace:'https://okcheon.example/ontology#',records:OKCHEON_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',DAECHEONG_LAKE:'LAKE',REST_AND_RECOVERY:'REST'},interestLabels:{LITERATURE_CULTURE:'문학·문화',TRADITIONAL_CULTURE:'전통문화체험',TOURISM_NATURE:'자연·산책',LAKE:'대청호',FOOD:'맛집',CAFE:'카페',INDOOR:'실내 활동',REST:'편안한 휴식'},reasonSummary:'현재 등록된 옥천 테스트 데이터 기준으로 선택하신 장소와 주변 문화공간을 중심으로 일정을 구성했습니다. 운영시간과 이동시간은 추가 확인이 필요합니다.'},
  muan:{regionId:'muan',namespace:'https://muan.example/ontology#',records:MUAN_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',REST_AND_RECOVERY:'REST'},interestLabels:{LOTUS_ECOLOGY:'연꽃·생태',FAMILY_TRIP:'가족여행',TOURISM_NATURE:'자연·산책',MUDFLAT_COAST:'갯벌·해안',ACTIVITY:'체험',FOOD:'맛집',CAFE:'카페',REST:'편안한 휴식',INDOOR:'실내 활동'},reasonSummary:'현재 등록된 무안 테스트 데이터 기준으로 회산백련지와 주변 권역을 중심으로 일정을 구성했습니다. 운영시간과 이동시간은 추가 확인이 필요합니다.'},
  gyeryong:{regionId:'gyeryong',namespace:'https://gyeryong.example/ontology#',records:GYERYONG_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',REST_AND_RECOVERY:'REST'},interestLabels:{MILITARY_CULTURE_HISTORY:'군문화·역사',FESTIVAL_EVENT:'축제·행사',FAMILY_EXPERIENCE:'가족 체험',TOURISM_NATURE:'자연·산책',FOOD:'맛집',CAFE:'카페',REST:'편안한 휴식',INDOOR:'실내 활동',LOCAL_CONVENIENCE:'생활편의'},reasonSummary:'현재 등록된 계룡 테스트 데이터 기준으로 군문화 공개 행사와 행사권을 중심으로 일정을 구성했습니다. 행사 일정과 관람 가능 여부, 공개구역 출입 가능 여부는 추가 확인이 필요합니다.'},
  hapcheon:{regionId:'hapcheon',namespace:'https://hapcheon.example/ontology#',records:HAPCHEON_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',REST_AND_RECOVERY:'REST'},interestLabels:{HAPCHEON_LAKE:'합천호·호수',TOURISM_NATURE:'자연·산책',SCENIC_DRIVE:'드라이브',FAMILY_TRIP:'가족여행',ACCOMMODATION:'숙박',FOOD:'맛집',CAFE:'카페',REST:'편안한 휴식',ACTIVITY:'체험'},reasonSummary:'현재 등록된 합천 테스트 데이터 기준으로 합천호와 주변 관광권, 숙박 의도를 중심으로 일정을 구성했습니다. 위치와 이동시간, 운영 및 예약 정보는 추가 확인이 필요합니다.'},
  'daejeon-junggu':{regionId:'daejeon-junggu',namespace:'https://daejeon-junggu.example/ontology#',records:DAEJEON_JUNGGU_MASTER_DATA,interestAliases:{REST_AND_RECOVERY:'REST'},interestLabels:{URBAN_CULTURE:'도심문화',TRADITIONAL_MARKET:'전통시장',FOOD:'맛집',CAFE:'카페',PERFORMANCE_EXHIBITION:'공연·전시',FAMILY_OUTING:'가족 나들이',WALKING:'산책',SHOPPING:'쇼핑',LOCAL_CONVENIENCE:'생활편의',REST:'편안한 휴식'},reasonSummary:'현재 등록된 대전 중구 이름 기반 테스트 데이터 기준으로 은행동·중앙로 문화권과 시장·문화예술 권역을 중심으로 구성했습니다. 보행거리, 주차, 대중교통 시간과 운영 정보는 추가 확인이 필요합니다.'},
};
export function regionalCandidateDataset(regionId:string){return REGIONAL_CANDIDATE_DATASETS[regionId]}
