import { OKCHEON_MASTER_DATA } from './okcheon/master-data';
import { MUAN_MASTER_DATA } from './muan/master-data';
import { GYERYONG_MASTER_DATA } from './gyeryong/master-data';
import { HAPCHEON_MASTER_DATA } from './hapcheon/master-data';
import { DAEJEON_JUNGGU_MASTER_DATA } from './daejeon-junggu/master-data';
import { REAL_PLACE_RECORDS } from '../master-data/master-data.records';
export interface RegionalCandidateRecord { entityUri:string;canonicalLabelKo:string;alternateLabels:readonly string[];category:string;tags:readonly string[];runtimeDataStatus:'UNKNOWN'|'PARTIAL'|'VERIFIED';entityType?:string;accommodationType?:string;areaLabel?:string;description?:string;eventAvailability?:string;accessStatus?:string;accessNotice?:string;address?:string;telephone?:string;website?:string;reservationUrl?:string;publicInformationUrl?:string;operatingHours?:unknown;closureDays?:unknown;parking?:unknown;accessibility?:unknown;walkingAccess?:unknown;latitude?:number;longitude?:number;coordinateSource?:object;actions?:Record<string,unknown>;source?:object;lastVerifiedAt?:string }
export interface RegionalCandidateDataset { regionId:string;namespace:string;records:readonly RegionalCandidateRecord[];interestAliases:Record<string,string>;interestLabels:Record<string,string>;reasonSummary:string }
const GAJO_CATEGORY:Record<string,{entityType:string;category:string;tags:string[]}>= {
  '산림휴양시설':{entityType:'ATTRACTION',category:'TOURISM_NATURE',tags:['TOURISM_NATURE','ACTIVITY','REST']},
  '온천시설':{entityType:'WELLNESS',category:'HOT_SPRING_WELLNESS',tags:['HOT_SPRING_WELLNESS','REST']},
  '음식점':{entityType:'RESTAURANT',category:'FOOD',tags:['FOOD']},
  '카페·휴식':{entityType:'CAFE',category:'CAFE',tags:['CAFE','REST']},
  '대표관광지':{entityType:'ATTRACTION',category:'TOURISM_NATURE',tags:['TOURISM_NATURE']},
};
const GAJO_REVIEW_RECORDS:readonly RegionalCandidateRecord[]=[
  {entityUri:'https://gajo-wellness.kr/ontology#geochangChangpowon',canonicalLabelKo:'거창창포원',alternateLabels:['창포원','거창 창포원'],entityType:'ATTRACTION',category:'TOURISM_NATURE',tags:['TOURISM_NATURE'],runtimeDataStatus:'UNKNOWN',description:'기존 의미 근거에서 확인된 거창군 생태공원 장소입니다. 운영 사실은 Regional Manager 검토가 필요합니다.',actions:{},source:{sourceType:'SEMANTIC_EVIDENCE',sourceName:'기존 EXKO 의미 근거',sourceUrl:'repository:server/semantic/exko/sight-copy.rdf'}},
  {entityUri:'https://gajo-wellness.kr/ontology#suseungdae',canonicalLabelKo:'수승대',alternateLabels:['수승대관광지','거창 수승대'],entityType:'ATTRACTION',category:'TOURISM_NATURE',tags:['TOURISM_NATURE'],runtimeDataStatus:'UNKNOWN',description:'기존 Gajo 및 EXKO 의미 근거에서 확인된 거창군 관광지입니다. 운영 사실은 Regional Manager 검토가 필요합니다.',actions:{},source:{sourceType:'SEMANTIC_EVIDENCE',sourceName:'기존 Gajo/EXKO 의미 근거',sourceUrl:'repository:server/semantic/exko/sight-copy.rdf'}},
];
export const GAJO_MASTER_DATA:readonly RegionalCandidateRecord[]=[...REAL_PLACE_RECORDS.map((place):RegionalCandidateRecord=>{const mapped=GAJO_CATEGORY[place.category]||{entityType:'OTHER',category:place.category,tags:[]};const actions:Record<string,unknown>={};const operational=place.verificationStatus!=='UNVERIFIED';if(/^https?:/.test(place.detailsProvenance.sourceUrl))actions.detail={url:place.detailsProvenance.sourceUrl};if(operational&&place.telephone)actions.call={phone:place.telephone};if(operational&&place.website)actions.website={url:place.website};if(operational&&Number.isFinite(place.latitude)&&Number.isFinite(place.longitude))actions.navigate={latitude:place.latitude,longitude:place.longitude};return{entityUri:place.entityUri,canonicalLabelKo:place.canonicalLabelKo,alternateLabels:place.alternateLabels||[],...mapped,runtimeDataStatus:place.verificationStatus==='UNVERIFIED'?'UNKNOWN':place.verificationStatus,address:place.address,telephone:operational?place.telephone:undefined,website:operational?place.website:undefined,description:place.description,latitude:operational?place.latitude:undefined,longitude:operational?place.longitude:undefined,actions,source:{sourceType:place.detailsProvenance.sourceName.includes('거창군')?'OFFICIAL_LOCAL_GOV':'OTHER_VERIFIED_SOURCE',sourceName:place.detailsProvenance.sourceName,sourceUrl:place.detailsProvenance.sourceUrl,verifiedAt:place.detailsProvenance.verifiedAt||place.detailsProvenance.retrievedAt},lastVerifiedAt:place.detailsProvenance.verifiedAt}}),...GAJO_REVIEW_RECORDS];
export const REGIONAL_CANDIDATE_DATASETS:Record<string,RegionalCandidateDataset>={
  gajo:{regionId:'gajo',namespace:'https://gajo-wellness.kr/ontology#',records:GAJO_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',REST_AND_RECOVERY:'REST'},interestLabels:{TOURISM_NATURE:'자연·산책',HOT_SPRING_WELLNESS:'온천·웰니스',FOOD:'맛집',CAFE:'카페',ACTIVITY:'체험',REST:'편안한 휴식'},reasonSummary:'검증된 가조 운영 데이터에서 현재 장소와 선택한 장소를 앵커로 관광·식사·카페 후보를 구성했습니다. 운영시간과 이동시간은 확인 가능한 데이터 범위에서만 안내합니다.'},
  okcheon:{regionId:'okcheon',namespace:'https://okcheon.example/ontology#',records:OKCHEON_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',DAECHEONG_LAKE:'LAKE',REST_AND_RECOVERY:'REST'},interestLabels:{LITERATURE_CULTURE:'문학·문화',TRADITIONAL_CULTURE:'전통문화체험',TOURISM_NATURE:'자연·산책',LAKE:'대청호',FOOD:'맛집',CAFE:'카페',INDOOR:'실내 활동',REST:'편안한 휴식'},reasonSummary:'현재 등록된 옥천 테스트 데이터 기준으로 선택하신 장소와 주변 문화공간을 중심으로 일정을 구성했습니다. 운영시간과 이동시간은 추가 확인이 필요합니다.'},
  muan:{regionId:'muan',namespace:'https://muan.example/ontology#',records:MUAN_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',REST_AND_RECOVERY:'REST'},interestLabels:{LOTUS_ECOLOGY:'연꽃·생태',FAMILY_TRIP:'가족여행',TOURISM_NATURE:'자연·산책',MUDFLAT_COAST:'갯벌·해안',ACTIVITY:'체험',FOOD:'맛집',CAFE:'카페',REST:'편안한 휴식',INDOOR:'실내 활동'},reasonSummary:'현재 등록된 무안 테스트 데이터 기준으로 회산백련지와 주변 권역을 중심으로 일정을 구성했습니다. 운영시간과 이동시간은 추가 확인이 필요합니다.'},
  gyeryong:{regionId:'gyeryong',namespace:'https://gyeryong.example/ontology#',records:GYERYONG_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',REST_AND_RECOVERY:'REST'},interestLabels:{MILITARY_CULTURE_HISTORY:'군문화·역사',FESTIVAL_EVENT:'축제·행사',FAMILY_EXPERIENCE:'가족 체험',TOURISM_NATURE:'자연·산책',FOOD:'맛집',CAFE:'카페',REST:'편안한 휴식',INDOOR:'실내 활동',LOCAL_CONVENIENCE:'생활편의'},reasonSummary:'현재 등록된 계룡 테스트 데이터 기준으로 군문화 공개 행사와 행사권을 중심으로 일정을 구성했습니다. 행사 일정과 관람 가능 여부, 공개구역 출입 가능 여부는 추가 확인이 필요합니다.'},
  hapcheon:{regionId:'hapcheon',namespace:'https://hapcheon.example/ontology#',records:HAPCHEON_MASTER_DATA,interestAliases:{NATURE:'TOURISM_NATURE',REST_AND_RECOVERY:'REST'},interestLabels:{HAPCHEON_LAKE:'합천호·호수',TOURISM_NATURE:'자연·산책',SCENIC_DRIVE:'드라이브',FAMILY_TRIP:'가족여행',ACCOMMODATION:'숙박',FOOD:'맛집',CAFE:'카페',REST:'편안한 휴식',ACTIVITY:'체험'},reasonSummary:'검증된 합천 운영 데이터에서 합천호와 선택한 숙소를 앵커로 관광·식사·카페 후보를 구성했습니다. 운영 여부와 빈 객실은 실시간 확인 정보가 아닙니다.'},
  'daejeon-junggu':{regionId:'daejeon-junggu',namespace:'https://daejeon-junggu.example/ontology#',records:DAEJEON_JUNGGU_MASTER_DATA,interestAliases:{REST_AND_RECOVERY:'REST'},interestLabels:{URBAN_CULTURE:'도심문화',TRADITIONAL_MARKET:'전통시장',FOOD:'맛집',CAFE:'카페',PERFORMANCE_EXHIBITION:'공연·전시',FAMILY_OUTING:'가족 나들이',WALKING:'산책',SHOPPING:'쇼핑',LOCAL_CONVENIENCE:'생활편의',REST:'편안한 휴식'},reasonSummary:'현재 등록된 대전 중구 이름 기반 테스트 데이터 기준으로 은행동·중앙로 문화권과 시장·문화예술 권역을 중심으로 구성했습니다. 보행거리, 주차, 대중교통 시간과 운영 정보는 추가 확인이 필요합니다.'},
};
export const REGIONAL_BOOTSTRAP_REGION_IDS=['gajo','hapcheon','okcheon'] as const;
export function regionalCandidateDataset(regionId:string){return REGIONAL_CANDIDATE_DATASETS[regionId]}
