import { useState } from 'react';
import { api } from '../api/client';
import ActionChannelManager from './ActionChannelManager';
import VisitorAnalyticsDashboard from './VisitorAnalyticsDashboard';
import './business-registration.css';
const types:Record<string,string>={ACCOMMODATION:'숙박',PENSION:'펜션',GLAMPING:'글램핑',CAMPING:'캠핑',CAFE:'카페',RESTAURANT:'식당',ATTRACTION:'관광지',EXPERIENCE:'체험'};
const states:Record<string,string>={NEW_CANDIDATE:'검증 대기',NEEDS_VERIFICATION:'재확인 필요',APPROVED:'검수 완료 · 비공개',ACTIVE:'공개 중',CHANGE_DETECTED:'확인 필요',REJECTED:'비공개',ARCHIVED:'운영 중지'};
const empty=()=>({displayName:'',englishName:'',businessType:'PENSION',address:'',phone:'',websiteUrl:'',naverPlaceUrl:'',kakaoPlaceUrl:'',latitude:'',longitude:'',mapConfirmed:false,phoneConfirmed:false,shortDescription:'',sourceUrl:'',verifiedOn:new Date().toISOString().slice(0,10)});
export default function BusinessRegistrationManager({onAdminTokenChange}:{onAdminTokenChange?:(token:string)=>void}) {
  const [token,setToken]=useState(()=>sessionStorage.getItem('admin-write-token')||''),[search,setSearch]=useState(''),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[editing,setEditing]=useState(false),[form,setForm]=useState(empty),[duplicates,setDuplicates]=useState<any[]|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const headers={'x-admin-token':token}, path='/admin/businesses', query='regionId=hapcheon';
  const input=()=>({...form,latitude:form.latitude===''?undefined:Number(form.latitude),longitude:form.longitude===''?undefined:Number(form.longitude)});
  const run=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setNotice('');try{await work()}catch(e:any){setNotice(typeof e.response?.data?.message==='string'?e.response.data.message:'처리하지 못했습니다. 관리 권한과 입력을 확인해 주세요.');if(e.response?.data?.duplicates)setDuplicates(e.response.data.duplicates)}finally{setBusy(false)}};
  const choose=(row:any)=>{setSelected(row);setEditing(false);setConfirmed(false);setDuplicates(null)};
  const change=async(action:string)=>{const {data}=await api.post(`${path}/${selected.id}/${action}?${query}`,{revision:selected.registration.revision,confirmed,...(action==='EDIT'?{input:input()}: {})},{headers});choose(data);setNotice('반영했습니다. 장소 공개와 연결 공개는 별도 단계입니다.')};
  const save=()=>run(async()=>{if(selected?.registration){await change('EDIT');return}if(duplicates===null||duplicates.length)throw new Error();const {data}=await api.post(`${path}?${query}`,input(),{headers});choose(data);setNotice('검증 대기로 등록했습니다. 아직 관광객에게 보이지 않습니다.')});
  return <section className="business-registration card" aria-label="합천 업소 관리"><h2>합천 업소 관리</h2><p>1. 업소 등록 → 2. 정보 검수·장소 공개 → 3. 전화·예약 연결 검수·공개</p>
    <label>관리자 인증<input type="password" autoComplete="off" value={token} onChange={e=>{setToken(e.target.value);sessionStorage.setItem('admin-write-token',e.target.value);onAdminTokenChange?.(e.target.value);setRows([]);setSelected(null)}}/></label>
    <div className="business-controls"><button type="button" onClick={()=>{setEditing(false);setSelected(null)}}>등록된 업소 관리</button><button type="button" onClick={()=>{setSelected(null);setForm(empty());setEditing(true);setDuplicates(null);setNotice('')}}>새 업소 등록</button></div>
    {!editing&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{const {data}=await api.get(`${path}?${query}`,{headers,params:{search}});setRows(data)})}}><label>업소명 검색<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="예: 스마일펜션"/></label><button disabled={busy||!token}>검색</button><ul>{rows.map(row=><li key={row.id}><button type="button" onClick={()=>choose(row)}>{row.displayName} · {states[row.lifecycleStatus]||'확인 필요'}</button></li>)}</ul></form>}
    {editing&&<form onSubmit={e=>{e.preventDefault();void save()}}><h3>{selected?'업소 정보 수정':'새 업소 등록'}</h3><p>지역: 합천 · 영어명 미입력 시 영어 이름 미확인으로 관리합니다.</p>
      <label>업종<select value={form.businessType} onChange={e=>{setForm({...form,businessType:e.target.value});setDuplicates(null)}}>{Object.entries(types).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
      {([['displayName','업소명'],['englishName','영어명 (선택)'],['address','주소'],['phone','전화번호 (미확인 시 비공개)'],['websiteUrl','공식 홈페이지 (선택)'],['naverPlaceUrl','네이버 플레이스 (선택)'],['kakaoPlaceUrl','카카오 플레이스 (선택)'],['latitude','위도 (선택)'],['longitude','경도 (선택)'],['shortDescription','짧은 소개'],['sourceUrl','공식 정보 근거 URL'],['verifiedOn','정보 확인일']] as const).map(([key,label])=><label key={key}>{label}<input required={['displayName','address','shortDescription','sourceUrl','verifiedOn'].includes(key)} maxLength={1000} type={key==='verifiedOn'?'date':key.endsWith('Url')?'url':'text'} inputMode={key==='latitude'||key==='longitude'?'decimal':undefined} value={form[key]} onChange={e=>{setForm({...form,[key]:e.target.value});setDuplicates(null)}}/></label>)}
      <label><input type="checkbox" checked={form.mapConfirmed} onChange={e=>setForm({...form,mapConfirmed:e.target.checked})}/>주소와 지도 좌표가 같은 업소임을 확인했습니다. 미확인 시 길찾기는 비공개입니다.</label>
      <label><input type="checkbox" checked={form.phoneConfirmed} onChange={e=>setForm({...form,phoneConfirmed:e.target.checked})}/>전화번호를 확인했습니다. 전화 연결은 장소 공개 후 별도 검수합니다.</label>
      {!selected&&<><button type="button" disabled={busy||!token} onClick={()=>void run(async()=>{const {data}=await api.post(`${path}/duplicates?${query}`,input(),{headers});setDuplicates(data)})}>중복 업소 확인</button>{duplicates!==null&&<div role="status">{duplicates.length?'같은 업소일 수 있습니다. 등록된 업소에서 확인해 주세요.':'중복 후보가 없습니다.'}{duplicates.map((r:any)=><p key={r.canonicalEntityId}>{r.displayName} · {r.address}</p>)}</div>}</>}
      <button disabled={busy||!token||(!selected&&(duplicates===null||duplicates.length>0))}>{selected?'수정 저장 · 비공개로 전환':'검증 대기로 등록'}</button></form>}
    {selected&&!editing&&<section aria-label="선택한 업소"><h3>{selected.displayName}</h3><p>{states[selected.lifecycleStatus]||'확인 필요'}</p><p>{selected.registration?.input?.address||selected.address}</p><p>영어명: {selected.registration?.input?.englishName||selected.visitorContent?.reviewedEnglishName||'미입력 · 영어 이름 미확인'}</p>
      {selected.registration&&<><p>{selected.registration.input.shortDescription}</p><a href={selected.source.sourceUrl} target="_blank" rel="noopener noreferrer">공식 근거 확인 (새 창)</a><p>정보 확인일: {selected.registration.input.verifiedOn}</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>공식 근거와 업소명·주소·기본정보를 확인했습니다.</label><div className="business-controls"><button disabled={busy||!confirmed} onClick={()=>void run(()=>change('VERIFY'))}>검수 완료</button><button disabled={busy||selected.lifecycleStatus!=='APPROVED'} onClick={()=>void run(()=>change('PUBLISH'))}>장소 공개</button><button disabled={busy} onClick={()=>{setForm({...empty(),...selected.registration.input,latitude:selected.registration.input.latitude?.toString()||'',longitude:selected.registration.input.longitude?.toString()||''});setEditing(true)}}>업소 정보 수정</button><button disabled={busy} onClick={()=>void run(()=>change('STOP'))}>운영 중지</button></div><details><summary>정보 변경·검수 이력</summary>{selected.auditTrail.map((a:any,i:number)=><p key={i}>{a.at} · {a.action} · {a.actorId}</p>)}</details></>}
      {selected.lifecycleStatus==='ACTIVE'&&selected.verificationStatus==='VERIFIED'?<ActionChannelManager key={selected.id} regionId="hapcheon" placeKey={selected.canonicalEntityId} token={token}/>:<p>검수 완료 후 장소를 공개하면 전화·홈페이지·지도·예약 연결을 등록할 수 있습니다.</p>}
    </section>}
    <p role="status">{notice}</p><details><summary>업소별 이용 통계</summary><VisitorAnalyticsDashboard token={token} placeNames={Object.fromEntries([...rows,...(selected?[selected]:[])].map(r=>[r.canonicalEntityId,r.displayName]))}/></details></section>;
}
