import{useState}from'react';
import{fetchFacilities}from'../api/client';
import{canonicalEntityId,recommendationItemLabel}from'../recommendationItem';
import{editItineraryItem,replacementCandidate}from'../itineraryEditing';
import type{TripSession}from'../tripSession';

export default function ItineraryItemEditor({step,index,total,regionId,onChanged}:{step:any;index:number;total:number;regionId:string;onChanged:(session:TripSession)=>void}){
 const[open,setOpen]=useState(false),[replacing,setReplacing]=useState(false),[candidates,setCandidates]=useState<any[]>([]),[notice,setNotice]=useState('');const entityId=canonicalEntityId(step)||'',id=step.itemId||entityId,completed=step.status==='COMPLETED';
 const apply=(edit:any)=>{const result=editItineraryItem(regionId,id,edit);if(result.status==='updated'&&result.session){onChanged(result.session);setOpen(false);setReplacing(false);setNotice('')}else setNotice(result.reason||'이 변경을 안전하게 적용할 수 없습니다.')};
 const find=async()=>{setReplacing(true);setNotice('');try{const rows=await fetchFacilities(regionId),currentCategory=String(step.category||step.entityType||'');setCandidates(rows.map((row:any)=>replacementCandidate(row,regionId)).filter(Boolean).filter((row:any)=>canonicalEntityId(row)!==entityId&&String(row.category||row.entityType||'')===currentCategory))}catch{setNotice('대체 장소를 불러오지 못했습니다. 다시 시도해 주세요.')}};
 return <div className="itinerary-item-management"><button type="button" className="itinerary-item-menu-button" aria-label={`${recommendationItemLabel(step)} 일정 수정`} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>⋯</button>{open&&<div className="itinerary-item-edit-panel"><strong>이 일정만 수정</strong>{completed?<p>완료한 일정은 방문 기록을 보호하기 위해 수정할 수 없습니다.</p>:<><button type="button" onClick={find}>다른 장소로 바꾸기</button><label>방문 시간 변경<input type="time" value={step.scheduledTime||''} onChange={e=>apply({type:'TIME',scheduledTime:e.target.value})}/></label><div className="itinerary-order-buttons"><button type="button" disabled={index===0} onClick={()=>apply({type:'MOVE',direction:'UP'})}>위로 이동</button><button type="button" disabled={index===total-1} onClick={()=>apply({type:'MOVE',direction:'DOWN'})}>아래로 이동</button></div><button type="button" className="danger-text" onClick={()=>{if(window.confirm(`${recommendationItemLabel(step)}을(를) 일정에서 삭제할까요?`))apply({type:'DELETE'})}}>이 장소 삭제</button>{replacing&&<div className="itinerary-replacement-list" aria-label="대체 장소 선택">{candidates.length?candidates.map(candidate=><button type="button" key={candidate.entityId} onClick={()=>apply({type:'REPLACE',replacement:candidate})}>{recommendationItemLabel(candidate)}</button>):<p>같은 유형의 검증된 대체 장소가 없습니다.</p>}</div>}</>}{notice&&<p role="status">{notice}</p>}</div>}</div>;
}
