import { useState } from "react";
import { fetchNearbyAnchors, reverseGeocodeLocation, searchLocation, type NearbyPlace } from "../api/client";
import { useRegion } from "../RegionContext";
import { confirmTripLocation, ensureTripSession, isFreshTripLocation, type TripLocation, type TripLocationStatus } from "../tripSession";
import { locationConfidence, observeVisitorLocation, setSessionLocation } from "../utils/visitorLocation";

const accuracyLabel=(accuracy?:number)=>({HIGH:"위치 정확도 좋음",MEDIUM:"위치 정확도 보통",LOW:"위치 정확도 낮음",UNUSABLE:"위치 정확도 확인 필요"})[locationConfidence(accuracy)];

export default function LocationContextBar({mode,onConfirmed,refreshNeeded=false}:{mode:"NOW"|"PLAN";onConfirmed?:(location:TripLocation,previous?:TripLocation)=>void;refreshNeeded?:boolean;searchTarget?:string}) {
  const region=useRegion(),session=ensureTripSession(region.id),saved=mode==="NOW"?session.locationContext?.now:session.locationContext?.planStart,nowSaved=session.locationContext?.now;
  const [status,setStatus]=useState<TripLocationStatus>(saved?.status||"UNKNOWN"),[candidate,setCandidate]=useState<TripLocation|undefined>(saved),[changing,setChanging]=useState(false),[entry,setEntry]=useState<"MANUAL"|"SELECTED_PLACE"|null>(null),[query,setQuery]=useState(""),[results,setResults]=useState<NearbyPlace[]>([]),[message,setMessage]=useState<string>(),[busy,setBusy]=useState(false);
  const requestGps=async()=>{if(busy)return;setEntry(null);setQuery("");setResults([]);setBusy(true);setStatus("REQUESTING");setMessage(undefined);const gps=await observeVisitorLocation();if(gps.status!=="AVAILABLE"){setBusy(false);setStatus(gps.status==="DENIED"?"DENIED":"ERROR");setMessage(gps.status==="DENIED"?"위치 권한이 거부되었습니다. 다른 장소를 기준으로 계속할 수 있어요.":gps.status==="TIMEOUT"?"위치 확인 시간이 초과되었습니다. 다른 장소를 기준으로 계속할 수 있어요.":"현재 위치를 사용할 수 없습니다. 다른 장소를 기준으로 계속할 수 있어요.");return}const usable=["HIGH","MEDIUM"].includes(locationConfidence(gps.accuracy));if(!usable){setCandidate({status:"STALE",source:"GPS",accuracy:gps.accuracy,experienceRegionId:region.id,observedAt:gps.observedAt});setStatus("STALE");setMessage("위치 정확도가 부족합니다. 다른 장소를 기준으로 찾아보세요.");setBusy(false);return}let label="현재 위치 주변",address:string|undefined,searchRegionId:string|undefined,regionMembership:TripLocation["regionMembership"]="UNCERTAIN";try{const reverse=await reverseGeocodeLocation(gps.latitude!,gps.longitude!,region.id,gps.accuracy);regionMembership=reverse.regionMembership||"UNCERTAIN";searchRegionId=reverse.searchRegionId||reverse.detectedRegionId;if(reverse.status==="RESOLVED"){label=reverse.label;address=reverse.address}}catch{}const next:TripLocation={status:"CONFIRMED",source:"GPS",latitude:gps.latitude,longitude:gps.longitude,accuracy:gps.accuracy,label,address,experienceRegionId:region.id,searchRegionId,regionMembership,observedAt:gps.observedAt,confirmedAt:new Date().toISOString()};confirmTripLocation(region.id,mode,next);if(mode==="NOW")setSessionLocation({status:"AVAILABLE",latitude:next.latitude,longitude:next.longitude,accuracy:next.accuracy!,observedAt:next.observedAt});onConfirmed?.(next,saved);setCandidate(next);setStatus(next.status);setMessage(searchRegionId&&searchRegionId!==region.id?`현재 ${label} 주변을 찾고 있어요.`:"현재 위치 주변에서 찾았습니다.");setBusy(false)};
  const openPlaceFallback=async()=>{setStatus("UNKNOWN");setEntry("SELECTED_PLACE");setQuery("");setMessage(undefined);setBusy(true);try{setResults(await fetchNearbyAnchors(region.id))}catch{setResults([]);setMessage("대표 장소를 불러오지 못했습니다. 장소명을 검색해 주세요.")}finally{setBusy(false)}};
  const lookup=async()=>{if(query.trim().length<2||busy)return;setBusy(true);setMessage(undefined);try{const rows=await searchLocation(query.trim(),region.id,undefined,candidate?.searchRegionId||saved?.searchRegionId||region.id);setResults(rows);if(!rows.length)setMessage("확인된 장소가 없습니다. 더 구체적인 주소나 장소명을 입력해 주세요.")}catch{setMessage("장소 검색이 원활하지 않습니다. 잠시 후 다시 시도해 주세요.")}finally{setBusy(false)}};
  const choose=(place:NearbyPlace)=>{setCandidate({status:"RESOLVED",source:entry||"SELECTED_PLACE",latitude:place.lat,longitude:place.lng,label:place.name,address:place.roadAddress||place.address,experienceRegionId:region.id,searchRegionId:saved?.searchRegionId||region.id,regionMembership:"INSIDE",observedAt:new Date().toISOString()});setStatus("RESOLVED");setChanging(false);setResults([])};
  const confirm=()=>{if(!candidate||!Number.isFinite(candidate.latitude)||!Number.isFinite(candidate.longitude))return;const previous=mode==="NOW"?saved:undefined,next:TripLocation={...candidate,status:"CONFIRMED"};confirmTripLocation(region.id,mode,next);if(mode==="NOW")setSessionLocation({status:"AVAILABLE",latitude:next.latitude,longitude:next.longitude,accuracy:next.accuracy??100,observedAt:next.observedAt});setCandidate({...next,confirmedAt:new Date().toISOString()});setStatus("CONFIRMED");setChanging(false);setMessage(previous&&previous.label!==next.label?"현재 위치 기준으로 다시 찾았습니다.":undefined);onConfirmed?.(next,previous)};
  const change=()=>{setChanging(true);setEntry(null);setQuery("");setResults([]);setMessage("현재 위치가 달라졌어요. 이곳을 기준으로 다시 찾아볼까요?")},cancel=()=>{setChanging(false);setCandidate(saved);setStatus(saved?.status||"UNKNOWN");setEntry(null);setMessage(undefined)};
  const outside=candidate?.regionMembership==="OUTSIDE",uncertain=candidate?.regionMembership==="UNCERTAIN",needsLocation=!candidate||changing||refreshNeeded||status==="UNKNOWN"||status==="DENIED"||status==="ERROR"||status==="STALE",stale=mode==="NOW"&&saved?.status==="CONFIRMED"&&!isFreshTripLocation(saved);
  const gpsButton=mode==="PLAN"&&nowSaved?.status==="CONFIRMED"?`${nowSaved.label||nowSaved.address||"확인한 현재 위치"}에서 시작`:mode==="PLAN"?"현재 위치에서 시작":saved?"현재 위치 다시 확인":"현재 위치로 찾기";
  return <section className="location-context-bar" aria-live="polite">
    {mode==="PLAN"?<><small>여행 시작 위치</small><h2>어디에서 여행을 시작할까요?</h2></>:candidate&&!changing?<><small>현재 위치</small><h2>📍 {candidate.label||candidate.address||"현재 위치 주변"}</h2></>:<><small>내 주변 찾기</small><h2>현재 위치 주변에서 찾아드릴까요?</h2><p>버튼을 누를 때만 브라우저 위치 권한을 요청합니다.</p></>}
    {(stale||refreshNeeded)&&!changing&&<p className="location-message">마지막으로 확인한 위치가 오래됐어요. 현재 위치를 다시 확인할까요?</p>}
    {changing&&saved&&<p className="location-previous">이전 확인 위치: <b>{saved.label||saved.address}</b></p>}
    {needsLocation&&<div className="location-methods"><button className="btn btn-primary location-primary-action" type="button" disabled={busy} onClick={mode==="PLAN"&&nowSaved?.status==="CONFIRMED"?()=>{setCandidate({...nowSaved,status:"RESOLVED",source:"TRIP_CONTEXT",observedAt:new Date().toISOString()});setStatus("RESOLVED")}:requestGps}>{gpsButton}</button><button type="button" disabled={busy} onClick={openPlaceFallback}>다른 위치에서 찾기</button>{changing&&<button type="button" className="btn btn-text" onClick={cancel}>변경 취소</button>}</div>}
    {status==="REQUESTING"&&<p>현재 위치를 확인하고 있습니다.</p>}
    {entry&&status!=="CONFIRMED"&&<div className="location-manual"><h3>어디를 기준으로 찾을까요?</h3><p>먼저 검증된 지역 대표 장소를 선택하거나, 지역 안의 장소명을 검색하세요.</p>{results.map(place=><button type="button" className="location-result" key={place.id} onClick={()=>choose(place)}><b>{place.name}</b><small>{place.providerCategoryName||place.categoryLabel||"장소 유형 확인 필요"}</small><small>{place.roadAddress||place.address||"주소 확인 필요"}</small></button>)}<label>장소명 검색<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={`예: ${results.slice(0,2).map(place=>place.name).join(", ")||`${region.regionName} 관광지`}`}/></label><button type="button" className="btn btn-outline" disabled={busy} onClick={lookup}>현재 지역에서 찾기</button></div>}
    {(status==="RESOLVED"||status==="CONFIRMED"||status==="STALE")&&candidate&&!changing&&<div className="location-confirmation"><p>{candidate.address||candidate.label}</p>{candidate.searchRegionId&&candidate.searchRegionId!==region.id&&<p className="location-message">{region.regionName} 여행 화면은 유지하고, 현재 {candidate.label} 주변을 찾고 있어요.</p>}{candidate.source==="GPS"&&<p>GPS 정확도 약 {Math.round(candidate.accuracy||0)}m · {accuracyLabel(candidate.accuracy)}</p>}{candidate.confirmedAt&&<p>마지막 확인 {new Date(candidate.confirmedAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</p>}{outside&&!candidate.searchRegionId&&<div className="location-outside"><b>현재 위치는 지원 지역 밖으로 확인됩니다.</b><p>좌표를 기준으로 주변 장소를 찾아드립니다.</p></div>}{uncertain&&<div className="location-outside"><b>지역 경계와 가까울 수 있어요.</b><p>주소와 현재 좌표를 함께 기준으로 주변 장소를 찾습니다.</p></div>}<div>{status==="RESOLVED"&&<button type="button" className="btn btn-primary" onClick={confirm}>{mode==="NOW"?"이 위치로 시작":"이 위치를 시작점으로"}</button>}<button type="button" className="btn btn-outline" onClick={change}>위치 변경</button></div></div>}
    {message&&<p className="location-message">{message}</p>}
    {session.locationContext?.pendingReplan&&mode==="NOW"&&<div className="location-replan-notice"><b>위치가 달라져 남은 일정 확인이 필요해요.</b><p>{session.locationContext.pendingReplan.distanceMeters!=null?`이전 기준 위치에서 약 ${(session.locationContext.pendingReplan.distanceMeters/1000).toFixed(1)}km 이동했습니다. `:""}기존 일정은 아직 변경하지 않았습니다. AI 여행도우미에서 RE-PLAN을 확인해 주세요.</p></div>}
  </section>;
}
