import { useState } from "react";
import { reverseGeocodeLocation, searchLocation, type NearbyPlace } from "../api/client";
import { useRegion } from "../RegionContext";
import { confirmTripLocation, ensureTripSession, isFreshTripLocation, type TripLocation, type TripLocationStatus } from "../tripSession";
import { locationConfidence, observeVisitorLocation, setSessionLocation } from "../utils/visitorLocation";

const accuracyLabel=(accuracy?:number)=>({HIGH:"위치 정확도 좋음",MEDIUM:"위치 정확도 보통",LOW:"위치 정확도 낮음",UNUSABLE:"위치 정확도 확인 필요"})[locationConfidence(accuracy)];

export default function LocationContextBar({mode,onConfirmed,refreshNeeded=false}:{mode:"NOW"|"PLAN";onConfirmed?:(location:TripLocation,previous?:TripLocation)=>void;refreshNeeded?:boolean}) {
  const region=useRegion(),session=ensureTripSession(region.id),saved=mode==="NOW"?session.locationContext?.now:session.locationContext?.planStart,nowSaved=session.locationContext?.now;
  const [status,setStatus]=useState<TripLocationStatus>(saved?.status||"UNKNOWN"),[candidate,setCandidate]=useState<TripLocation|undefined>(saved),[changing,setChanging]=useState(false),[entry,setEntry]=useState<"MANUAL"|"SELECTED_PLACE"|null>(null),[query,setQuery]=useState(""),[results,setResults]=useState<NearbyPlace[]>([]),[message,setMessage]=useState<string>(),[busy,setBusy]=useState(false);
  const requestGps=async()=>{if(busy)return;setBusy(true);setStatus("REQUESTING");setMessage(undefined);const gps=await observeVisitorLocation();if(gps.status!=="AVAILABLE"){setBusy(false);setStatus(gps.status==="DENIED"?"DENIED":"ERROR");setMessage(gps.status==="DENIED"?"위치 권한이 거부되었습니다. 직접 입력하거나 장소를 선택해 주세요.":"현재 위치를 확인하지 못했습니다. 다른 방법으로 계속할 수 있어요.");return}const confidence=locationConfidence(gps.accuracy),usable=confidence!=="UNUSABLE";try{const reverse=await reverseGeocodeLocation(gps.latitude!,gps.longitude!);const next:TripLocation={status:usable?"RESOLVED":"STALE",source:"GPS",latitude:gps.latitude,longitude:gps.longitude,accuracy:gps.accuracy,label:reverse.label,address:reverse.address,observedAt:gps.observedAt};setCandidate(next);setStatus(next.status);if(!usable)setMessage("GPS 정확도가 낮아 주변 거리 기준으로 사용하지 않습니다. 직접 입력하거나 장소를 선택해 주세요.")}catch{const nextStatus=usable?"RESOLVED":"STALE";setCandidate({status:nextStatus,source:"GPS",latitude:gps.latitude,longitude:gps.longitude,accuracy:gps.accuracy,label:"주소 확인 실패",observedAt:gps.observedAt});setStatus(nextStatus);setMessage(usable?"주소 확인 서비스가 원활하지 않습니다. 좌표와 정확도를 확인한 뒤 사용할 수 있어요.":"GPS 정확도가 낮습니다. 직접 입력하거나 장소를 선택해 주세요.")}finally{setBusy(false)}};
  const lookup=async()=>{if(query.trim().length<2||busy)return;setBusy(true);setMessage(undefined);try{const rows=await searchLocation(query.trim(),region.id,candidate?.latitude!=null&&candidate.longitude!=null?{latitude:candidate.latitude,longitude:candidate.longitude}:undefined);setResults(rows);if(!rows.length)setMessage("확인된 장소가 없습니다. 더 구체적인 주소나 장소명을 입력해 주세요.")}catch{setMessage("장소 검색이 원활하지 않습니다. 잠시 후 다시 시도해 주세요.")}finally{setBusy(false)}};
  const choose=(place:NearbyPlace)=>{setCandidate({status:"RESOLVED",source:entry||"SELECTED_PLACE",latitude:place.lat,longitude:place.lng,label:place.name,address:place.roadAddress||place.address,observedAt:new Date().toISOString()});setStatus("RESOLVED");setChanging(false);setResults([])};
  const confirm=()=>{if(!candidate||!Number.isFinite(candidate.latitude)||!Number.isFinite(candidate.longitude))return;const previous=mode==="NOW"?saved:undefined,next:TripLocation={...candidate,status:"CONFIRMED"};confirmTripLocation(region.id,mode,next);if(mode==="NOW")setSessionLocation({status:"AVAILABLE",latitude:next.latitude,longitude:next.longitude,accuracy:next.accuracy??100,observedAt:next.observedAt});setCandidate({...next,confirmedAt:new Date().toISOString()});setStatus("CONFIRMED");setChanging(false);setMessage(previous&&previous.label!==next.label?"현재 위치 기준으로 다시 찾았습니다.":undefined);onConfirmed?.(next,previous)};
  const change=()=>{setChanging(true);setEntry(null);setQuery("");setResults([]);setMessage("현재 위치가 달라졌어요. 이곳을 기준으로 다시 찾아볼까요?")},cancel=()=>{setChanging(false);setCandidate(saved);setStatus(saved?.status||"UNKNOWN");setEntry(null);setMessage(undefined)};
  const expected=region.regionName.replace(/\s*여행.*/,"").slice(0,2),outside=Boolean(candidate?.label&&expected&&!candidate.label.includes(expected)),needsLocation=!candidate||changing||refreshNeeded||status==="UNKNOWN"||status==="DENIED"||status==="ERROR"||status==="STALE",stale=mode==="NOW"&&saved?.status==="CONFIRMED"&&!isFreshTripLocation(saved);
  const gpsButton=mode==="PLAN"&&nowSaved?.status==="CONFIRMED"?`${nowSaved.label||nowSaved.address||"확인한 현재 위치"}에서 시작`:mode==="PLAN"?"현재 위치에서 시작":saved?"현재 위치 다시 확인":"현재 위치 사용";
  return <section className="location-context-bar" aria-live="polite">
    {mode==="PLAN"?<><small>여행 시작 위치</small><h2>어디에서 여행을 시작할까요?</h2></>:candidate&&!changing?<><small>현재 위치</small><h2>📍 {candidate.label||candidate.address||"확인된 지역"}</h2></>:<><small>현재 위치</small><h2>현재 어디에 계세요?</h2><p>현재 위치를 알려주시면 주변 관광지·식당·카페와 편의시설을 찾아드릴게요.</p></>}
    {(stale||refreshNeeded)&&!changing&&<p className="location-message">마지막으로 확인한 위치가 오래됐어요. 현재 위치를 다시 확인할까요?</p>}
    {changing&&saved&&<p className="location-previous">이전 확인 위치: <b>{saved.label||saved.address}</b></p>}
    {needsLocation&&<div className="location-methods"><button type="button" disabled={busy} onClick={mode==="PLAN"&&nowSaved?.status==="CONFIRMED"?()=>{setCandidate({...nowSaved,status:"RESOLVED",source:"TRIP_CONTEXT",observedAt:new Date().toISOString()});setStatus("RESOLVED")}:requestGps}>{gpsButton}</button><button type="button" disabled={busy} onClick={()=>{setStatus("UNKNOWN");setEntry("MANUAL")}}>직접 입력</button><button type="button" disabled={busy} onClick={()=>{setStatus("UNKNOWN");setEntry("SELECTED_PLACE");setQuery(region.regionName)}}>{mode==="PLAN"?`${region.regionName} 지역·관광지 선택`:"지역·장소 선택"}</button>{changing&&<button type="button" className="btn btn-text" onClick={cancel}>변경 취소</button>}</div>}
    {status==="REQUESTING"&&<p>브라우저에서 현재 위치를 확인하고 있습니다…</p>}
    {entry&&status!=="CONFIRMED"&&<div className="location-manual"><label>{entry==="MANUAL"?"주소 또는 장소명":"지역·관광지"}<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="예: 합천군 대병면 또는 합천호"/></label><button type="button" className="btn btn-outline" disabled={busy} onClick={lookup}>찾기</button>{results.map(place=><button type="button" className="location-result" key={place.id} onClick={()=>choose(place)}><b>{place.name}</b><small>{place.roadAddress||place.address||"주소 확인 필요"}</small></button>)}</div>}
    {(status==="RESOLVED"||status==="CONFIRMED"||status==="STALE")&&candidate&&!changing&&<div className="location-confirmation"><p>{candidate.address||candidate.label}</p>{candidate.source==="GPS"&&<p>GPS 정확도 약 {Math.round(candidate.accuracy||0)}m · {accuracyLabel(candidate.accuracy)}</p>}{candidate.confirmedAt&&<p>마지막 확인 {new Date(candidate.confirmedAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</p>}{outside&&<div className="location-outside"><b>현재 위치는 {region.regionName} 밖으로 확인됩니다.</b><p>현재 지역 주변을 찾거나 {region.regionName} 여행 시작 위치를 별도로 선택할 수 있어요.</p>{status==="RESOLVED"&&<button type="button" className="btn btn-outline" onClick={confirm}>현재 지역 주변 찾기</button>}<button type="button" className="btn btn-outline" onClick={()=>{setChanging(true);setEntry("SELECTED_PLACE");setQuery(region.regionName)}}>{region.regionName} 여행을 계획하기</button></div>}<div>{status==="RESOLVED"&&!outside&&<button type="button" className="btn btn-primary" onClick={confirm}>{mode==="NOW"?"이 위치로 시작":"이 위치를 시작점으로"}</button>}<button type="button" className="btn btn-outline" onClick={change}>위치 변경</button></div></div>}
    {message&&<p className="location-message">{message}</p>}
    {session.locationContext?.pendingReplan&&mode==="NOW"&&<div className="location-replan-notice"><b>위치가 달라져 남은 일정 확인이 필요해요.</b><p>{session.locationContext.pendingReplan.distanceMeters!=null?`이전 기준 위치에서 약 ${(session.locationContext.pendingReplan.distanceMeters/1000).toFixed(1)}km 이동했습니다. `:""}기존 일정은 아직 변경하지 않았습니다. AI 여행도우미에서 RE-PLAN을 확인해 주세요.</p></div>}
  </section>;
}
