import test from 'node:test';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import { assertApplyAuthorization, documentHash, runReceipt32Restore, TARGET } from './receipt32-restore-core.mjs';

const { ObjectId }=mongoose.mongo,{EJSON}=mongoose.mongo.BSON;
const clone=value=>EJSON.parse(EJSON.stringify(value,{relaxed:false}),{relaxed:false});
const preImage=()=>({_id:new ObjectId(TARGET._id),id:TARGET.id,regionId:TARGET.regionId,canonicalEntityId:TARGET.canonicalEntityId,displayName:'합천 정원테마파크',aliases:[],verificationStatus:'VERIFIED',lifecycleStatus:'CHANGE_DETECTED',detectedChanges:[{field:'displayName',newValue:'합천영상테마파크'}],proposedFacts:{displayName:'합천영상테마파크',aliases:['영상테마파크']},auditTrail:[{action:'CHANGE_DETECTED',at:'2026-08-30T09:41:47.254Z'}],source:{sourceType:'KTO_LINKED_DATA',sourceUrl:'https://example.invalid/evidence'},createdAt:new Date('2026-08-19T03:02:18.692Z'),updatedAt:new Date('2026-08-30T09:41:47.254Z'),__v:4});
const current=pre=>{const post={...clone(pre),lifecycleStatus:'ACTIVE',detectedChanges:[],auditTrail:[...clone(pre.auditTrail),{action:'IGNORE_CHANGE',at:'2026-09-01T00:00:00.000Z',actorId:'OPS_01'}],updatedAt:new Date('2026-09-01T00:00:00.000Z'),__v:5};delete post.proposedFacts;return post};
const neighbor=(canonicalEntityId,name)=>({_id:new ObjectId(),id:`fixture-${name}`,regionId:'hapcheon',canonicalEntityId,displayName:name,lifecycleStatus:'ACTIVE',auditTrail:[],__v:1});
const matches=(row,query)=>Object.entries(query).every(([key,value])=>{if(key==='proposedFacts'&&value?.$exists===false)return row[key]===undefined;if(key==='detectedChanges'&&value?.$size===0)return Array.isArray(row[key])&&row[key].length===0;if(key==='auditTrail.action')return row.auditTrail?.some(event=>event.action===value);return String(row[key])===String(value)});
const repository=rows=>({rows,writes:0,find(query){return{toArray:async()=>rows.filter(row=>matches(row,query)).map(clone)}},async updateOne(query,update){const found=rows.filter(row=>matches(row,query));if(found.length!==1)return{matchedCount:found.length,modifiedCount:0};const row=found[0];Object.assign(row,clone(update.$set));row.auditTrail.push(clone(update.$push.auditTrail));row.__v=Number(row.__v)+update.$inc.__v;this.writes++;return{matchedCount:1,modifiedCount:1}}});
const fixture=()=>{const pre=preImage(),post=current(pre),video=neighbor('https://hapcheon.example/ontology#hapcheonVideoThemePark','합천 영상테마파크'),festival=neighbor('https://hapcheon.example/ontology#hwangmaesanSilverGrassFestival','황매산 억새축제'),collection=repository([post,video,festival]),manifest={collection:'regional_data_records',preImageSha256:documentHash(pre),expectedPostImageSha256:documentHash(post),expectedCurrentVersion:post.__v,videoSha256:documentHash(video),festivalSha256:documentHash(festival)};return{pre,post,video,festival,collection,manifest}};

test('defaults to a no-write dry-run and reports only hashes and fixed identity',async()=>{const f=fixture(),result=await runReceipt32Restore({collection:f.collection,preImage:f.pre,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 controlled rollback'});assert.equal(result.mode,'DRY_RUN');assert.equal(f.collection.writes,0);assert.deepEqual(result.target,TARGET);assert.equal(JSON.stringify(result).includes('합천영상테마파크'),false)});
test('requires --apply, fixed confirmation and explicit approval together',()=>{assert.equal(assertApplyAuthorization({}),false);assert.throws(()=>assertApplyAuthorization({apply:true,confirm:'wrong',approved:'true'}),/confirmation/);assert.throws(()=>assertApplyAuthorization({apply:true,confirm:'RESTORE_RECEIPT_32_6a851cba'}),/confirmation/);assert.equal(assertApplyAuthorization({apply:true,confirm:'RESTORE_RECEIPT_32_6a851cba',approved:'true'}),true)});
test('refuses mismatched pre-image hash, version and expected post-image without writing',async()=>{for(const change of[{preImageSha256:'0'.repeat(64)},{expectedCurrentVersion:99},{expectedPostImageSha256:'f'.repeat(64)}]){const f=fixture();await assert.rejects(runReceipt32Restore({collection:f.collection,preImage:f.pre,manifest:{...f.manifest,...change},actorId:'OPS_01',reason:'receipt 32 controlled rollback'}),/refused/);assert.equal(f.collection.writes,0)}});
test('refuses zero or multiple target matches without writing',async()=>{for(const rows of[[],[current(preImage()),current(preImage())]]){const f=fixture(),collection=repository([...rows,f.video,f.festival]);await assert.rejects(runReceipt32Restore({collection,preImage:f.pre,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 controlled rollback'}),/target count/);assert.equal(collection.writes,0)}});
test('restores only allowlisted facts, appends audit and preserves both neighbor hashes',async()=>{const f=fixture(),videoHash=documentHash(f.video),festivalHash=documentHash(f.festival),result=await runReceipt32Restore({collection:f.collection,preImage:f.pre,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 controlled rollback',apply:true}),after=f.collection.rows[0],{at,...audit}=after.auditTrail.at(-1);assert.equal(result.mode,'APPLIED');assert.equal(after.lifecycleStatus,'CHANGE_DETECTED');assert.deepEqual(after.detectedChanges,f.pre.detectedChanges);assert.deepEqual(after.proposedFacts,f.pre.proposedFacts);assert.equal(after.displayName,'합천 정원테마파크');assert.match(at,/^\d{4}-/);assert.deepEqual(audit,{action:'RESTORE_IGNORE_CHANGE',actorId:'OPS_01',regionId:'hapcheon',reason:'receipt 32 controlled rollback',preImageSha256:f.manifest.preImageSha256,restoredFields:['lifecycleStatus','detectedChanges','proposedFacts']});assert.equal(documentHash(f.collection.rows[1]),videoHash);assert.equal(documentHash(f.collection.rows[2]),festivalHash)});
test('refuses a changed neighbor and invalid actor without writing',async()=>{const changed=fixture();changed.video.displayName='다른 이름';await assert.rejects(runReceipt32Restore({collection:changed.collection,preImage:changed.pre,manifest:changed.manifest,actorId:'OPS_01',reason:'receipt 32 controlled rollback'}),/video SHA-256/);assert.equal(changed.collection.writes,0);const invalid=fixture();await assert.rejects(runReceipt32Restore({collection:invalid.collection,preImage:invalid.pre,manifest:invalid.manifest,actorId:'person@example.com',reason:'receipt 32 controlled rollback'}),/actorId/);assert.equal(invalid.collection.writes,0)});
