import test from'node:test';import assert from'node:assert/strict';import mongoose from'mongoose';import{CORE_AFTER,CORE_BEFORE,CORE_TARGET,authorizeCoreOperation,runCoreAlignment}from'./receipt32-core-align-core.mjs';import{documentHash}from'./receipt32-restore-core.mjs';
const{EJSON,ObjectId}=mongoose.mongo.BSON,clone=value=>EJSON.parse(EJSON.stringify(value,{relaxed:false}),{relaxed:false}),equal=(a,b)=>EJSON.stringify(a,{relaxed:false})===EJSON.stringify(b,{relaxed:false});
const core=()=>({_id:new ObjectId(CORE_TARGET._id),id:CORE_TARGET.id,regionId:CORE_TARGET.regionId,...clone(CORE_BEFORE),auditTrail:[{action:'CORE_DESTINATION_DESIGNATED',at:'2026-08-21T09:28:45.897Z'}],createdAt:new Date('2026-08-21T09:28:45.897Z'),updatedAt:new Date('2026-08-30T13:31:21.411Z'),__v:2}),other=()=>({_id:new ObjectId(),id:'core-hapcheon-hwangmaesan',regionId:'hapcheon',displayName:'황매산',canonicalEntityId:'https://hapcheon.example/ontology#hwangmaesanCountyPark',aliases:['황매산 군립공원'],expectedCategory:'TOURISM_NATURE',active:true,auditTrail:[],__v:1});
const matches=(row,query)=>Object.entries(query).every(([key,value])=>value&&typeof value==='object'&&'$ne'in value?!equal(row[key],value.$ne):equal(row[key],value));
const repository=(rows,mutateBeforeCas)=>({rows,writes:0,find(query){return{toArray:async()=>rows.filter(row=>matches(row,query)).map(clone)}},async findOneAndUpdate(query,update){mutateBeforeCas?.(rows);const found=rows.filter(row=>matches(row,query));if(found.length!==1)return null;const row=found[0];Object.assign(row,clone(update.$set));row.auditTrail.push(clone(update.$push.auditTrail));row.__v=Number(row.__v)+1;this.writes++;return clone(row)}});
const fixture=()=>{const target=core(),unrelated=other(),collection=repository([clone(target),clone(unrelated)]),manifest={collection:'coredestinations',preImageSha256:documentHash(target),expectedCurrentVersion:target.__v,otherCoreHashes:{[String(unrelated._id)]:documentHash(unrelated)}};return{target,unrelated,collection,manifest}};

test('alignment is dry-run by default and requires a distinct apply gate',async()=>{const f=fixture(),result=await runCoreAlignment({collection:f.collection,preImage:f.target,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 core identity alignment'});assert.equal(result.mode,'DRY_RUN');assert.equal(f.collection.writes,0);assert.equal(authorizeCoreOperation({}),false);assert.throws(()=>authorizeCoreOperation({apply:true,confirm:'wrong',approved:'true'}),/confirmation/);assert.equal(authorizeCoreOperation({apply:true,confirm:'ALIGN_RECEIPT_32_CORE_6a881a4d',approved:'true'}),true)});
test('aligns only the exact old core through one standalone atomic CAS',async()=>{const f=fixture(),otherHash=documentHash(f.unrelated),result=await runCoreAlignment({collection:f.collection,preImage:f.target,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 core identity alignment',apply:true}),after=f.collection.rows[0];assert.equal(result.mode,'ALIGNED');assert.equal(f.collection.writes,1);assert.equal(String(after._id),CORE_TARGET._id);assert.equal(after.id,CORE_TARGET.id);for(const[key,value]of Object.entries(CORE_AFTER))assert.deepEqual(after[key],value);assert.equal(after.aliases.includes('합천 정원테마파크'),false);assert.equal(after.auditTrail.at(-1).action,'CORE_DESTINATION_IDENTITY_ALIGNED');assert.equal(documentHash(f.collection.rows[1]),otherHash)});
test('refuses a duplicate new display name and compare-and-set races without writing',async()=>{const duplicate=fixture();duplicate.collection.rows.push({...other(),_id:new ObjectId(),displayName:CORE_AFTER.displayName});await assert.rejects(runCoreAlignment({collection:duplicate.collection,preImage:duplicate.target,manifest:duplicate.manifest,actorId:'OPS_01',reason:'receipt 32 core identity alignment',apply:true}),/conflicting/);assert.equal(duplicate.collection.writes,0);const raced=fixture(),collection=repository(raced.collection.rows,rows=>{rows[0].active=false});await assert.rejects(runCoreAlignment({collection,preImage:raced.target,manifest:raced.manifest,actorId:'OPS_01',reason:'receipt 32 core identity alignment',apply:true}),/compare-and-set/);assert.equal(collection.writes,0)});
test('an apply retry is idempotent and does not append another audit event',async()=>{const f=fixture(),args={collection:f.collection,preImage:f.target,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 core identity alignment',apply:true};await runCoreAlignment(args);const auditCount=f.collection.rows[0].auditTrail.length,result=await runCoreAlignment(args);assert.equal(result.mode,'ALREADY_ALIGNED');assert.equal(f.collection.writes,1);assert.equal(f.collection.rows[0].auditTrail.length,auditCount)});
test('restore uses its own gate and refuses mismatched aligned state without writing',async()=>{const f=fixture();await runCoreAlignment({collection:f.collection,preImage:f.target,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 core identity alignment',apply:true});const aligned=f.collection.rows[0];f.manifest.expectedAlignedImageSha256=documentHash(aligned);f.manifest.expectedCurrentVersion=aligned.__v;assert.throws(()=>authorizeCoreOperation({operation:'restore',apply:true,confirm:'ALIGN_RECEIPT_32_CORE_6a881a4d',approved:'true'}),/confirmation/);aligned.active=false;const writes=f.collection.writes;await assert.rejects(runCoreAlignment({collection:f.collection,preImage:f.target,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 core identity restoration',apply:true,operation:'restore'}),/expected restore state/);assert.equal(f.collection.writes,writes)});
test('restores the fixed core fields without truncating alignment audit',async()=>{const f=fixture();await runCoreAlignment({collection:f.collection,preImage:f.target,manifest:f.manifest,actorId:'OPS_01',reason:'receipt 32 core identity alignment',apply:true});const aligned=f.collection.rows[0];f.manifest.expectedAlignedImageSha256=documentHash(aligned);f.manifest.expectedCurrentVersion=aligned.__v;const result=await runCoreAlignment({collection:f.collection,preImage:f.target,manifest:f.manifest,actorId:'OPS_02',reason:'receipt 32 core identity restoration',apply:true,operation:'restore'}),after=f.collection.rows[0];assert.equal(result.mode,'RESTORED');for(const[key,value]of Object.entries(CORE_BEFORE))assert.deepEqual(after[key],value);assert.deepEqual(after.auditTrail.map(event=>event.action).slice(-2),['CORE_DESTINATION_IDENTITY_ALIGNED','RESTORE_CORE_DESTINATION_IDENTITY'])});
