import { Injectable } from '@nestjs/common';
export interface RegionConfig { id:string;regionName:string;administrativeLevel?:'district'|'city'|'county';parentRegionId?:string;serviceName:string;serviceAreaMessage:string;center?:{latitude:number;longitude:number};bounds?:{north:number;south:number;east:number;west:number};weatherReference?:{latitude:number;longitude:number;timezone:string;sourceId:string};ontologyNamespace:string;supportedCategories:string[];knownPlaces:string[];externalDestinations:Array<{pattern:RegExp;destination:string;region:string}> }
export const GAJO_REGION_CONFIG:RegionConfig={id:'gajo',regionName:'가조',serviceName:'가조 여행 동행',serviceAreaMessage:'현재는 가조 지역을 중심으로 안내하고 있어요. 가조에서 즐길 수 있는 장소를 찾아드릴까요?',center:{latitude:35.714,longitude:127.918},bounds:{north:35.84,south:35.58,east:128.05,west:127.78},weatherReference:{latitude:35.7423,longitude:127.9528,timezone:'Asia/Seoul',sourceId:'gajo-weather-reference'},ontologyNamespace:'https://gajo-wellness.kr/ontology#',supportedCategories:['FOOD','CAFE','ACTIVITY','TOURISM_NATURE'],knownPlaces:['백두산천지온천','거창 항노화힐링랜드'],externalDestinations:[{pattern:/해인사/,destination:'해인사',region:'합천'}]};
export const OKCHEON_REGION_CONFIG:RegionConfig={id:'okcheon',regionName:'옥천',serviceName:'옥천 여행안내',serviceAreaMessage:'현재는 옥천 지역을 중심으로 안내하고 있어요. 옥천에서 즐길 수 있는 장소를 찾아드릴까요?',ontologyNamespace:'https://okcheon.example/ontology#',supportedCategories:['LITERATURE_CULTURE','TRADITIONAL_CULTURE','TOURISM_NATURE','LAKE','FOOD','CAFE','INDOOR','REST'],knownPlaces:['정지용 생가','정지용문학관','옥천전통문화체험관'],externalDestinations:[{pattern:/해인사|가조온천|백두산천지온천/,destination:'요청한 외부 장소',region:'외부 지역'}]};
export const MUAN_REGION_CONFIG:RegionConfig={id:'muan',regionName:'무안',serviceName:'무안 여행안내',serviceAreaMessage:'현재는 무안 지역을 중심으로 안내하고 있어요. 무안에서 즐길 수 있는 장소를 찾아드릴까요?',ontologyNamespace:'https://muan.example/ontology#',supportedCategories:['LOTUS_ECOLOGY','FAMILY_TRIP','TOURISM_NATURE','MUDFLAT_COAST','ACTIVITY','FOOD','CAFE','REST','INDOOR'],knownPlaces:['회산백련지','회산백련지 일대'],externalDestinations:[{pattern:/해인사|가조온천|백두산천지온천|정지용|대청호/,destination:'요청한 외부 장소',region:'외부 지역'}]};
export const GYERYONG_REGION_CONFIG:RegionConfig={id:'gyeryong',regionName:'계룡',serviceName:'계룡 여행안내',serviceAreaMessage:'현재는 계룡 지역을 중심으로 안내하고 있어요. 계룡에서 즐길 수 있는 장소와 일정을 찾아드릴까요?',ontologyNamespace:'https://gyeryong.example/ontology#',supportedCategories:['MILITARY_CULTURE_HISTORY','FESTIVAL_EVENT','FAMILY_EXPERIENCE','TOURISM_NATURE','FOOD','CAFE','REST','INDOOR','LOCAL_CONVENIENCE'],knownPlaces:['계룡 군문화축제','계룡 군문화·행사권'],externalDestinations:[{pattern:/해인사|가조온천|백두산천지온천|정지용|대청호|회산백련지/,destination:'요청한 외부 장소',region:'외부 지역'}]};
export const HAPCHEON_REGION_CONFIG:RegionConfig={id:'hapcheon',regionName:'합천',serviceName:'합천 여행안내',serviceAreaMessage:'현재는 합천호 권역을 중심으로 안내하고 있어요. 합천에서 즐길 수 있는 장소와 일정을 찾아드릴까요?',center:{latitude:35.55,longitude:128.05},bounds:{north:35.84,south:35.45,east:128.18,west:127.95},weatherReference:{latitude:35.55,longitude:128.05,timezone:'Asia/Seoul',sourceId:'hapcheon-verified-data-center'},ontologyNamespace:'https://hapcheon.example/ontology#',supportedCategories:['HAPCHEON_LAKE','TOURISM_NATURE','SCENIC_DRIVE','FAMILY_TRIP','ACCOMMODATION','FOOD','CAFE','REST','ACTIVITY'],knownPlaces:['합천호','해인사','황매산','합천영상테마파크','합천호 스마일펜션'],externalDestinations:[{pattern:/가조온천|백두산천지온천|정지용|대청호|회산백련지|계룡 군문화축제/,destination:'요청한 외부 장소',region:'외부 지역'}]};
export const DAEJEON_JUNGGU_REGION_CONFIG:RegionConfig={id:'daejeon-junggu',regionName:'대전 중구',administrativeLevel:'district',parentRegionId:'daejeon',serviceName:'대전 중구 여행안내',serviceAreaMessage:'현재는 대전 중구를 중심으로 안내하고 있어요.\n중구에서 지금 즐길 수 있는 장소와 일정을 찾아드릴까요?',ontologyNamespace:'https://daejeon-junggu.example/ontology#',supportedCategories:['URBAN_CULTURE','TRADITIONAL_MARKET','FOOD','CAFE','PERFORMANCE_EXHIBITION','FAMILY_OUTING','WALKING','SHOPPING','LOCAL_CONVENIENCE','REST'],knownPlaces:['은행동·중앙로 문화권','으능정이 문화의거리','대전 중앙시장','대흥동 문화예술권'],externalDestinations:[{pattern:/가조온천|백두산천지온천|정지용|대청호|회산백련지|계룡 군문화축제|합천호|스마일펜션/,destination:'요청한 외부 장소',region:'외부 지역'}]};
export const REGION_CONFIGS:Record<string,RegionConfig>={gajo:GAJO_REGION_CONFIG,okcheon:OKCHEON_REGION_CONFIG,muan:MUAN_REGION_CONFIG,gyeryong:GYERYONG_REGION_CONFIG,hapcheon:HAPCHEON_REGION_CONFIG,'daejeon-junggu':DAEJEON_JUNGGU_REGION_CONFIG};
@Injectable()export class RegionConfigService{readonly current=GAJO_REGION_CONFIG;get(regionId?:string){return REGION_CONFIGS[regionId||'gajo']||GAJO_REGION_CONFIG}detectOutOfRegion(message?:string,regionId?:string){const config=this.get(regionId);if(!message||message.includes(config.regionName)||config.knownPlaces.some(place=>message.includes(place)))return undefined;const match=config.externalDestinations.find(item=>item.pattern.test(message)&&/가고|갈래|놀러|여행|방문|관광/.test(message));return match&&{destination:match.destination,region:match.region}}}
