import {PlaceWeatherContextProvider} from './place-weather-context.provider';

const live={observedAt:'2026-09-01T00:00:00.000Z',weather:'CLOUDY',temperature:7,windSpeed:11,source:'OPEN_METEO',status:'LIVE',stale:false};
const record=(id:string,latitude?:number,longitude?:number)=>({entityUri:id,latitude,longitude,operationalTips:[{id:'weather',trigger:{temperatureAtMost:8},priority:1,message:'tip',provenance:{},realtimeRequired:true}]});
const create=(observation:any=live,values:Record<string,unknown>={})=>{
  const weather={getCurrent:jest.fn(async()=>observation)},hydration={hydrate:jest.fn((base:any,current:any)=>({context:{...base,temperature:current.temperature,windSpeed:current.windSpeed,weather:current.weather,weatherState:current.weather,weatherObservation:{observedAt:current.observedAt,source:current.source,status:current.status,stale:current.stale}}}))},config={get:jest.fn((key:string)=>values[key])};
  return{provider:new PlaceWeatherContextProvider(weather as any,hydration as any,config as any),weather,hydration};
};

describe('PlaceWeatherContextProvider',()=>{
  it('deduplicates identical coordinates within one request and preserves each entity identity',async()=>{const{provider,weather}=create(),contexts=await provider.contextsForRecords('hapcheon',[record('a',35.5,128.1),record('b',35.5,128.1)],{companions:[{relationship:'family'}]},new Date('2026-09-01T00:05:00Z'));expect(weather.getCurrent).toHaveBeenCalledTimes(1);expect([...contexts.keys()]).toEqual(['a','b']);expect(contexts.get('a').companions).toEqual([{relationship:'family'}])});
  it('does not call outside services for missing coordinates or records without realtime weather tips',async()=>{const{provider,weather}=create();const contexts=await provider.contextsForRecords('hapcheon',[record('missing'),{...record('general',35.5,128.1),operationalTips:[]}]);expect(contexts.size).toBe(0);expect(weather.getCurrent).not.toHaveBeenCalled()});
  it('limits unique external calls and starts them in parallel',async()=>{const{provider,weather}=create(live,{PLACE_WEATHER_MAX_CALLS_PER_REQUEST:2});const contexts=await provider.contextsForRecords('hapcheon',[record('a',35.1,128.1),record('b',35.2,128.2),record('c',35.3,128.3)]);expect(weather.getCurrent).toHaveBeenCalledTimes(2);expect([...contexts.keys()]).toEqual(['a','b'])});
  it.each([{...live,status:'STALE',stale:true},{...live,status:'UNAVAILABLE',source:'UNAVAILABLE'}])('rejects stale or unproven observations without caching them',async observation=>{const{provider,weather}=create(observation);expect((await provider.contextsForRecords('hapcheon',[record('a',35.5,128.1)])).size).toBe(0);expect((await provider.contextsForRecords('hapcheon',[record('a',35.5,128.1)])).size).toBe(0);expect(weather.getCurrent).toHaveBeenCalledTimes(2)});
  it('falls back without throwing when the provider fails',async()=>{const{provider,weather}=create();weather.getCurrent.mockRejectedValue(new Error('offline'));await expect(provider.contextsForRecords('hapcheon',[record('a',35.5,128.1)])).resolves.toEqual(new Map())});
  it('uses the five minute cache without leaking the first visitor context',async()=>{const{provider,weather}=create();await provider.contextsForRecords('hapcheon',[record('a',35.5,128.1)],{companions:[{relationship:'parent'}]},new Date('2026-09-01T00:00:00Z'));const second=await provider.contextsForRecords('hapcheon',[record('a',35.5,128.1)],{companions:[{relationship:'child'}]},new Date('2026-09-01T00:04:00Z'));expect(weather.getCurrent).toHaveBeenCalledTimes(1);expect(second.get('a').companions).toEqual([{relationship:'child'}])});
});
