import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { randomUUID } from 'crypto';
import { RegionalDataService } from '../regional-data/regional-data.service';
import { CopilotCandidate, CopilotCandidateDocument } from './copilot-candidate.schema';
import { assertCopilotAccess, CopilotPrincipal } from './copilot-auth';

@Injectable()
export class CopilotService {
  constructor(@InjectModel(CopilotCandidate.name)private model:Model<CopilotCandidateDocument>,private regional:RegionalDataService){}
  private normalize(value=''){return value.normalize('NFKC').toLocaleLowerCase('ko-KR').replace(/[^0-9a-z가-힣]/g,'')}
  async ingestSearchCandidate(input:any){
    if(!input?.regionId||!input?.displayName||!input?.category||!input?.evidence?.sourceType)throw new BadRequestException('Structured search evidence is required');
    const fingerprint=this.normalize(`${input.displayName}:${input.address||''}:${input.phone||''}`),now=new Date().toISOString();
    const safe={id:`cop-${randomUUID()}`,regionId:input.regionId,fingerprint,displayName:input.displayName,category:input.category,entityType:input.entityType||input.category,address:input.address,phone:input.phone,latitude:input.latitude,longitude:input.longitude,provenance:{name:input.evidence,address:input.address?input.evidence:undefined,phone:input.phone?input.evidence:undefined,coordinates:Number.isFinite(input.latitude)&&Number.isFinite(input.longitude)?input.evidence:undefined},evidence:{sourceType:input.evidence.sourceType,sourceUrl:input.evidence.sourceUrl,providerCategory:input.evidence.providerCategory,discoveredAt:input.evidence.discoveredAt||now},status:'DISCOVERED' as const,auditTrail:[{action:'SEARCH_CANDIDATE_INGESTED',at:now,source:{sourceType:input.evidence.sourceType}}]};
    const existing:any=await this.model.findOne({regionId:input.regionId,fingerprint});if(existing)return existing.toObject();
    const created:any=await this.model.create(safe);return created.toObject();
  }
  async queue(user:CopilotPrincipal,regionId:string){assertCopilotAccess(user,regionId);const candidates:any[]=await this.model.find({regionId,status:{$nin:['ACTIVE','REJECTED']}}).lean(),rdm:any[]=await this.regional.list({regionId});const tasks=[...candidates.map(x=>({taskId:`candidate:${x.id}`,regionId,type:'SEARCH_DISCOVERED_ENTITY',priority:x.status==='REVIEW'?1:2,candidate:x,reason:'관광객 검색에서 발견됐지만 VERIFIED RDM 일치 항목이 없습니다.',evidence:x.evidence,createdAt:(x as any).createdAt,status:x.status})),...rdm.filter(x=>['NEW_CANDIDATE','NEEDS_VERIFICATION','CHANGE_DETECTED'].includes(x.lifecycleStatus)).map(x=>({taskId:`rdm:${x.id}`,regionId,type:x.lifecycleStatus==='CHANGE_DETECTED'?'DATA_CHANGE_CANDIDATE':'UNVERIFIED_ENTITY',priority:1,entity:x,reason:'운영 데이터 반영 전에 관리자 확인이 필요합니다.',evidence:x.source,createdAt:(x as any).createdAt,status:x.lifecycleStatus}))];return tasks.sort((a,b)=>a.priority-b.priority)}
  async detail(user:CopilotPrincipal,id:string){const row:any=await this.model.findOne({id});if(!row)throw new NotFoundException();assertCopilotAccess(user,row.regionId);const duplicates=await this.duplicates(row);return{candidate:row.toObject(),duplicateWarning:duplicates.length?'기존 업체와 동일할 가능성이 있습니다.':undefined,possibleDuplicates:duplicates,why:['관광객 검색에서 발견됨','VERIFIED RDM 일치 항목 없음','지역 운영정보 반영 전 사람의 검토 필요']}}
  async review(user:CopilotPrincipal,id:string,edited:any={}){const row:any=await this.model.findOne({id});if(!row)throw new NotFoundException();assertCopilotAccess(user,row.regionId,true);if(!['DISCOVERED','CANDIDATE','NEEDS_MORE_EVIDENCE','REVIEW'].includes(row.status))throw new BadRequestException('Candidate cannot be reviewed');const allowed=['displayName','category','entityType','address','phone','latitude','longitude'];const previous=Object.fromEntries(allowed.map(k=>[k,row[k]]));for(const key of allowed)if(edited[key]!==undefined)row[key]=edited[key];row.status='REVIEW';row.auditTrail.push({action:Object.keys(edited).length?'CANDIDATE_EDITED':'CANDIDATE_REVIEWED',actorId:user.sub,regionId:row.regionId,previous,newValue:Object.fromEntries(allowed.map(k=>[k,row[k]])),at:new Date().toISOString()});await row.save();return row.toObject()}
  async activate(user:CopilotPrincipal,id:string,confirmed:boolean,duplicateAcknowledged=false){const row:any=await this.model.findOne({id});if(!row)throw new NotFoundException();assertCopilotAccess(user,row.regionId,true);if(!confirmed)throw new ForbiddenException('Explicit human confirmation required');if(!['REVIEW','VERIFIED'].includes(row.status))throw new BadRequestException('Candidate must be reviewed first');if(!row.displayName||!row.category||!row.evidence?.sourceUrl)throw new BadRequestException('Required operational facts are missing');const duplicates=await this.duplicates(row);if(duplicates.length&&!duplicateAcknowledged)throw new ConflictException('Potential duplicate requires manager acknowledgement');if(row.status==='REVIEW'){row.status='VERIFIED';row.auditTrail.push({action:'CANDIDATE_VERIFIED',actorId:user.sub,regionId:row.regionId,previous:'REVIEW',newValue:'VERIFIED',at:new Date().toISOString()});await row.save()}const created:any=await this.regional.create({regionId:row.regionId,source:{sourceType:'OFFICIAL_MAP_LISTING',sourceUrl:row.evidence.sourceUrl,sourceName:row.evidence.sourceType},proposedFacts:{displayName:row.displayName,entityType:row.entityType,category:row.category,address:row.address,phone:row.phone,latitude:row.latitude,longitude:row.longitude}});const active:any=await this.regional.action(created.id,'APPROVE',undefined,{actorId:user.sub,regionId:row.regionId,action:'CANDIDATE_VERIFIED'});row.status='ACTIVE';row.activatedEntityId=active.canonicalEntityId;row.auditTrail.push({action:'ENTITY_ACTIVATED',actorId:user.sub,regionId:row.regionId,previous:'VERIFIED',newValue:'ACTIVE',at:new Date().toISOString()});await row.save();return{candidate:row.toObject(),regionalEntity:active}}
  async reject(user:CopilotPrincipal,id:string){const row:any=await this.model.findOne({id});if(!row)throw new NotFoundException();assertCopilotAccess(user,row.regionId,true);if(row.status==='ACTIVE')throw new BadRequestException('Active entity must be managed through RDM');row.status='REJECTED';row.auditTrail.push({action:'ENTITY_REJECTED',actorId:user.sub,regionId:row.regionId,previous:'REVIEW',newValue:'REJECTED',at:new Date().toISOString()});await row.save();return row.toObject()}
  private async duplicates(row:any){const records:any[]=await this.regional.list({regionId:row.regionId});const name=this.normalize(row.displayName);return records.filter(x=>this.normalize(x.displayName)===name||Boolean(row.phone&&x.phone===row.phone)||(Number.isFinite(row.latitude)&&Number.isFinite(x.latitude)&&Math.hypot((row.latitude-x.latitude)*111000,(row.longitude-x.longitude)*88000)<30)).map(x=>({id:x.id,displayName:x.displayName,canonicalEntityId:x.canonicalEntityId}))}
}
