import { authoritativeSafetyEvidence } from '../concierge/essential-services';
import { DISCOVERY_CATEGORY_MATCH } from '../concierge/discovery-eligibility';

export type HeatShelterCoverageStatus = 'COVERAGE_SUFFICIENT' | 'COVERAGE_GAP_CANDIDATE' | 'DATA_INSUFFICIENT';

const distanceMeters=(a:any,b:any)=>{if(![a?.latitude,a?.longitude,b?.latitude,b?.longitude].every(Number.isFinite))return undefined;const lat=((a.latitude+b.latitude)/2)*Math.PI/180;return Math.round(Math.hypot((a.latitude-b.latitude)*111000,(a.longitude-b.longitude)*111000*Math.cos(lat)))};

export function diagnoseHeatShelterCoverage(regionId:string,records:readonly any[],coreDestinations:readonly any[],thresholdMeters=2000){
  const shelters=records.filter(record=>record?.regionId===regionId&&DISCOVERY_CATEGORY_MATCH.HEAT_SHELTER(record)&&authoritativeSafetyEvidence(record)&&Number.isFinite(record.latitude)&&Number.isFinite(record.longitude));
  const anchors=coreDestinations.map(core=>{const record=records.find(item=>item?.regionId===regionId&&(item.entityUri===core.canonicalEntityId||[item.canonicalLabelKo,...(item.alternateLabels||[])].some((name:string)=>[core.displayName,...(core.aliases||[])].includes(name))));if(!record||!Number.isFinite(record.latitude)||!Number.isFinite(record.longitude))return{coreDestination:core.displayName,status:'DATA_INSUFFICIENT' as const,reason:'Core Destination의 검증된 좌표가 없어 거리 기반 쉼터 진단을 할 수 없습니다.'};if(!shelters.length)return{coreDestination:core.displayName,status:'DATA_INSUFFICIENT' as const,reason:'공식·승인된 무더위쉼터 위치 데이터가 없어 coverage 결론을 내릴 수 없습니다.'};const nearest=shelters.map(shelter=>({shelter,distanceMeters:distanceMeters(record,shelter)!})).sort((a,b)=>a.distanceMeters-b.distanceMeters)[0];return nearest.distanceMeters<=thresholdMeters?{coreDestination:core.displayName,status:'COVERAGE_SUFFICIENT' as const,nearestShelter:nearest.shelter.canonicalLabelKo,distanceMeters:nearest.distanceMeters,reason:`설정된 ${thresholdMeters}m 기준 안에 공식 쉼터 위치가 있습니다.`}:{coreDestination:core.displayName,status:'COVERAGE_GAP_CANDIDATE' as const,nearestShelter:nearest.shelter.canonicalLabelKo,distanceMeters:nearest.distanceMeters,reason:`가장 가까운 공식 쉼터가 설정된 ${thresholdMeters}m 기준 밖에 있어 사람의 검토가 필요합니다.`}});
  const status:HeatShelterCoverageStatus=!anchors.length||anchors.every(x=>x.status==='DATA_INSUFFICIENT')?'DATA_INSUFFICIENT':anchors.some(x=>x.status==='COVERAGE_GAP_CANDIDATE')?'COVERAGE_GAP_CANDIDATE':anchors.some(x=>x.status==='DATA_INSUFFICIENT')?'DATA_INSUFFICIENT':'COVERAGE_SUFFICIENT';
  return{regionId,category:'HEAT_SHELTER',status,thresholdMeters,officialShelterCount:shelters.length,anchors,limitations:['유동인구와 고령인구 밀도 데이터는 현재 통합되어 있지 않아 추정하지 않습니다.','운영시간·냉방 작동·현재 수용 가능 인원·직원 상주·접근 가능한 좌석은 별도 근거 없이는 판단하지 않습니다.'],policyBoundary:'COVERAGE_GAP_CANDIDATE는 검토 신호이며 시설 지정·설치 결론이 아닙니다. 최종 판단은 권한 있는 지자체와 담당자가 합니다.',readOnly:true};
}
